openapi: 3.0.1
info:
  contact:
    email: api-support@onshape.zendesk.com
  description: |-
    ## Welcome to the Onshape REST API Explorer

    To use this API explorer, sign in to your [Onshape](https://cad.onshape.com) account in another tab, then click the **Try it out** button below (it toggles to a **Cancel** button when selected).

    See the **[API Explorer Guide](https://onshape-public.github.io/docs/api-intro/explorer/)** for help navigating this API Explorer, including **[authentication](https://onshape-public.github.io/docs/api-intro/explorer/#authentication)**.

    **Tip:** To ensure the current session isn't used when trying other authentication techniques, make sure to [remove the Onshape cookie](https://support.google.com/chrome/answer/95647#zippy=%2Cdelete-cookies-from-a-site) as per the instructions for your browser. Alternatively, you can use a private or incognito window.

    ## See Also

    * [Onshape API Guide](https://onshape-public.github.io/docs/): Our full suite of developer guides, to be used as an accompaniment to this API Explorer.
    * [Onshape Developer Portal](https://dev-portal.onshape.com/): The Onshape portal for managing your API keys, OAuth2 credentials, your Onshape applications, and your Onshape App Store entries.
    * [Authentication Guide](https://onshape-public.github.io/docs/auth/): Our guide to using API keys, request signatures, and OAuth2 in  your Onshape applications.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://www.onshape.com/legal/terms-of-use
  title: Onshape REST API
  version: 1.189.45668-bc4b86074dbb
  x-logo:
    url: images/logo-onshape-gray-green.svg
    backgroundColor: '#ffffff'
    altText: Onshape
    href: images/logo-onshape-gray-green.svg
  x-indeterministic-schemas:
  - BTDiffInfo
  - BTParameterSpecArray-2600
  - BTSplineDescription-2118
  - NodeModel
  - BTPFunctionDeclaration-246
  - BTPFunctionOrPredicateDeclaration-247
  - BTPExpression-9
  - SkinModel
  - BTMAnnotation-4664
  x-filter-info: ?restUserRole=PUBLIC
servers:
- description: Current
  url: https://cad.onshape.com/api/v9
security:
- BasicAuth: []
tags:
- description: Manage application preferences.
  name: APIApplication
- description: "Manage user purchases, subscriptions, and consumables."
  name: Account
- description: Create and manage enterprise aliases. (Enterprise admins only.)
  name: Alias
- description: Manage the application-specific metadata that associates application
    data with Onshape data.
  name: AppAssociativeData
- description: Access and modify application elements.
  name: AppElement
- description: Create and manage assemblies.
  name: Assembly
- description: Get billing plan data for applications.
  name: Billing
- description: "Create, modify, and translate blob elements."
  name: BlobElement
- description: "Create, read, update, and delete comments."
  name: Comment
- description: Access company information.
  name: Company
- description: Create and manage documents.
  name: Document
- description: "Access, create, and translate drawings."
  name: Drawing
- description: Access and manage Elements. Every Element in an Onshape document is
    represented by a tab.
  name: Element
- description: Access valid export rules.
  name: ExportRule
- description: Access and manage Feature Studio Elements.
  name: FeatureStudio
- description: Access and modify folder sharing permissions.
  name: Folder
- description: Access the list of things that can be inserted into a document.
  name: Insertable
- description: Access and modify metadata.
  name: Metadata
- description: Access properties associated with metadata categories.
  name: MetadataCategory
- description: Manage the set of valid Part numbers.
  name: NumberingScheme
- description: Get the OpenAPI specification for the Onshape API.
  name: OpenApi
- description: Export Parts and access Part details.
  name: Part
- description: Create valid part numbers.
  name: PartNumber
- description: Access and modify Part Studios.
  name: PartStudio
- description: "Create, access, and delete templates for properties tables."
  name: PropertiesTableTemplate
- description: Access publication information.
  name: Publication
- description: Access and update Release Management workflows.
  name: ReleasePackage
- description: "Access, delete, and enumerate revisions."
  name: Revision
- description: Access sketch information.
  name: Sketch
- description: "Create, access, and modify Tasks and Action Items."
  name: Task
- description: Access team information.
  name: Team
- description: "Access, modify, and delete thumbnails."
  name: Thumbnail
- description: "Import and export Onshape surfaces, parts, Part Studios, Assemblies,\
    \ and subassemblies to/from other file formats (STL, PARASOLID, SOLIDWORKS, etc)."
  name: Translation
- description: Access user information.
  name: User
- description: "Create, modify, and access variables."
  name: Variables
- description: Get all versions of the Onshape REST APIs.
  name: Version
- description: "Create and manage [webhooks](https://onshape-public.github.io/docs/app-dev/webhook/)."
  name: Webhook
- description: Access and modify workflows.
  name: Workflow
paths:
  /accounts/plans/{planId}/purchases:
    get:
      deprecated: false
      operationId: getPlanPurchases
      summary: Get a list of all app purchases made for the specified plan.
      tags:
      - Account
      x-BTVisibility: PRODUCTION
  /accounts/purchases:
    get:
      deprecated: false
      description: This API should be used within the context of an OAuth-enabled
        application.
      operationId: getPurchases
      summary: Get a list of all app purchases made by the current user.
      tags:
      - Account
      x-BTVisibility: PRODUCTION
  /accounts/purchases/{pid}/consume:
    post:
      deprecated: false
      operationId: consumePurchase
      security:
      - OAuth2:
        - OAuth2Purchase
        BasicAuth:
        - OAuth2Purchase
      summary: Mark a purchase as consumed by the current user.
      tags:
      - Account
      x-BTVisibility: PRODUCTION
  /accounts/{aid}/purchases/{pid}:
    delete:
      deprecated: false
      operationId: cancelPurchaseNew
      security:
      - OAuth2:
        - OAuth2Purchase
        BasicAuth:
        - OAuth2Purchase
      summary: Cancel a recurring subscription for the specified account ID and purchase
        ID.
      tags:
      - Account
      x-BTVisibility: PRODUCTION
  /aliases:
    get:
      deprecated: false
      operationId: getAliasesInCompany
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get a list of all aliases that exist for your enterprise.
      tags:
      - Alias
      x-BTVisibility: PRODUCTION
    post:
      deprecated: false
      description: '`Manage users and teams` global permission is required to call
        this API.'
      operationId: createAlias
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Create an alias in your enterprise.
      tags:
      - Alias
      x-BTVisibility: PRODUCTION
  /aliases/{aid}:
    delete:
      deprecated: false
      description: '`Manage users and teams` global permission is required to call
        this API.'
      operationId: deleteAlias
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Delete an alias from your enterprise.
      tags:
      - Alias
      x-BTVisibility: PRODUCTION
    get:
      deprecated: false
      description: Get the information for an alias ID.
      operationId: getAlias
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get an alias by ID.
      tags:
      - Alias
      x-BTVisibility: PRODUCTION
    post:
      deprecated: false
      description: "`Manage users and teams` global permission is required to call\
        \ this API. \n* Add new users in the `additions` array. \n* Remove existing\
        \ users in the `removals` array. Attempts to remove a user that does not exist\
        \ in the Alias list will have no effect.\n* Replace the entire Alias list\
        \ with the `entries` array. \n* You can also update the alias' `name` and\
        \ `description`. \nFor example, given an Alias with members userA and userB:\
        \ \n* `additions: [userC]` results in [userA, userB, userC] \n* `removals:\
        \ [userB]` results in [userA] \n* `entries: [userC, user D]` results in [userC,\
        \ userD]"
      operationId: updateAlias
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: "Add, remove, replace, or rename entries in an alias list."
      tags:
      - Alias
      x-BTVisibility: PRODUCTION
  /aliases/{aid}/members:
    get:
      deprecated: false
      description: This is a search-like endpoint that returns a subset of the member
        list. Use `getAlias` to return all members every time it's called.
      operationId: getAliasMembers
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get all users and teams assigned to an alias.
      tags:
      - Alias
      x-BTVisibility: PRODUCTION
  /appelements/d/{did}/w/{wid}:
    post:
      deprecated: false
      operationId: createElement
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Create a new application element.
      tags:
      - AppElement
      x-BTVisibility: PRODUCTION
  /appelements/d/{did}/w/{wid}/bulkcreate:
    post:
      deprecated: false
      description: Call this faster API instead of creating multiple app elements
        one at a time or in parallel.
      operationId: bulkCreateElement
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Create multiple empty application elements at once.
      tags:
      - AppElement
      x-BTVisibility: PRODUCTION
  /appelements/d/{did}/w/{wid}/e/{eid}/blob/{bid}:
    delete:
      deprecated: false
      operationId: deleteBlobSubelement
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Delete a blob subelement from an app element.
      tags:
      - AppElement
      x-BTVisibility: PRODUCTION
    get:
      deprecated: false
      description: The downloaded file can be used to retrieve stored subelements.
      operationId: downloadBlobSubelementWorkspace
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: "Download the blob element (i.e., a file) stored in an app element\
        \ in a document's workspace."
      tags:
      - AppElement
      x-BTVisibility: PRODUCTION
    post:
      deprecated: false
      description: "Request body parameters are multipart fields, so you must use\
        \ `\"Content-Type\":\"multipart/form-data\"` in the request header."
      operationId: uploadBlobSubelement
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Create a new blob subelement from an uploaded file.
      tags:
      - AppElement
      x-BTVisibility: PRODUCTION
  /appelements/d/{did}/w/{wid}/e/{eid}/copyassociativedata:
    post:
      deprecated: false
      description: "Can only be copied between tabs in the same document. You can\
        \ manage associativity with [translateIds](https://cad.onshape.com/glassworks/explorer/#/PartStudio/translateIds)."
      operationId: copyAssociativeData
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Copy associative data from one view to another.
      tags:
      - AppAssociativeData
      x-BTVisibility: PRODUCTION
  /appelements/d/{did}/w/{wid}/e/{eid}/transactions:
    get:
      deprecated: false
      operationId: getElementTransactions
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get a list of all transactions performed on an element.
      tags:
      - AppElement
      x-BTVisibility: PRODUCTION
    post:
      deprecated: false
      description: "Creates a microbranch (i.e., a branch for a new microversion)."
      operationId: startTransaction
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Start a transaction
      tags:
      - AppElement
      x-BTVisibility: PRODUCTION
  /appelements/d/{did}/w/{wid}/e/{eid}/transactions/{tid}:
    delete:
      deprecated: false
      description: "Deletes a microbranch (i.e., the branch with the microversion\
        \ for the transaction)."
      operationId: abortTransaction
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Abort a transaction.
      tags:
      - AppElement
      x-BTVisibility: PRODUCTION
  /appelements/d/{did}/w/{wid}/transactions:
    post:
      deprecated: false
      description: "If successful, all transactions will be committed to a single\
        \ microversion. If the call raises an error, nothing will be committed."
      operationId: commitTransactions
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Merge multiple transactions into one microversion.
      tags:
      - AppElement
      x-BTVisibility: PRODUCTION
  /appelements/d/{did}/{vm}/{vmid}/e/{eid}/blob/{bid}:
    get:
      deprecated: false
      description: Download a blob subelement as a file.
      operationId: downloadBlobSubelement
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Download a blob subelement from the specified app element.
      tags:
      - AppElement
      x-BTVisibility: PRODUCTION
  /appelements/d/{did}/{wvm}/{wvmid}/e/{eid}/associativedata:
    delete:
      deprecated: false
      description: "You can manage associativity with [translateIds](https://cad.onshape.com/glassworks/explorer/#/PartStudio/translateIds)."
      operationId: deleteAssociativeData
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Delete the associative data from the specified app element.
      tags:
      - AppAssociativeData
      x-BTVisibility: PRODUCTION
    get:
      deprecated: false
      description: "You can manage associativity with [translateIds](https://cad.onshape.com/glassworks/explorer/#/PartStudio/translateIds)."
      operationId: getAssociativeData
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get the associative data for the specified app element.
      tags:
      - AppAssociativeData
      x-BTVisibility: PRODUCTION
    post:
      deprecated: false
      description: "You can manage associativity with [translateIds](https://cad.onshape.com/glassworks/explorer/#/PartStudio/translateIds)."
      operationId: postAssociativeData
      security:
      - OAuth2:
        - OAuth2Read
        - OAuth2Write
        BasicAuth:
        - OAuth2Read
        - OAuth2Write
      summary: Set the associative data for the specified app element.
      tags:
      - AppAssociativeData
      x-BTVisibility: PRODUCTION
  /appelements/d/{did}/{wvm}/{wvmid}/e/{eid}/blob:
    get:
      deprecated: false
      operationId: getBlobSubelementIds
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: "Get a list of all blob subelement IDs for the specified workspace,\
        \ version, or microversion."
      tags:
      - AppElement
      x-BTVisibility: PRODUCTION
  /appelements/d/{did}/{wvm}/{wvmid}/e/{eid}/compare:
    get:
      deprecated: false
      description: Specify the source workspace/version/microversion in the URL and
        specify the target workspace/version/microversion in the query parameters.
      operationId: compareAppElementJson
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Compare app element JSON trees between workspaces/versions/microversions
        in a document.
      tags:
      - AppElement
      x-BTVisibility: PRODUCTION
  /appelements/d/{did}/{wvm}/{wvmid}/e/{eid}/content:
    get:
      deprecated: false
      operationId: getSubElementContent
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get a list of all subelement IDs in a specified workspace/version/microversion.
      tags:
      - AppElement
      x-BTVisibility: PRODUCTION
    post:
      deprecated: false
      operationId: updateAppElement
      security:
      - OAuth2:
        - OAuth2Read
        - OAuth2Write
        BasicAuth:
        - OAuth2Read
        - OAuth2Write
      summary: Update the content for the specified app element.
      tags:
      - AppElement
      x-BTVisibility: PRODUCTION
  /appelements/d/{did}/{wvm}/{wvmid}/e/{eid}/content/history:
    get:
      deprecated: false
      operationId: getAppElementHistory
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get the history of the specified all element.
      tags:
      - AppElement
      x-BTVisibility: PRODUCTION
  /appelements/d/{did}/{wvm}/{wvmid}/e/{eid}/content/ids:
    get:
      deprecated: false
      operationId: getSubelementIds
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get a list of all subelement IDs in a specified workspace/version/microversion.
      tags:
      - AppElement
      x-BTVisibility: PRODUCTION
  /appelements/d/{did}/{wvm}/{wvmid}/e/{eid}/content/json:
    get:
      deprecated: false
      operationId: getJson
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get the full JSON tree for the specified workspace/version/microversion.
      tags:
      - AppElement
      x-BTVisibility: PRODUCTION
  /appelements/d/{did}/{wvm}/{wvmid}/e/{eid}/content/jsonpaths:
    post:
      deprecated: false
      description: Use this endpoint to return the JSON at the specified path instead
        of returning the entire JSON for the element. This POST endpoint does not
        write any information.
      operationId: getJsonPaths
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get the JSON at specified paths for an element.
      tags:
      - AppElement
      x-BTVisibility: PRODUCTION
  /appelements/d/{did}/{wvm}/{wvmid}/e/{eid}/content/subelements:
    delete:
      deprecated: false
      operationId: deleteAppElementContentBatch
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: "Delete multiple subelements array by document ID, workspace or version\
        \ or microversion ID, tab ID, and subelement IDs."
      tags:
      - AppElement
      x-BTVisibility: PRODUCTION
  /appelements/d/{did}/{wvm}/{wvmid}/e/{eid}/content/subelements/{sid}:
    delete:
      deprecated: false
      operationId: deleteAppElementContent
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Deletes the content from the specified app element.
      tags:
      - AppElement
      x-BTVisibility: PRODUCTION
  /appelements/d/{did}/{wvm}/{wvmid}/e/{eid}/references:
    post:
      deprecated: false
      operationId: createReference
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Creates a reference to an app element.
      tags:
      - AppElement
      x-BTVisibility: PRODUCTION
  /appelements/d/{did}/{wvm}/{wvmid}/e/{eid}/references/{rid}:
    delete:
      deprecated: false
      operationId: deleteReference
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Delete an app element reference.
      tags:
      - AppElement
      x-BTVisibility: PRODUCTION
    get:
      deprecated: false
      description: For single operations only. Use `resolveReferences` for bulk operations.
      operationId: resolveReference
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Resolves a single reference to an app element.
      tags:
      - AppElement
      x-BTVisibility: PRODUCTION
    post:
      deprecated: false
      operationId: updateReference
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Update an app element reference.
      tags:
      - AppElement
      x-BTVisibility: PRODUCTION
  /appelements/d/{did}/{wvm}/{wvmid}/e/{eid}/resolvereferences:
    get:
      deprecated: false
      description: For bulk operations only. Use `resolveReference` for a single operation.
      operationId: resolveReferences
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Resolves bulk app element references.
      tags:
      - AppElement
      x-BTVisibility: PRODUCTION
  /appelements/d/{did}/{wvm}/{wvmid}/resolvereferences:
    get:
      deprecated: false
      description: Resolve all references for all workspace elements. For bulk operations  only.
        Use `resolveReferences` for a single element.
      operationId: resolveAllElementReferences
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Resolves bulk app element references.
      tags:
      - AppElement
      x-BTVisibility: PRODUCTION
  /applications/clients/{cid}/settings/companies/{cpid}:
    delete:
      deprecated: false
      description: This API is only usable with an OAuth token and only by the current
        user or admin.
      operationId: deleteCompanyAppSettings
      summary: Delete a company's application preference settings.
      tags:
      - APIApplication
      x-BTVisibility: PRODUCTION
    get:
      deprecated: false
      description: This API is only usable with an OAuth token and only by the current
        user or admin.
      operationId: getCompanyAppSettings
      summary: Get company-level preference settings for an application.
      tags:
      - APIApplication
      x-BTVisibility: PRODUCTION
    post:
      deprecated: false
      description: This API is only usable with an OAuth token and only by the current
        user or admin.
      operationId: updateAppCompanySettings
      summary: Update company preference settings for an application.
      tags:
      - APIApplication
      x-BTVisibility: PRODUCTION
  /applications/clients/{cid}/settings/users/{uid}:
    delete:
      deprecated: false
      description: This API is only usable with an OAuth token and only by the current
        user or admin.
      operationId: deleteAppSettings
      summary: Delete a user's application preference settings.
      tags:
      - APIApplication
      x-BTVisibility: PRODUCTION
    get:
      deprecated: false
      description: This API is only usable with an OAuth token and only by the current
        user or admin.
      operationId: getUserAppSettings
      summary: Get user-level preference settings for an application.
      tags:
      - APIApplication
      x-BTVisibility: PRODUCTION
    post:
      deprecated: false
      description: This API is only usable with an OAuth token and only by the current
        user or admin.
      operationId: updateAppSettings
      summary: Update a user's application preference settings.
      tags:
      - APIApplication
      x-BTVisibility: PRODUCTION
  /applications/extensions/user/{uid}/client/{cid}:
    get:
      deprecated: false
      operationId: getApplicableExtensionsForClient
      security:
      - OAuth2:
        - OAuth2ReadPII
        BasicAuth:
        - OAuth2ReadPII
      summary: Get a list of the client extensions the specified user has granted/accepted
        terms for.
      tags:
      - APIApplication
      x-BTVisibility: PRODUCTION
  /assemblies/d/{did}/e/{eid}/namedViews:
    get:
      deprecated: false
      operationId: getNamedViews
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get the view data for all named views for the specified element.
      tags:
      - Assembly
      x-BTVisibility: PRODUCTION
  /assemblies/d/{did}/w/{wid}:
    post:
      deprecated: false
      operationId: createAssembly
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Create a new assembly tab in the document.
      tags:
      - Assembly
      x-BTVisibility: PRODUCTION
  /assemblies/d/{did}/w/{wid}/e/{eid}/bomelement:
    post:
      deprecated: false
      operationId: getOrCreateBillOfMaterialsElement
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: "Gets the Bill Of Materials (BOM) for the specified assembly, or creates\
        \ a BOM if none exist."
      tags:
      - Assembly
      x-BTVisibility: PRODUCTION
  /assemblies/d/{did}/w/{wid}/e/{eid}/features/featureid/{fid}:
    delete:
      deprecated: false
      operationId: deleteFeature
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Delete a feature from an assembly.
      tags:
      - Assembly
      x-BTVisibility: PRODUCTION
    post:
      deprecated: false
      operationId: updateFeature
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Update an existing feature for an Assembly.
      tags:
      - Assembly
      x-BTVisibility: PRODUCTION
  /assemblies/d/{did}/w/{wid}/e/{eid}/instance/nodeid/{nid}:
    delete:
      deprecated: false
      operationId: deleteInstance
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Delete an instance of an assembly.
      tags:
      - Assembly
      x-BTVisibility: PRODUCTION
  /assemblies/d/{did}/w/{wid}/e/{eid}/instances:
    post:
      deprecated: false
      description: Part Studio instances may include multiple parts.
      operationId: createInstance
      security:
      - OAuth2:
        - OAuth2Read
        - OAuth2Write
        BasicAuth:
        - OAuth2Read
        - OAuth2Write
      summary: "Insert an instance of a part, sketch, assembly, or Part Studio into\
        \ an assembly."
      tags:
      - Assembly
      x-BTVisibility: PRODUCTION
  /assemblies/d/{did}/w/{wid}/e/{eid}/modify:
    post:
      deprecated: false
      description: "This endpoint can include multiple modifications to an assembly\
        \ with one change. For example, it can delete/suppress/unsuppress/transform\
        \ multiple instances. It creates one history entry in the document history\
        \ list."
      operationId: modify
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Modify an assembly.
      tags:
      - Assembly
      x-BTVisibility: PRODUCTION
  /assemblies/d/{did}/w/{wid}/e/{eid}/occurrencetransforms:
    post:
      deprecated: false
      operationId: transformOccurrences
      security:
      - OAuth2:
        - OAuth2Read
        - OAuth2Write
        BasicAuth:
        - OAuth2Read
        - OAuth2Write
      summary: Transform a list of assembly occurrences.
      tags:
      - Assembly
      x-BTVisibility: PRODUCTION
  /assemblies/d/{did}/w/{wid}/e/{eid}/transformedinstances:
    post:
      deprecated: false
      operationId: insertTransformedInstances
      security:
      - OAuth2:
        - OAuth2Read
        - OAuth2Write
        BasicAuth:
        - OAuth2Read
        - OAuth2Write
      summary: Create new instances with transformation.
      tags:
      - Assembly
      x-BTVisibility: PRODUCTION
  /assemblies/d/{did}/{wvm}/{wvmid}/e/{eid}:
    get:
      deprecated: false
      description: All coordinates and translation matrix components are in meters
        (m).
      operationId: getAssemblyDefinition
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get definition information for the specified assembly.
      tags:
      - Assembly
      x-BTVisibility: PRODUCTION
  /assemblies/d/{did}/{wvm}/{wvmid}/e/{eid}/bom:
    get:
      deprecated: false
      description: Returns the BOM in JSON in the Onshape BOM Standard format.
      operationId: getBillOfMaterials
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get the Bill Of Materials (BOM) content for the specified assembly.
      tags:
      - Assembly
      x-BTVisibility: PRODUCTION
  /assemblies/d/{did}/{wvm}/{wvmid}/e/{eid}/boundingboxes:
    get:
      deprecated: false
      operationId: getAssemblyBoundingBoxes
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get bounding box information for the specified assembly.
      tags:
      - Assembly
      x-BTVisibility: PRODUCTION
  /assemblies/d/{did}/{wvm}/{wvmid}/e/{eid}/displaystates:
    get:
      deprecated: false
      operationId: getDisplayStates
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get a list of display states for the specified assembly.
      tags:
      - Assembly
      x-BTVisibility: PRODUCTION
  /assemblies/d/{did}/{wvm}/{wvmid}/e/{eid}/explodedviews:
    get:
      deprecated: false
      operationId: getExplodedViews
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get a list of exploded views for the specified assembly.
      tags:
      - Assembly
      x-BTVisibility: PRODUCTION
  /assemblies/d/{did}/{wvm}/{wvmid}/e/{eid}/features:
    get:
      deprecated: false
      operationId: getFeatures
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get the definitions of the specified features in an assembly.
      tags:
      - Assembly
      x-BTVisibility: PRODUCTION
    post:
      deprecated: false
      operationId: addFeature
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Add a feature to the assembly feature list.
      tags:
      - Assembly
      x-BTVisibility: PRODUCTION
  /assemblies/d/{did}/{wvm}/{wvmid}/e/{eid}/featurespecs:
    get:
      deprecated: false
      operationId: getFeatureSpecs
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get the feature spec definitions for an assembly.
      tags:
      - Assembly
      x-BTVisibility: PRODUCTION
  /assemblies/d/{did}/{wvm}/{wvmid}/e/{eid}/massproperties:
    get:
      deprecated: false
      description: "The assembly must contain parts that have density. The returned\
        \ schema includes the same information as in the Onshape [Mass Properties\
        \ Tool](https://cad.onshape.com/help/Content/massprops-asmb.htm). \nWhen three\
        \ values are returned: \n * The first is the calculated value. \n * The second\
        \ is the minimum possible value, considering tolerance. \n * The third is\
        \ the maximum possible value, considering tolerance."
      operationId: getAssemblyMassProperties
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get the mass properties for the assembly.
      tags:
      - Assembly
      x-BTVisibility: PRODUCTION
  /assemblies/d/{did}/{wvm}/{wvmid}/e/{eid}/namedpositions:
    get:
      deprecated: false
      operationId: getNamedPositions
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get a list of all named positions for the assembly.
      tags:
      - Assembly
      x-BTVisibility: PRODUCTION
  /assemblies/d/{did}/{wvm}/{wvmid}/e/{eid}/shadedviews:
    get:
      deprecated: false
      operationId: getAssemblyShadedViews
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get an array of shaded view images for the document.
      tags:
      - Assembly
      x-BTVisibility: PRODUCTION
  /assemblies/d/{did}/{wv}/{wvid}/e/{eid}/translations:
    post:
      deprecated: false
      description: "* Use `formatName` in the JSON request body to specify the export\
        \ file type. Use [Translations/getAllTranslatorFormats](https://cad.onshape.com/glassworks/explorer/#/Translation/getAllTranslatorFormats)\
        \ to get a list of valid export file formats. Confirm that `couldBeAssembly=true.`\n\
        * Set `storeInDocument` to `true` to export to a data file. Set to `false`\
        \ to export to a blob element in the same document. \n* See [API Guide: Model\
        \ Translation](https://onshape-public.github.io/docs/api-adv/translation/)\
        \ for more details."
      operationId: translateFormat
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Export the assembly to another format.
      tags:
      - Assembly
      x-BTVisibility: PRODUCTION
  /billing/plans/client/{cid}:
    get:
      deprecated: false
      description: This API should be used within the context of an OAuth-enabled
        application.
      operationId: getClientPlans
      summary: Get all billing plans and their information for an application by client
        ID.
      tags:
      - Billing
      x-BTVisibility: PRODUCTION
  /blobelements/d/{did}/w/{wid}:
    post:
      deprecated: false
      description: "Request body parameters are multipart fields, so you must use\
        \ `\"Content-Type\":\"multipart/form-data\"` in the request header."
      operationId: uploadFileCreateElement
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Upload a file and create a blob element from it.
      tags:
      - BlobElement
      x-BTVisibility: PRODUCTION
  /blobelements/d/{did}/w/{wid}/e/{eid}:
    get:
      deprecated: false
      description: "See [API Guide: Model Translation](https://onshape-public.github.io/docs/api-adv/translation/)\
        \ for more details."
      operationId: downloadFileWorkspace
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Download a file from a blob element for the specified workspace/version/microversion.
      tags:
      - BlobElement
      x-BTVisibility: PRODUCTION
    post:
      deprecated: false
      description: "Request body parameters are multipart fields, so you must use\
        \ `\"Content-Type\":\"multipart/form-data\"` in the request header."
      operationId: uploadFileUpdateElement
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Update a blob element by uploading a file.
      tags:
      - BlobElement
      x-BTVisibility: PRODUCTION
  /blobelements/d/{did}/w/{wid}/e/{eid}/units:
    post:
      deprecated: false
      operationId: updateUnits
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Change the measurement units for the blob element.
      tags:
      - BlobElement
      x-BTVisibility: PRODUCTION
  /blobelements/d/{did}/{wv}/{wvid}/e/{eid}/translations:
    post:
      deprecated: false
      description: "* Use `formatName` in the JSON request body to specify the export\
        \ file type. Use [Translations/getAllTranslatorFormats](https://cad.onshape.com/glassworks/explorer/#/Translation/getAllTranslatorFormats)\
        \ to get a list of valid export file formats. \n* Set `storeInDocument` to\
        \ `true` to export to a data file. Set to `false` to export to a blob element\
        \ in the same document. \n* See [API Guide: Model Translation](https://onshape-public.github.io/docs/api-adv/translation/)\
        \ for more details."
      operationId: createBlobTranslation
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Export a blob element to another format.
      tags:
      - BlobElement
      x-BTVisibility: PRODUCTION
  /comments:
    get:
      deprecated: false
      operationId: getComments
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get a list of comments in a document.
      tags:
      - Comment
      x-BTVisibility: PRODUCTION
    post:
      deprecated: false
      operationId: createComment
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Update a document with a new comment.
      tags:
      - Comment
      x-BTVisibility: PRODUCTION
  /comments/{cid}:
    delete:
      deprecated: false
      operationId: deleteComment
      security:
      - OAuth2:
        - OAuth2Delete
        BasicAuth:
        - OAuth2Delete
      summary: Delete a comment from a document.
      tags:
      - Comment
      x-BTVisibility: PRODUCTION
    get:
      deprecated: false
      operationId: getComment
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get details for a comment.
      tags:
      - Comment
      x-BTVisibility: PRODUCTION
    post:
      deprecated: false
      operationId: updateComment
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Update the content of an existing comment.
      tags:
      - Comment
      x-BTVisibility: PRODUCTION
  /comments/{cid}/attachment:
    delete:
      deprecated: false
      operationId: deleteAttachments
      security:
      - OAuth2:
        - OAuth2Delete
        BasicAuth:
        - OAuth2Delete
      summary: Delete all attachments from a comment.
      tags:
      - Comment
      x-BTVisibility: PRODUCTION
    post:
      deprecated: false
      operationId: addAttachment
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Add an attachment to a comment.
      tags:
      - Comment
      x-BTVisibility: PRODUCTION
  /comments/{cid}/attachment/{fdid}.{ext}:
    get:
      deprecated: false
      description: Returns only a single attachment.
      operationId: getAttachment
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get the attachment with the specified file extension that is associated
        with the specified comment.
      tags:
      - Comment
      x-BTVisibility: PRODUCTION
  /comments/{cid}/reopen:
    post:
      deprecated: false
      operationId: reopen
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Reopen a resolved comment.
      tags:
      - Comment
      x-BTVisibility: PRODUCTION
  /comments/{cid}/resolve:
    post:
      deprecated: false
      operationId: resolve
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Resolve a comment.
      tags:
      - Comment
      x-BTVisibility: PRODUCTION
  /companies:
    get:
      deprecated: false
      description: "If no user is specified, will return all companies associated\
        \ with the current user."
      operationId: findCompany
      summary: Get all companies to which the specified user belongs.
      tags:
      - Company
      x-BTVisibility: PRODUCTION
  /companies/{cid}:
    get:
      deprecated: false
      operationId: getCompany
      summary: Get company information by company ID.
      tags:
      - Company
      x-BTVisibility: PRODUCTION
  /companies/{cid}/documentsbyname:
    get:
      deprecated: false
      description: This API can only be called by company admins. Use the `name` field
        for the exact document name string.
      operationId: getDocumentsByName
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get document by exact document name.
      tags:
      - Company
      x-BTVisibility: PRODUCTION
  /companies/{cid}/users:
    post:
      deprecated: false
      description: Returns the company user info.
      operationId: addUserToCompany
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Add a user to a company.
      tags:
      - Company
      x-BTVisibility: PRODUCTION
  /companies/{cid}/users/{uid}:
    delete:
      deprecated: false
      operationId: removeUserFromCompany
      security:
      - OAuth2:
        - OAuth2Delete
        BasicAuth:
        - OAuth2Delete
      summary: "Remove a user from a company, company teams, and all the direct shares."
      tags:
      - Company
      x-BTVisibility: PRODUCTION
    post:
      deprecated: false
      description: Returns updated company user info. Global permissions can only
        be updated by the company admin.
      operationId: updateCompanyUser
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Update the company's information for a user.
      tags:
      - Company
      x-BTVisibility: PRODUCTION
  /documents:
    get:
      deprecated: false
      operationId: getDocuments
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get a list of documents that meet the criteria you specify.
      tags:
      - Document
      x-BTVisibility: PRODUCTION
    post:
      deprecated: false
      description: The `name` field is required in the `BTDocumentParams` schema when
        creating a new document.
      operationId: createDocument
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Create and upload a document.
      tags:
      - Document
      x-BTVisibility: PRODUCTION
  /documents/d/{did}/externaldata/{fid}:
    get:
      deprecated: false
      description: "* See [API Guide: Model Translation](https://onshape-public.github.io/docs/api-adv/translation/)\
        \ for more details.\n* If downloading an exported file, poll the `requestState`\
        \ in the translation response and wait for a result of `DONE` before attempting\
        \ to download the file. \n* Use the `resultExternalDataIds` from the translation\
        \ response as the foreign id (`{fid}`) in this API."
      operationId: downloadExternalData
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Download external data file(s) associated with the document.
      tags:
      - Document
      x-BTVisibility: PRODUCTION
  /documents/d/{did}/versions:
    get:
      deprecated: false
      operationId: getDocumentVersions
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Retrieve versions by document ID.
      tags:
      - Document
      x-BTVisibility: PRODUCTION
    post:
      deprecated: false
      operationId: createVersion
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Create version by document ID.
      tags:
      - Document
      x-BTVisibility: PRODUCTION
  /documents/d/{did}/versions/{vid}:
    get:
      deprecated: false
      operationId: getVersion
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Retrieve version by document ID and version ID.
      tags:
      - Document
      x-BTVisibility: PRODUCTION
  /documents/d/{did}/w/{wid}/e/{eid}/latestdocumentreferences:
    post:
      deprecated: false
      operationId: updateExternalReferencesToLatestDocuments
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: "Update external references to latest by document ID, workspace ID,\
        \ and tab ID."
      tags:
      - Document
      x-BTVisibility: PRODUCTION
  /documents/d/{did}/w/{wid}/moveelement:
    post:
      deprecated: false
      operationId: moveElementsToDocument
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Move tab by document ID and workspace ID.
      tags:
      - Document
      x-BTVisibility: PRODUCTION
  /documents/d/{did}/w/{wid}/revertunchangedtorevisions:
    post:
      deprecated: false
      operationId: revertUnchangedToRevisions
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      tags:
      - Document
      x-BTVisibility: PRODUCTION
  /documents/d/{did}/w/{wid}/syncAppElements:
    post:
      deprecated: false
      operationId: syncAppElements
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      tags:
      - Document
      x-BTVisibility: PRODUCTION
  /documents/d/{did}/workspaces:
    get:
      deprecated: false
      operationId: getDocumentWorkspaces
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Retrieve workspaces by document ID.
      tags:
      - Document
      x-BTVisibility: PRODUCTION
    post:
      deprecated: false
      operationId: createWorkspace
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Create workspace by document ID.
      tags:
      - Document
      x-BTVisibility: PRODUCTION
  /documents/d/{did}/workspaces/{wid}:
    delete:
      deprecated: false
      operationId: deleteWorkspace
      security:
      - OAuth2:
        - OAuth2Delete
        BasicAuth:
        - OAuth2Delete
      summary: Delete workspace by document ID and workspace ID.
      tags:
      - Document
      x-BTVisibility: PRODUCTION
  /documents/d/{did}/{wm}/{wmid}/documenthistory:
    get:
      deprecated: false
      operationId: getDocumentHistory
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Retrieve document history by document ID and workspace or microversion
        ID.
      tags:
      - Document
      x-BTVisibility: PRODUCTION
  /documents/d/{did}/{wvm}/{wvmid}/elements:
    get:
      deprecated: false
      operationId: getElementsInDocument
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Retrieve tabs by document ID and workspace or version or microversion
        ID.
      tags:
      - Document
      x-BTVisibility: PRODUCTION
  /documents/d/{did}/{wvm}/{wvmid}/unitinfo:
    get:
      deprecated: false
      operationId: getUnitInfo
      summary: Get the selected units and precision by document ID and workspace or
        version or microversion ID.
      tags:
      - Document
      x-BTVisibility: PRODUCTION
  /documents/d/{did}/{wv}/{wvid}/currentmicroversion:
    get:
      deprecated: false
      operationId: getCurrentMicroversion
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Retrieve current microversion by document ID and workspace or version
        ID.
      tags:
      - Document
      x-BTVisibility: PRODUCTION
  /documents/d/{did}/{wv}/{wvid}/e/{eid}/export:
    post:
      deprecated: false
      operationId: export2Json
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: "Export document by document ID, workspace or version ID, and tab ID."
      tags:
      - Document
      x-BTVisibility: PRODUCTION
  /documents/d/{did}/{wv}/{wvid}/insertables:
    get:
      deprecated: false
      operationId: getInsertables
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Retrieve insertables by document ID and workspace or version ID.
      tags:
      - Document
      x-BTVisibility: PRODUCTION
  /documents/search:
    post:
      deprecated: false
      description: This returns list of documents based on search parameters.
      operationId: search
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Search document.
      tags:
      - Document
      x-BTVisibility: PRODUCTION
  /documents/{did}:
    delete:
      deprecated: false
      operationId: deleteDocument
      security:
      - OAuth2:
        - OAuth2Delete
        BasicAuth:
        - OAuth2Delete
      summary: Delete document by document ID.
      tags:
      - Document
      x-BTVisibility: PRODUCTION
    get:
      deprecated: false
      operationId: getDocument
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Retrieve document by document ID.
      tags:
      - Document
      x-BTVisibility: PRODUCTION
    post:
      deprecated: false
      operationId: updateDocumentAttributes
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Update document attributes by document ID.
      tags:
      - Document
      x-BTVisibility: PRODUCTION
  /documents/{did}/acl:
    get:
      deprecated: false
      operationId: getDocumentAcl
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Retrieve access control list by document ID.
      tags:
      - Document
      x-BTVisibility: PRODUCTION
  /documents/{did}/permissionset:
    get:
      deprecated: false
      operationId: getDocumentPermissionSet
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Retrieve Document permissions by document ID.
      tags:
      - Document
      x-BTVisibility: PRODUCTION
  /documents/{did}/share:
    post:
      deprecated: false
      operationId: shareDocument
      security:
      - OAuth2:
        - OAuth2Read
        - OAuth2Share
        BasicAuth:
        - OAuth2Read
        - OAuth2Share
      summary: Share document by document ID.
      tags:
      - Document
      x-BTVisibility: PRODUCTION
  /documents/{did}/share/{eid}:
    delete:
      deprecated: false
      description: "Specify the ID of the entity to unshare with in the `eid` field,\
        \ and specify the type of entity being identified in the `entryType` field.\
        \ For example, to unshare a document with a company, you would use `1` as\
        \ the `entryType` value and the `companyId` as the `entityId`."
      operationId: unShareDocument
      security:
      - OAuth2:
        - OAuth2Read
        - OAuth2Share
        BasicAuth:
        - OAuth2Read
        - OAuth2Share
      summary: Remove document View permissions from a user or other entity.
      tags:
      - Document
      x-BTVisibility: PRODUCTION
  /documents/{did}/shareWithSupport:
    delete:
      deprecated: false
      operationId: unshareFromSupport
      summary: Unshare document with support.
      tags:
      - Document
      x-BTVisibility: PRODUCTION
    post:
      deprecated: false
      operationId: shareWithSupport
      summary: Share document by document ID with Onshape support.
      tags:
      - Document
      x-BTVisibility: PRODUCTION
  /documents/{did}/w/{wid}/mergePreview:
    get:
      deprecated: false
      operationId: mergePreview
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: "Merge preview of changes that will occur based on document ID, workspace\
        \ ID and source workspace/version ID"
      tags:
      - Document
      x-BTVisibility: PRODUCTION
  /documents/{did}/w/{wid}/restore/{vm}/{vmid}:
    post:
      deprecated: false
      operationId: restoreFromHistory
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: "Restore version or microversion to workspace by document ID, workspace\
        \ ID, and version or microversion ID."
      tags:
      - Document
      x-BTVisibility: PRODUCTION
  /documents/{did}/workspaces/{wid}/copy:
    post:
      deprecated: false
      operationId: copyWorkspace
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Copy workspace by document ID and workspace ID.
      tags:
      - Document
      x-BTVisibility: PRODUCTION
  /documents/{did}/workspaces/{wid}/merge:
    post:
      deprecated: false
      operationId: mergeIntoWorkspace
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Merge into workspace by document ID and workspace ID.
      tags:
      - Document
      x-BTVisibility: PRODUCTION
  /drawings/d/{did}/w/{wid}/create:
    post:
      deprecated: false
      description: "This endpoint takes a JSON Schema as input. See the schema docs\
        \ below for details, and see [API Guide: Drawings](https://onshape-public.github.io/docs/api-adv/drawings/)\
        \ for more information."
      operationId: createDrawingAppElement
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Create a new drawing in a document.
      tags:
      - Drawing
      x-BTVisibility: PRODUCTION
  /drawings/d/{did}/w/{wid}/e/{eid}/modify:
    post:
      deprecated: false
      description: "See [API Guide: Drawings](https://onshape-public.github.io/docs/api-adv/drawings/)\
        \ for more information."
      operationId: modifyDrawing
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Modify a drawing via JSON payload.
      tags:
      - Drawing
      x-BTVisibility: PRODUCTION
  /drawings/d/{did}/w/{wid}/e/{eid}/translationformats:
    get:
      deprecated: false
      description: "See [API Guide: Translations](https://onshape-public.github.io/docs/api-adv/translation/#export-a-drawing-as-a-json)\
        \ for more information."
      operationId: getDrawingTranslatorFormats
      summary: Get a list of all valid formats the drawing can be translated (exported)
        to.
      tags:
      - Drawing
      x-BTVisibility: PRODUCTION
  /drawings/d/{did}/{wvm}/{wvmid}/e/{eid}/views:
    get:
      deprecated: false
      operationId: getDrawingViews_1
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get details of all drawing views.
      tags:
      - Drawing
      x-BTVisibility: PRODUCTION
  /drawings/d/{did}/{wvm}/{wvmid}/e/{eid}/views/{viewid}/jsongeometry:
    get:
      deprecated: false
      operationId: getDrawingViewJsonGeometry_1
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get view geometry of a drawing view in JSON format.
      tags:
      - Drawing
      x-BTVisibility: PRODUCTION
  /drawings/d/{did}/{wv}/{wvid}/e/{eid}/translations:
    post:
      deprecated: false
      description: "Export a drawing to a different format within a document. Use\
        \ `getDrawingTranslatorFormats` for a list of supported translation (i.e.,\
        \ import/export) formats. See [API Guide: Translations](https://onshape-public.github.io/docs/api-adv/translation/#export-a-drawing-as-a-json)\
        \ for more information."
      operationId: createDrawingTranslation
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Translate (export) a drawing to a different format.
      tags:
      - Drawing
      x-BTVisibility: PRODUCTION
  /drawings/modify/status/{mrid}:
    get:
      deprecated: false
      operationId: getModificationStatus
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get the status of a drawing modification operation.
      tags:
      - Drawing
      x-BTVisibility: PRODUCTION
  /elements/copyelement/{did}/workspace/{wid}:
    post:
      deprecated: false
      description: "Specify the target document and workspace in the URL. Specify\
        \ the source document, workspace, and element in the request body. \nIf `anchorElementId`\
        \ is specified, the copied element will be inserted after the anchor element.\
        \ If not specified, the copied element will be inserted at the end of the\
        \ tab list. \n"
      operationId: copyElementFromSourceDocument
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Copy an element from a source document.
      tags:
      - Element
      x-BTVisibility: PRODUCTION
  /elements/d/{did}/e/{eid}/configurationencodings:
    post:
      deprecated: false
      description: "Returns a configuration string in the following form: \n`configuration=parameterId%3DparameterValue`\
        \ \nThe configuration string can be used in other Onshape API calls to specify\
        \ which configuration option to use. See the [Configuration API Guide](https://onshape-public.github.io/docs/api-adv/configs/)\
        \ for additional details. \n"
      operationId: encodeConfigurationMap
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Encode a configuration option for use in other API calls.
      tags:
      - Element
      x-BTVisibility: PRODUCTION
  /elements/d/{did}/w/{wid}/e/{eid}:
    delete:
      deprecated: false
      description: Attempting to delete the last element in a document will result
        in an error.
      operationId: deleteElement
      security:
      - OAuth2:
        - OAuth2Delete
        BasicAuth:
        - OAuth2Delete
      summary: Delete an element from a document.
      tags:
      - Element
      x-BTVisibility: PRODUCTION
  /elements/d/{did}/w/{wid}/e/{eid}/updatereferences:
    post:
      deprecated: false
      operationId: updateReferences
      security:
      - OAuth2:
        - OAuth2Read
        - OAuth2Write
        BasicAuth:
        - OAuth2Read
        - OAuth2Write
      summary: Update or replace references in an element.
      tags:
      - Element
      x-BTVisibility: PRODUCTION
  /elements/d/{did}/{wvm}/{wvmid}/e/{eid}/configuration:
    get:
      deprecated: false
      description: "Use Configurations to create variations of elements. You can configure\
        \ feature and parameter values, part properties, custom part properties, face\
        \ and part appearances, and sketch text. Each Part Studio can have only one\
        \ Configuration, but it can contain multiple Configuration inputs. \nSee the\
        \ [Configuration API Guide](https://onshape-public.github.io/docs/api-adv/configs/)\
        \ for additional details. "
      operationId: getConfiguration
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get the configuration definition for a Part Studio or Assembly.
      tags:
      - Element
      x-BTVisibility: PRODUCTION
    post:
      deprecated: false
      description: "See the [Configuration API Guide](https://onshape-public.github.io/docs/api-adv/configs/)\
        \ for additional details"
      operationId: updateConfiguration
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Update the configuration definition for a Part Studio or Assembly.
      tags:
      - Element
      x-BTVisibility: PRODUCTION
  /elements/d/{did}/{wvm}/{wvmid}/e/{eid}/configurationencodings/{cid}:
    get:
      deprecated: false
      description: "Decode a configuration string into its original JSON form to obtain\
        \ configuration parameter ID and value. See the [Configuration API Guide](https://onshape-public.github.io/docs/api-adv/configs/)\
        \ for additional details.  "
      operationId: decodeConfiguration
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Decode a configuration string.
      tags:
      - Element
      x-BTVisibility: PRODUCTION
  /elements/translatorFormats/{did}/{wv}/{wvid}/{eid}:
    get:
      deprecated: false
      description: "See the [Translation API Guide](https://onshape-public.github.io/docs/api-adv/translation/)\
        \ for additional details. "
      operationId: getElementTranslatorFormatsByVersionOrWorkspace
      summary: Gets the list of formats an element can be translated to or from.
      tags:
      - Element
      x-BTVisibility: PRODUCTION
  /exportrules/options/{cu}/{cuid}:
    get:
      deprecated: false
      description: Does NOT get the rules themselves; it gets the information used
        to create them.
      operationId: getValidRuleOptions
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: ' Get a list of valid export rule options for the user or company.'
      tags:
      - ExportRule
      x-BTVisibility: PRODUCTION
  /featurestudios/d/{did}/w/{wid}:
    post:
      deprecated: false
      description: Specify the name for the new tab in the request body.
      operationId: createFeatureStudio
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Create a new Feature Studio tab in a document.
      tags:
      - FeatureStudio
      x-BTVisibility: PRODUCTION
  /featurestudios/d/{did}/{wvm}/{wvmid}/e/{eid}:
    get:
      deprecated: false
      operationId: getFeatureStudioContents
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get the text for a Feature Studio element.
      tags:
      - FeatureStudio
      x-BTVisibility: PRODUCTION
    post:
      deprecated: false
      operationId: updateFeatureStudioContents
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Update the text for a Feature Studio element.
      tags:
      - FeatureStudio
      x-BTVisibility: PRODUCTION
  /featurestudios/d/{did}/{wvm}/{wvmid}/e/{eid}/featurespecs:
    get:
      deprecated: false
      operationId: getFeatureStudioSpecs
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get the feature specs for a Feature Studio element.
      tags:
      - FeatureStudio
      x-BTVisibility: PRODUCTION
  /folders/{fid}/acl:
    get:
      deprecated: false
      description: "Returns the ACL of permission objects. Each object contains: \n\
        * The type of entity  \n    * 0 (User)  \n    * 1 (Company) \n    * 2 (Team)\
        \ \n    * 3 (Document) \n    * 4 (Application) \n * The ID of the entity for\
        \ the specified type. \n* The permissions for that entity. \n    *  OWNER\
        \ (100): All permissions, including those not listed, such as permission to\
        \ transfer ownership. \n    * DELETE (90) \n    * RESHARE (80) \n    * WRITE\
        \ (70) \n    * READ (60) \n    * LINK (50) \n    * COPY (30): Can copy workspace\
        \ \n    * EXPORT (20): Can export geometry \n    * COMMENT (10) \n    * ANONYMOUS_ACCESS\
        \ (5): Special, restricted read access"
      operationId: getFolderAcl
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get the Access Control List (ACL) for a folder to view permissions.
      tags:
      - Folder
      x-BTVisibility: PRODUCTION
  /folders/{fid}/share:
    post:
      deprecated: false
      description: "* Specify the type of entity to share with using `entries.entryType`:\
        \ \n    * 0 (User)  \n    * 1 (Company) \n    * 2 (Team) \n    * 3 (Document)\
        \ \n    * 4 (Application) \n* Provide one of the identifiers in the `entries`\
        \ object in the request body.  \n    * You can share with non-Onshape users\
        \ with the `email` field when `entryType=0`.  \n * Provide the string for\
        \ the permission set. Do not include the integer in parentheses: \n    * OWNER\
        \ (100): Object owner. Implies all permissions including those not listed\
        \ such as permission to transfer ownership. \n    * DELETE (90) \n    * RESHARE\
        \ (80) \n    * WRITE (70) \n    * READ (60) \n    * LINK (50) \n    * COPY\
        \ (30): Can copy workspace \n    * EXPORT (20): Can export geometry \n   \
        \ * COMMENT (10) \n    * ANONYMOUS_ACCESS (5): Special, restricted read access"
      operationId: share
      security:
      - OAuth2:
        - OAuth2Read
        - OAuth2Share
        BasicAuth:
        - OAuth2Read
        - OAuth2Share
      summary: Share folder with an entity.
      tags:
      - Folder
      x-BTVisibility: PRODUCTION
  /folders/{fid}/share/{eid}:
    delete:
      deprecated: false
      description: "* Provide the folder ID for the folder to unshare.  \n * Provide\
        \ the `entityType` for the type of entity to remove. \n    * 0 (User)  \n\
        \    * 1 (Company) \n    * 2 (Team) \n    * 3 (Document) \n    * 4 (Application)\
        \ \n* Provide the entity ID in the `eid` param."
      operationId: unShare
      security:
      - OAuth2:
        - OAuth2Read
        - OAuth2Share
        BasicAuth:
        - OAuth2Read
        - OAuth2Share
      summary: Remove permissions from the folder for the specified Access Control
        List (ACL) entry.
      tags:
      - Folder
      x-BTVisibility: PRODUCTION
  /insertables/d/{did}/latest:
    get:
      deprecated: false
      description: "* Returns only the latest revision of released insertables. \n\
        * Use the document ID (`did`) parameter to specify the source document, not\
        \ the insertion target. \n* For example, you can insert a custom Feature library\
        \ into another custom Feature library, insert Parts into an Assembly or a\
        \ Drawing, etc."
      operationId: getLatestInDocument
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get a list of things in this document that can be inserted elsewhere.
      tags:
      - Insertable
      x-BTVisibility: PRODUCTION
  /metadata/d/{did}/{wvm}/{wvmid}/e:
    get:
      deprecated: false
      description: "See [API Guide: Metadata](https://onshape-public.github.io/docs/api-adv/metadata/)\
        \ for details. \n* You can specify the optional `depth` query parameter to\
        \ get multiple levels in an assembly. Default `depth` is `1`. \n* `linkDocumentId`\
        \ can be specified where applicable. Combined with `inferMetadataOwner` (default\
        \ value is `false`), this is used to infer metadata owner. \n* `includeComputedProperties`\
        \ can be used to include or omit computed properties. Default value is `true`.\
        \ \n* `includeComputedAssemblyProperties` can be used to query computed assembly\
        \ properties which are generally expensive. Default value is `false`. \n*\
        \ You can also choose to include a `thumbnail`. Default value is `false`."
      operationId: getWMVEsMetadata
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get the metadata for all elements in a document.
      tags:
      - Metadata
      x-BTVisibility: PRODUCTION
  /metadata/d/{did}/{wvm}/{wvmid}/e/{eid}:
    get:
      deprecated: false
      description: "See [API Guide: Metadata](https://onshape-public.github.io/docs/api-adv/metadata/)\
        \ for details. \n* `linkDocumentId` can be specified where applicable and\
        \ this combined with the query param `inferMetadataOwner` (default value is\
        \ `false`) will be used to infer metadata owner. \n* `configuration` optional\
        \ query parameter defaults to default configuration. \n* You can specify an\
        \ optional `depth` query parameter to get multiple levels in an assembly.\
        \ Default `depth` is `1`. \n* `includeComputedProperties` can be used to include\
        \ or omit computed properties. Default value is `true`. \n* `includeComputedAssemblyProperties`\
        \ can be used to query computed assembly properties which are generally expensive.\
        \ Default value is `false`. \n* You can also choose to include a `thumbnail`.\
        \ Default value is `false`."
      operationId: getWMVEMetadata
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get the metadata for an element.
      tags:
      - Metadata
      x-BTVisibility: PRODUCTION
    post:
      deprecated: false
      description: "See [API Guide: Metadata](https://onshape-public.github.io/docs/api-adv/metadata/)\
        \ for details. \n* Microversion (`m`) in `wvm` path parameter option is not\
        \ supported. \n* Specify the property metadata to update in the Request body."
      operationId: updateWVEMetadata
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Update the metadata for an element.
      tags:
      - Metadata
      x-BTVisibility: PRODUCTION
  /metadata/d/{did}/{wvm}/{wvmid}/e/{eid}/assembly-debug:
    get:
      deprecated: false
      description: "See [API Guide: Metadata](https://onshape-public.github.io/docs/api-adv/metadata/)\
        \ for details. \n* `linkDocumentId` can be specified where applicable and\
        \ this combined with the query param `inferMetadataOwner` (default value is\
        \ `false`) will be used to infer metadata owner. \n* `configuration` optional\
        \ query parameter defaults to default configuration. \n* `includeComputedProperties`\
        \ can be used to include or omit computed properties. Default value is `true`.\
        \ \n* `includeComputedAssemblyProperties` can be used to query computed assembly\
        \ properties which are generally expensive. Default value is `false`. \n*\
        \ You can also choose to include a `thumbnail`. Default value is `false`."
      operationId: getFullAssemblyMetadata
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: "Get the metadata for an assembly, including supporting metadata."
      tags:
      - Metadata
      x-BTVisibility: PRODUCTION
  /metadata/d/{did}/{wvm}/{wvmid}/e/{eid}/p:
    get:
      deprecated: false
      description: "See [API Guide: Metadata](https://onshape-public.github.io/docs/api-adv/metadata/)\
        \ for details. \n* The `configuration` optional query parameter uses the default\
        \ configuration unless otherwise specified. \n* You can specify an optional\
        \ `depth` query parameter to get multiple levels in an assembly. Default `depth`\
        \ is `1`. \n* `linkDocumentId` can be specified where applicable. Combined\
        \ with `inferMetadataOwner` (default value is `false`), this is used to infer\
        \ metadata owner. \n* `includeComputedProperties` can be used to include or\
        \ omit computed properties. Default value is `true`. \n* `includeComputedAssemblyProperties`\
        \ can be used to query computed assembly properties which are generally expensive.\
        \ Default value is `false`. \n* You can also choose to include a `thumbnail`.\
        \ Default value is `false`."
      operationId: getWMVEPsMetadata
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get the metadata for all parts in a document.
      tags:
      - Metadata
      x-BTVisibility: PRODUCTION
  /metadata/d/{did}/{wvm}/{wvmid}/e/{eid}/{iden}/{pid}:
    get:
      deprecated: false
      description: "See [API Guide: Metadata](https://onshape-public.github.io/docs/api-adv/metadata/)\
        \ for details. \n* Specify the part in the `iden` or `pid` path parameter.\
        \ \n* The `configuration` optional query parameter uses the default configuration\
        \ unless otherwise specified. \n* `linkDocumentId` can be specified where\
        \ applicable. Combined with `inferMetadataOwner` (default value is `false`),\
        \ this is used to infer metadata owner. \n* `includeComputedProperties` can\
        \ be used to include or omit computed properties. Default value is `true`.\
        \ \n* `includeComputedAssemblyProperties` can be used to query computed assembly\
        \ properties which are generally expensive. Default value is `false`. \n*\
        \ You can also choose to include a `thumbnail`. Default value is `false`."
      operationId: getWMVEPMetadata
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get the metadata for a part.
      tags:
      - Metadata
      x-BTVisibility: PRODUCTION
    post:
      deprecated: false
      description: "See [API Guide: Metadata](https://onshape-public.github.io/docs/api-adv/metadata/)\
        \ for details. \n* Specify the part in the `iden` or `pid` path parameter.\
        \ \n* The `configuration` optional query parameter uses the default configuration\
        \ unless otherwise specified. \n* `linkDocumentId` can be specified where\
        \ applicable. Combined with `inferMetadataOwner` (default value is `false`),\
        \ this is used to infer metadata owner. \n* Specify the property metadata\
        \ to update in the Request body."
      operationId: updateWVEPMetadata
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Update the metadata for a part.
      tags:
      - Metadata
      x-BTVisibility: PRODUCTION
  /metadata/d/{did}/{wv}/{wvid}:
    get:
      deprecated: false
      description: "See [API Guide: Metadata](https://onshape-public.github.io/docs/api-adv/metadata/)\
        \ for details. \n* `linkDocumentId` can be specified where applicable. Combined\
        \ with `inferMetadataOwner` (default value is `false`), this is used to infer\
        \ metadata owner. \n* You can specify an optional `depth` query parameter\
        \ to get multiple levels in an assembly. Default `depth` is `1`. \n* `includeComputedProperties`\
        \ can be used to include or omit computed properties. Default value is `true`.\
        \ \n* `includeComputedAssemblyProperties` can be used to query computed assembly\
        \ properties which are generally expensive. Default value is `false`. \n*\
        \ You can also choose to include a `thumbnail`. Default value is `false`."
      operationId: getWVMetadata
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get the metadata for a workspace or version.
      tags:
      - Metadata
      x-BTVisibility: PRODUCTION
    post:
      deprecated: false
      description: "See [API Guide: Metadata](https://onshape-public.github.io/docs/api-adv/metadata/)\
        \ for details."
      operationId: updateWVMetadata
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Update the metadata for a workspace or version.
      tags:
      - Metadata
      x-BTVisibility: PRODUCTION
  /metadata/standardcontent/d/{did}:
    post:
      deprecated: false
      description: "See [API Guide: Metadata](https://onshape-public.github.io/docs/api-adv/metadata/)\
        \ for details. \n* Specify the document ID to update in the `did` path param.\
        \ \n* Specify the document in which you have inserted the standard content\
        \ part in the `linkDocumentId` query param. \n* Specify the property metadata\
        \ to update in the Request body."
      operationId: updateVEOPStandardContentPartMetadata
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Update the metadata for a standard content part.
      tags:
      - Metadata
      x-BTVisibility: PRODUCTION
  /metadata/standardcontent/d/{did}/v/{vid}/e/{eid}/p/{pid}:
    get:
      deprecated: false
      description: "See [API Guide: Metadata](https://onshape-public.github.io/docs/api-adv/metadata/)\
        \ for details. \n* Specify the part in the `pid` path parameter. \n* The `configuration`\
        \ and `linkDocumentId` query parameters are required. \n* `includeComputedProperties`\
        \ can be used to include or omit computed properties. Default value is `true`.\
        \ \n* `includeComputedAssemblyProperties` can be used to query computed assembly\
        \ properties which are generally expensive. Default value is `false`. \n*\
        \ You can also choose to include a `thumbnail`. Default value is `false`."
      operationId: getVEOPStandardContentMetadata
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get the metadata for a standard content part.
      tags:
      - Metadata
      x-BTVisibility: PRODUCTION
  /metadatacategory/categoryproperties:
    get:
      deprecated: false
      description: "An object's category specifies its type: Part, Assembly, Drawing,\
        \ etc. Available properties depend on the object's category."
      operationId: getCategoryProperties
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get properties associated with the specified metadata categories.
      tags:
      - MetadataCategory
      x-BTVisibility: PRODUCTION
  /numberingscheme/nextnumbers:
    post:
      deprecated: false
      operationId: nextNumbers
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: "Send the items to generate numbers for, and return the next valid\
        \ available part numbers."
      tags:
      - NumberingScheme
      x-BTVisibility: PRODUCTION
  /openapi:
    get:
      deprecated: false
      description: The Onshape API OpenAPI specification is returned in the JSON format.
      operationId: getOpenApi
      parameters:
      - description: Force reload the OpenApi definition. Only works when asking for
          the latest version.
        explode: true
        in: query
        name: forceReload
        required: false
        schema:
          type: boolean
        style: form
      - description: "Specify a version of Onshape from which the OpenAPI is generated.\
          \ If '*' is specified in any of the version fields, that indicates any version\
          \ if acceptable."
        explode: true
        in: query
        name: version
        required: false
        schema:
          type: string
        style: form
      - description: Version aliases based on the currently released version.
        explode: true
        in: query
        name: versionAlias
        required: false
        schema:
          $ref: '#/components/schemas/VersionAlias'
        style: form
      - description: Do not filter the specification at all.
        explode: true
        in: query
        name: noFilter
        required: false
        schema:
          default: false
          type: boolean
        style: form
      - description: Return only operations with tags included in includedTags.
        explode: true
        in: query
        name: includedTags
        required: false
        schema:
          items:
            type: string
          type: array
        style: form
      - description: "If an operation contains an excluded tag, it is not returned\
          \ from this endpoint."
        explode: true
        in: query
        name: excludedTags
        required: false
        schema:
          items:
            type: string
          type: array
        style: form
      - description: Include deprecated endpoints.
        explode: true
        in: query
        name: includeDeprecated
        required: false
        schema:
          default: false
          type: boolean
        style: form
      - description: Only include deprecated endpoints.
        explode: true
        in: query
        name: onlyDeprecated
        required: false
        schema:
          default: false
          type: boolean
        style: form
      - description: Only return endpoints that have the specified documentation status.
          Default is to return all the endpoints the user should have access to.
        explode: true
        in: query
        name: documentationStatuses
        required: false
        schema:
          items:
            $ref: '#/components/schemas/Status'
          type: array
        style: form
      - description: The REST user role for which this spec is requested.
        explode: true
        in: query
        name: restUserRole
        required: false
        schema:
          $ref: '#/components/schemas/BTRestUserRole'
        style: form
      - description: Only return operations with specified ids.
        explode: true
        in: query
        name: operationIds
        required: false
        schema:
          items:
            type: string
          type: array
        style: form
      - description: Do not return operations with specified ids.
        explode: true
        in: query
        name: excludedOperationIds
        required: false
        schema:
          items:
            type: string
          type: array
        style: form
      summary: Get the OpenAPI specification for the Onshape REST API.
      tags:
      - OpenApi
      x-BTVisibility: PRODUCTION
  /openapi/tags:
    get:
      deprecated: false
      description: "Tags are used to group operations. For example, `Document` groups\
        \ operations on documents."
      operationId: getTags
      summary: Get the list of tags in the Onshape OpenAPI specification.
      tags:
      - OpenApi
      x-BTVisibility: PRODUCTION
  /partnumber/nextnumbers:
    post:
      deprecated: false
      operationId: updateNextNumbers
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: "Send the items to generate numbers for, and return the next valid\
        \ available part numbers."
      tags:
      - PartNumber
      x-BTVisibility: PRODUCTION
  /parts/d/{did}/{wvm}/{wvmid}:
    get:
      deprecated: false
      operationId: getPartsWMV
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: "Get all parts in a workspace, version, or microversion."
      tags:
      - Part
      x-BTVisibility: PRODUCTION
  /parts/d/{did}/{wvm}/{wvmid}/e/{eid}:
    get:
      deprecated: false
      operationId: getPartsWMVE
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get all parts in an element.
      tags:
      - Part
      x-BTVisibility: PRODUCTION
  /parts/d/{did}/{wvm}/{wvmid}/e/{eid}/partid/{partid}/bodydetails:
    get:
      deprecated: false
      description: All coordinates are in meters (m).
      operationId: getBodyDetails
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get a part's body details.
      tags:
      - Part
      x-BTVisibility: PRODUCTION
  /parts/d/{did}/{wvm}/{wvmid}/e/{eid}/partid/{partid}/boundingboxes:
    get:
      deprecated: false
      operationId: getBoundingBoxes
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get a part's bounding box details.
      tags:
      - Part
      x-BTVisibility: PRODUCTION
  /parts/d/{did}/{wvm}/{wvmid}/e/{eid}/partid/{partid}/gltf:
    get:
      deprecated: false
      description: "Returns a 307 redirect from which to download the exported file.\
        \ See [API Guide: Model Translation](https://onshape-public.github.io/docs/api-adv/translation/)\
        \ for more details."
      operationId: exportPartGltf
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Export a part as a glTF file.
      tags:
      - Part
      x-BTVisibility: PRODUCTION
  /parts/d/{did}/{wvm}/{wvmid}/e/{eid}/partid/{partid}/massproperties:
    get:
      deprecated: false
      description: "Parts must have density. The returned schema includes the same\
        \ information as in the Onshape [Mass Properties Tool](https://cad.onshape.com/help/Content/massprops-ps.htm).\
        \ \nWhen three values are returned: \n * The first is the calculated value.\
        \ \n * The second is the minimum possible value, considering tolerance. \n\
        \ * The third is the maximum possible value, considering tolerance."
      operationId: getMassProperties
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get a part's mass properties.
      tags:
      - Part
      x-BTVisibility: PRODUCTION
  /parts/d/{did}/{wvm}/{wvmid}/e/{eid}/partid/{partid}/parasolid:
    get:
      deprecated: false
      description: "Returns a 307 redirect from which to download the exported file.\
        \ See [API Guide: Model Translation](https://onshape-public.github.io/docs/api-adv/translation/)\
        \ for more details."
      operationId: exportPS
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Export a part as a Parasolid file.
      tags:
      - Part
      x-BTVisibility: PRODUCTION
  /parts/d/{did}/{wvm}/{wvmid}/e/{eid}/partid/{partid}/shadedviews:
    get:
      deprecated: false
      operationId: getPartShadedViews
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get a part's shaded views.
      tags:
      - Part
      x-BTVisibility: PRODUCTION
  /parts/d/{did}/{wvm}/{wvmid}/e/{eid}/partid/{partid}/sheetmetal/bendtable:
    get:
      deprecated: false
      operationId: getBendTable
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get a part's sheet metal bend table.
      tags:
      - Part
      x-BTVisibility: PRODUCTION
  /parts/d/{did}/{wvm}/{wvmid}/e/{eid}/partid/{partid}/stl:
    get:
      deprecated: false
      description: "Returns a 307 redirect from which to download the exported file.\
        \ See [API Guide: Model Translation](https://onshape-public.github.io/docs/api-adv/translation/)\
        \ for more details."
      operationId: exportStl
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Export a part as an STL file.
      tags:
      - Part
      x-BTVisibility: PRODUCTION
  /parts/d/{did}/{wvm}/{wvmid}/e/{eid}/partid/{partid}/tessellatededges:
    get:
      deprecated: false
      description: Returns the coordinates (in meters) of each edge's endpoints.
      operationId: getEdges
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get a list of a part's tessellation edges.
      tags:
      - Part
      x-BTVisibility: PRODUCTION
  /parts/d/{did}/{wvm}/{wvmid}/e/{eid}/partid/{partid}/tessellatedfaces:
    get:
      deprecated: false
      description: Coordinates are in meters (m).
      operationId: getFaces_1
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get a list of a part's tessellation faces.
      tags:
      - Part
      x-BTVisibility: PRODUCTION
  /partstudios/d/{did}/e/{eid}/namedViews:
    get:
      deprecated: false
      description: Returns a map from view name to view data for the given element
      operationId: getPartStudioNamedViews
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get a list of all named views that exist in the Part Studio.
      tags:
      - PartStudio
      x-BTVisibility: PRODUCTION
  /partstudios/d/{did}/w/{wid}:
    post:
      deprecated: false
      operationId: createPartStudio
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Create a new Part Studio in a document.
      tags:
      - PartStudio
      x-BTVisibility: PRODUCTION
  /partstudios/d/{did}/w/{wid}/e/{eid}/features/featureid/{fid}:
    delete:
      deprecated: false
      description: "See the [Features API Guide](https://onshape-public.github.io/docs/api-adv/featureaccess/)\
        \ for additional information."
      operationId: deletePartStudioFeature
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Delete a Part Studio feature.
      tags:
      - PartStudio
      x-BTVisibility: PRODUCTION
    post:
      deprecated: false
      description: "Replaces an existing feature in the location of the existing feature.\
        \ See the [Features API Guide](https://onshape-public.github.io/docs/api-adv/featureaccess/)\
        \ for additional information."
      operationId: updatePartStudioFeature
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Update the definition of a Part Studio feature.
      tags:
      - PartStudio
      x-BTVisibility: PRODUCTION
  /partstudios/d/{did}/w/{wid}/e/{eid}/features/rollback:
    post:
      deprecated: false
      description: Set to -1 to move the rollback bar to the end of the list.
      operationId: updateRollback
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Move the Feature List rollback bar in the Part Studio.
      tags:
      - PartStudio
      x-BTVisibility: PRODUCTION
  /partstudios/d/{did}/w/{wid}/e/{eid}/features/updates:
    post:
      deprecated: false
      description: "This API accepts a list of features (that must already exist in\
        \ the Part Studio) to update. This call does not fully redefine the features;\
        \ it updates only the parameters supplied in the top-level feature structure,\
        \ and optionally can update feature suppression attributes. \nSee the [Features\
        \ API Guide](https://onshape-public.github.io/docs/api-adv/featureaccess/)\
        \ for additional information."
      operationId: updateFeatures
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Update multiple features in a Part Studio
      tags:
      - PartStudio
      x-BTVisibility: PRODUCTION
  /partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/bodydetails:
    get:
      deprecated: false
      operationId: getPartStudioBodyDetails
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get the body details for a Part Studio.
      tags:
      - PartStudio
      x-BTVisibility: PRODUCTION
  /partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/boundingboxes:
    get:
      deprecated: false
      description: "This endpoint does not result in a tight bounding box. The values\
        \ returned are meant for graphics and visualization, and are approximate.\
        \ \nTo calculate a tight bounding box, see the [FeatureScript API Guide](https://onshape-public.github.io/docs/api-adv/fs/#calculate-a-tight-bounding-box). "
      operationId: getPartStudioBoundingBoxes
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get the bounding boxes for a Part Studio.
      tags:
      - PartStudio
      x-BTVisibility: PRODUCTION
  /partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/compare:
    get:
      deprecated: false
      operationId: comparePartStudios
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get the differences between two Part Studios in a single document.
      tags:
      - PartStudio
      x-BTVisibility: PRODUCTION
  /partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/features:
    get:
      deprecated: false
      description: "See the [Features API Guide](https://onshape-public.github.io/docs/api-adv/featureaccess/)\
        \ for additional information."
      operationId: getPartStudioFeatures
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get a list of features instantiated in the Part Studio.
      tags:
      - PartStudio
      x-BTVisibility: PRODUCTION
    post:
      deprecated: false
      description: "The feature is added immediately before the rollback bar. Any\
        \ geometry IDs specified in the feature must be valid at that point in the\
        \ feature tree. \n \nSee the [Features API Guide](https://onshape-public.github.io/docs/api-adv/featureaccess/)\
        \ for additional information."
      operationId: addPartStudioFeature
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Add a feature to the Part Studio's Feature List.
      tags:
      - PartStudio
      x-BTVisibility: PRODUCTION
  /partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/featurescript:
    post:
      deprecated: false
      operationId: evalFeatureScript
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Evaluate the FeatureScript snippet for a Part Studio.
      tags:
      - PartStudio
      x-BTVisibility: PRODUCTION
  /partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/featurescriptrepresentation:
    get:
      deprecated: false
      operationId: getFeatureScriptRepresentation
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get the FeatureScript representation of a Part Studio.
      tags:
      - PartStudio
      x-BTVisibility: PRODUCTION
  /partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/featurespecs:
    get:
      deprecated: false
      description: Returns a list of feature specs available within the Part Studio.
        A feature spec provides a data description of the feature's interface to a
        feature.
      operationId: getPartStudioFeatureSpecs
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get the specs for a Part Studio feature.
      tags:
      - PartStudio
      x-BTVisibility: PRODUCTION
  /partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/fstable:
    get:
      deprecated: false
      operationId: getFeatureScriptTable
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Compute and return a FeatureScript table for a Part Studio.
      tags:
      - PartStudio
      x-BTVisibility: PRODUCTION
  /partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/gltf:
    get:
      deprecated: false
      description: "Returns the glTF representation. See [API Guide: Model Translation](https://onshape-public.github.io/docs/api-adv/translation/)"
      operationId: exportPartStudioGltf
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Export the Part Studio as a glTF file.
      tags:
      - PartStudio
      x-BTVisibility: PRODUCTION
  /partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/idtranslations:
    post:
      deprecated: false
      description: "* Deterministic IDs are only valid for one microversion. \n* This\
        \ maps deterministic IDs between microversions in an attempt to find the corresponding\
        \ entities in each version."
      operationId: translateIds
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Find corresponding deterministic IDs from a source document microversion
        at the target version.
      tags:
      - PartStudio
      x-BTVisibility: PRODUCTION
  /partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/massproperties:
    get:
      deprecated: false
      description: "Parts must have density. The returned schema includes the same\
        \ information as in the Onshape [Mass Properties Tool](https://cad.onshape.com/help/Content/massprops-ps.htm).\
        \ \nWhen three values are returned: \n * The first is the calculated value.\
        \ \n * The second is the minimum possible value, considering tolerance. \n\
        \ * The third is the maximum possible value, considering tolerance."
      operationId: getPartStudioMassProperties
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get the mass properties for a Part Studio.
      tags:
      - PartStudio
      x-BTVisibility: PRODUCTION
  /partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/parasolid:
    get:
      deprecated: false
      description: "Returns a 307 redirect from which to download the exported file.\
        \ See [API Guide: Model Translation](https://onshape-public.github.io/docs/api-adv/translation/)\
        \ for more details."
      operationId: exportParasolid
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Export the Part Studio as a Parasolid file.
      tags:
      - PartStudio
      x-BTVisibility: PRODUCTION
  /partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/shadedviews:
    get:
      deprecated: false
      operationId: getPartStudioShadedViews
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get a list of shaded views for a Part Studio.
      tags:
      - PartStudio
      x-BTVisibility: PRODUCTION
  /partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/sketches:
    get:
      deprecated: false
      operationId: getSketchInfo
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get information for all sketches in Part Studio.
      tags:
      - Sketch
      x-BTVisibility: PRODUCTION
  /partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/sketches/{sid}/boundingboxes:
    get:
      deprecated: false
      operationId: getSketchBoundingBoxes
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get all bounding boxes for a sketch.
      tags:
      - Sketch
      x-BTVisibility: PRODUCTION
  /partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/sketches/{sid}/tessellatedentities:
    get:
      deprecated: false
      description: "The accuracy of the tessellation to exact geometry is controlled\
        \ by the `angleTolerance` and `chordTolerance` parameters. The tessellation\
        \ points are computed closely enough so that neither the angle tolerance nor\
        \ the chord tolerance are exceeded. For most parts, the angular tolerance\
        \ is the most restrictive of the two default tolerances."
      operationId: getTessellatedEntities
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get the tessellations of a sketch in a Part Studio.
      tags:
      - Sketch
      x-BTVisibility: PRODUCTION
  /partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/stl:
    get:
      deprecated: false
      description: "Returns a 307 redirect from which to download the exported file.\
        \ See [API Guide: Model Translation](https://onshape-public.github.io/docs/api-adv/translation/)"
      operationId: exportPartStudioStl
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Export the Part Studio as an STL file.
      tags:
      - PartStudio
      x-BTVisibility: PRODUCTION
  /partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/tessellatededges:
    get:
      deprecated: false
      description: "Returns the edges as tessellated data and includes display data.\
        \ \nCoordinates are in meters (m)."
      operationId: getPartStudioEdges
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get a list of all edges in a Part Studio.
      tags:
      - PartStudio
      x-BTVisibility: PRODUCTION
  /partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/tessellatedfaces:
    get:
      deprecated: false
      description: Coordinates are in meters (m).
      operationId: getPartStudioFaces
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get a list of all faces in a Part Studio.
      tags:
      - PartStudio
      x-BTVisibility: PRODUCTION
  /partstudios/d/{did}/{wv}/{wvid}/e/{eid}/translations:
    post:
      deprecated: false
      description: "* Use `formatName` in the JSON request body to specify the export\
        \ file type. Use [Translations/getAllTranslatorFormats](https://cad.onshape.com/glassworks/explorer/#/Translation/getAllTranslatorFormats)\
        \ to get a list of valid export file formats. `\n* Set `storeInDocument` to\
        \ `true` to export to a data file. Set to `false` to export to a blob element\
        \ in the same document. \n* See [API Guide: Model Translation](https://onshape-public.github.io/docs/api-adv/translation/)\
        \ for more details."
      operationId: createPartStudioTranslation
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Export a Part Studio to another format.
      tags:
      - PartStudio
      x-BTVisibility: PRODUCTION
  /publications:
    post:
      deprecated: false
      operationId: createPublication
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Create a new publication.
      tags:
      - Publication
      x-BTVisibility: PRODUCTION
  /publications/{pid}:
    delete:
      deprecated: false
      operationId: deletePublication
      security:
      - OAuth2:
        - OAuth2Delete
        BasicAuth:
        - OAuth2Delete
      summary: Delete a publication.
      tags:
      - Publication
      x-BTVisibility: PRODUCTION
    post:
      deprecated: false
      operationId: updatePublicationAttributes
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: "Update publication's attributes name, description, and notes."
      tags:
      - Publication
      x-BTVisibility: PRODUCTION
  /publications/{pid}/item:
    post:
      deprecated: false
      operationId: addItemToPublication
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Add an item in a publication.
      tags:
      - Publication
      x-BTVisibility: PRODUCTION
  /publications/{pid}/item/{iid}:
    delete:
      deprecated: false
      operationId: deletePublicationItem
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Remove an item from a publication.
      tags:
      - Publication
      x-BTVisibility: PRODUCTION
  /publications/{pid}/items:
    get:
      deprecated: false
      operationId: getPublicationItems
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get all items in a publication.
      tags:
      - Publication
      x-BTVisibility: PRODUCTION
    post:
      deprecated: false
      operationId: addItemsToPublication
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Add publication items in bulk.
      tags:
      - Publication
      x-BTVisibility: PRODUCTION
  /releasepackages/companyreleaseworkflow:
    get:
      deprecated: false
      operationId: getCompanyReleaseWorkflow
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get information about the release/obsoletion workflow for a company-owned
        document.
      tags:
      - ReleasePackage
      x-BTVisibility: PRODUCTION
  /releasepackages/obsoletion/{wfid}:
    post:
      deprecated: false
      operationId: createObsoletionPackage
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Create an obsoletion package to make an existing revision obsolete.
      tags:
      - ReleasePackage
      x-BTVisibility: PRODUCTION
  /releasepackages/release/{wfid}:
    post:
      deprecated: false
      description: "All revisionable items must be from the same document. Once a\
        \ release package is successfully created, use `updateReleasePackage` to update\
        \ all desired item/package properties, and transition it to the desired state."
      operationId: createReleasePackage
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Create a new release package for one or more items.
      tags:
      - ReleasePackage
      x-BTVisibility: PRODUCTION
  /releasepackages/{rpid}:
    get:
      deprecated: false
      operationId: getReleasePackage
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get details about the specified release package.
      tags:
      - ReleasePackage
      x-BTVisibility: PRODUCTION
    post:
      deprecated: false
      description: Use the `wfaction` query param to also perform a workflow transition.
      operationId: updateReleasePackage
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Update the release/obsoletion package/item properties.
      tags:
      - ReleasePackage
      x-BTVisibility: PRODUCTION
  /revisions/c/{cid}/partnumber/{pnum}:
    get:
      deprecated: false
      operationId: getRevisionByPartNumber
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get a list of revisions by part number.
      tags:
      - Revision
      x-BTVisibility: PRODUCTION
  /revisions/companies/{cid}:
    get:
      deprecated: false
      description: "* Returns a slice of all revisions per API call. \n* To get the\
        \ next set of results, use the `next` URL from the response body. \n* This\
        \ API can only be called by company admins."
      operationId: enumerateRevisions
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Enumerate all of a company's revisions.
      tags:
      - Revision
      x-BTVisibility: PRODUCTION
  /revisions/companies/{cid}/d/{did}/{wv}/{wvid}/e/{eid}:
    get:
      deprecated: false
      operationId: getRevisionHistoryInCompanyByElementId
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get a list of all revisions for an element in a company-owned document.
      tags:
      - Revision
      x-BTVisibility: PRODUCTION
  /revisions/companies/{cid}/d/{did}/{wv}/{wvid}/e/{eid}/p/{pid}:
    get:
      deprecated: false
      operationId: getRevisionHistoryInCompanyByPartId
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get a list of all revisions for a part in a company-owned document
        by part ID.
      tags:
      - Revision
      x-BTVisibility: PRODUCTION
  /revisions/companies/{cid}/partnumber/{pnum}:
    get:
      deprecated: false
      description: "You can also request `elementType` in addition to `partNumber`\
        \ since companies may or may not allow drawings to share part numbers with\
        \ their parts/assemblies. To perform search without `elementType`, use `elementType`\
        \ = -1 | UNKNOWN. Available element types are: -1: Unknown, 0: Part Studio,\
        \ 1: Assembly, 2: Drawing, 4: Blob, 5: Application, 8: Variable Studio 10:\
        \ Unknown"
      operationId: getRevisionHistoryInCompanyByPartNumber
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get a list of all revisions for a part or element in a company-owned
        document by part number.
      tags:
      - Revision
      x-BTVisibility: PRODUCTION
  /revisions/companies/{cid}/partnumber/{pnum}/elementType/{et}:
    delete:
      deprecated: false
      description: Only company admins can call this API. All documents that contain
        or use the part number must be deleted first. This operation cannot be undone.
      operationId: deleteRevisionHistory
      security:
      - OAuth2:
        - OAuth2Delete
        BasicAuth:
        - OAuth2Delete
      summary: Delete all revisions for a part number.
      tags:
      - Revision
      x-BTVisibility: PRODUCTION
  /revisions/d/{did}:
    get:
      deprecated: false
      description: Retrieve a list of all revisions that exist in a document and are
        owned by the document's owning company.
      operationId: getAllInDocument
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get all revisions for the specified document.
      tags:
      - Revision
      x-BTVisibility: PRODUCTION
  /revisions/d/{did}/v/{vid}:
    get:
      deprecated: false
      description: Retrieve a list of all revisions that exist in a document version
        and are owned by the document's owning company.
      operationId: getAllInDocumentVersion
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get all revisions for a version.
      tags:
      - Revision
      x-BTVisibility: PRODUCTION
  /revisions/{cd}/{cdid}/p/{pnum}/latest:
    get:
      deprecated: false
      description: Returns 204 if no revisions are found.
      operationId: getLatestInDocumentOrCompany
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get the latest revision for a part number in a document or company.
      tags:
      - Revision
      x-BTVisibility: PRODUCTION
  /tabletemplates:
    post:
      deprecated: false
      operationId: createTableTemplate
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Create a new properties table template.
      tags:
      - PropertiesTableTemplate
      x-BTVisibility: PRODUCTION
  /tabletemplates/companies/{cid}:
    get:
      deprecated: false
      operationId: getByCompanyId
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get all properties table templates available for a company.
      tags:
      - PropertiesTableTemplate
      x-BTVisibility: PRODUCTION
  /tabletemplates/d/{did}:
    get:
      deprecated: false
      operationId: getByDocumentId
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get all table templates that are available to use on the provided document.
      tags:
      - PropertiesTableTemplate
      x-BTVisibility: PRODUCTION
  /tabletemplates/{tid}:
    delete:
      deprecated: false
      operationId: deleteTableTemplate
      security:
      - OAuth2:
        - OAuth2Delete
        BasicAuth:
        - OAuth2Delete
      summary: Delete a properties table template.
      tags:
      - PropertiesTableTemplate
      x-BTVisibility: PRODUCTION
    get:
      deprecated: false
      operationId: getTableTemplate
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get a properties table template by template ID.
      tags:
      - PropertiesTableTemplate
      x-BTVisibility: PRODUCTION
  /tasks:
    get:
      deprecated: false
      description: Returns a list of tasks assigneed to the userId specified in the
        request. Only company admins can view tasks that were not created by them
        and are not assigned to them.
      operationId: getActionItems
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Lists tasks assigned to the specified user
      tags:
      - Task
      x-BTVisibility: PRODUCTION
    post:
      deprecated: false
      operationId: createTask
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Create a new task in a draft state.
      tags:
      - Task
      x-BTVisibility: PRODUCTION
  /tasks/{tid}:
    get:
      deprecated: false
      operationId: getTask
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get a task by id.
      tags:
      - Task
      x-BTVisibility: PRODUCTION
    post:
      deprecated: false
      operationId: updateTask
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Update the task and its properties.
      tags:
      - Task
      x-BTVisibility: PRODUCTION
  /tasks/{tid}/{transition}:
    post:
      deprecated: false
      operationId: transitionTask
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Execute a workflow transition.
      tags:
      - Task
      x-BTVisibility: PRODUCTION
  /teams:
    get:
      deprecated: false
      operationId: find
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get a list of all teams the current user belongs to.
      tags:
      - Team
      x-BTVisibility: PRODUCTION
  /teams/{tid}:
    get:
      deprecated: false
      operationId: getTeam
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get team information by team ID.
      tags:
      - Team
      x-BTVisibility: PRODUCTION
  /teams/{tid}/members:
    get:
      deprecated: false
      description: Returns a maximum of 20 per page.
      operationId: getMembers
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get a list of a team's members.
      tags:
      - Team
      x-BTVisibility: PRODUCTION
  /thumbnails/d/{did}:
    get:
      deprecated: false
      description: |-
        * By default, returns thumbnail info for the element with the most-recently generated image. If you pinned an element for the document thumbnail, that element will always be used for the document-level thumbnail, if it exists in the workspace.
        * The default workspace may vary by user; the image served depends on the signed-in user.
        * See also: [Tech tip on how to change a document thumbnail in onshape](https://www.onshape.com/en/resource-center/tech-tips/tech-tip-how-to-change-a-document-thumbnail-in-onshape)
      operationId: getThumbnailForDocument
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get the thumbnail info for a document in the default workspace.
      tags:
      - Thumbnail
      x-BTVisibility: PRODUCTION
  /thumbnails/d/{did}/v/{vid}:
    get:
      deprecated: false
      description: |-
        * By default, returns thumbnail info for the element with the most-recently generated image. If you pinned an element for the document thumbnail, that element will always be used for the document-level thumbnail, if it exists in the workspace.
        * See also: [Tech tip on how to change a document thumbnail in onshape](https://www.onshape.com/en/resource-center/tech-tips/tech-tip-how-to-change-a-document-thumbnail-in-onshape)
      operationId: getThumbnailForDocumentAndVersion
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get the thumbnail info for a version of a document.
      tags:
      - Thumbnail
      x-BTVisibility: PRODUCTION
  /thumbnails/d/{did}/w/{wid}:
    get:
      deprecated: false
      description: |-
        * By default, returns thumbnail info for the element with the most-recently generated image. If you pinned an element for the document thumbnail, that element will always be used for the document-level thumbnail, if it exists in the workspace.
        * See also: [Tech tip on how to change a document thumbnail in onshape](https://www.onshape.com/en/resource-center/tech-tips/tech-tip-how-to-change-a-document-thumbnail-in-onshape)
      operationId: getDocumentThumbnail
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get the thumbnail info for a workspace.
      tags:
      - Thumbnail
      x-BTVisibility: PRODUCTION
  /thumbnails/d/{did}/w/{wid}/e/{eid}/ac/{cid}/s/{sz}:
    get:
      deprecated: false
      description: "Returns the thumbnail image for an element at a specified version,\
        \ with the given configuration."
      operationId: getElementThumbnailWithApiConfiguration
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get the thumbnail image with the given configuration for an element.
      tags:
      - Thumbnail
      x-BTVisibility: PRODUCTION
  /thumbnails/d/{did}/w/{wid}/s/{sz}:
    get:
      deprecated: false
      description: |-
        * By default, returns thumbnail image for the element with the most-recently generated image. If you pinned an element for the document thumbnail, that element will always be used for the document-level thumbnail, if it exists in the workspace.
        * See also: [Tech tip on how to change a document thumbnail in onshape](https://www.onshape.com/en/resource-center/tech-tips/tech-tip-how-to-change-a-document-thumbnail-in-onshape)
      operationId: getDocumentThumbnailWithSize
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get the thumbnail image with the given size for a document.
      tags:
      - Thumbnail
      x-BTVisibility: PRODUCTION
  /thumbnails/d/{did}/{wv}/{wvid}/e/{eid}:
    delete:
      deprecated: false
      description: "Deletes an application element's thumbnail and images for the\
        \ given document, workspace or version, and element combination."
      operationId: deleteApplicationThumbnails
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Delete an element's thumbnail.
      tags:
      - Thumbnail
      x-BTVisibility: PRODUCTION
    get:
      deprecated: false
      description: "Returns thumbnail info for the given document, workspace or version,\
        \ and element."
      operationId: getElementThumbnail
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get the thumbnail info structure for an element.
      tags:
      - Thumbnail
      x-BTVisibility: PRODUCTION
    post:
      deprecated: false
      description: "* Allows 3rd-party applications to set thumbnails for their elements.\
        \ \n* Application elements can have both primary and secondary thumbnails.\
        \ A primary thumbnail represents the top-level of the element. A secondary\
        \ thumbnail can represent sub-components of the element (e.g., a drawing sheet).\n\
        * To update one or more thumbnails, you must set the overwrite query param\
        \ to `true` and supply the entire set of thumbnails. All previous thumbnails\
        \ will be deleted prior to updating the element with the latest images."
      operationId: setApplicationElementThumbnail
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Set the thumbnail image for an application element.
      tags:
      - Thumbnail
      x-BTVisibility: PRODUCTION
  /thumbnails/d/{did}/{wv}/{wvid}/e/{eid}/s/{sz}:
    get:
      deprecated: false
      operationId: getElementThumbnailWithSize
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get the thumbnail image with the given size for an element.
      tags:
      - Thumbnail
      x-BTVisibility: PRODUCTION
  /thumbnails/document/{did}:
    get:
      deprecated: false
      description: "This API exists for historical reasons. It uses `/document/` in\
        \ the path, rather than the standard `/d/` to specify the document."
      operationId: getThumbnailForDocumentOld
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: This endpoint will be deprecated soon. Use `getThumbnailForDocument`
        instead.
      tags:
      - Thumbnail
      x-BTVisibility: PRODUCTION
  /thumbnails/document/{did}/version/{vid}:
    get:
      deprecated: false
      description: "This API exists for historical reasons. It uses `/document/` in\
        \ the path, rather than the standard `/d/` to specify the document."
      operationId: getThumbnailForDocumentAndVersionOld
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: This endpoint will be deprecated soon. Use `getThumbnailForDocumentAndVersion`
        instead.
      tags:
      - Thumbnail
      x-BTVisibility: PRODUCTION
  /translations/d/{did}:
    get:
      deprecated: false
      operationId: getDocumentTranslations
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get information on an in-progress or completed translation by document
        ID.
      tags:
      - Translation
      x-BTVisibility: PRODUCTION
  /translations/d/{did}/w/{wid}:
    post:
      deprecated: false
      description: "The API call may complete before the translation is finished.\
        \ If `requestState = ACTIVE`, the translation can be polled until the state\
        \ is either `DONE` or `FAILED`. Alternatively, a webhook callback can be registered\
        \ for notification of translation completion (requires `Write` scope if `storeInDocument`\
        \ is `true`). See [API Guide: Model Translation](https://onshape-public.github.io/docs/api-adv/translation/)\
        \ for more details."
      operationId: createTranslation
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: "Upload a foreign file into Onshape and translate the data into parts,\
        \ Part Studios, assemblies, and subassemblies."
      tags:
      - Translation
      x-BTVisibility: PRODUCTION
  /translations/translationformats:
    get:
      deprecated: false
      description: "Note that we don't necessarily support both import and export\
        \ for any given format. See [API Guide: Model Translation](https://onshape-public.github.io/docs/api-adv/translation/)\
        \ for more details."
      operationId: getAllTranslatorFormats
      summary: Get a list of formats this translation can use.
      tags:
      - Translation
      x-BTVisibility: PRODUCTION
  /translations/{tid}:
    delete:
      deprecated: false
      operationId: deleteTranslation
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Delete a translation request.
      tags:
      - Translation
      x-BTVisibility: PRODUCTION
    get:
      deprecated: false
      description: "When the translation is complete, `requestState` changes from\
        \ `ACTIVE` to `DONE` or `FAILED`. See [API Guide: Model Translation](https://onshape-public.github.io/docs/api-adv/translation/)\
        \ for more details."
      operationId: getTranslation
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get information on an in-progress or completed translation by translation
        ID.
      tags:
      - Translation
      x-BTVisibility: PRODUCTION
  /users/session:
    post:
      deprecated: false
      description: Returned information depends on caller's `OAuth2ReadPll` scope.
      operationId: session
      summary: "Authenticate a user's Onshape credentials, and create a session."
      tags:
      - User
      x-BTVisibility: PRODUCTION
  /users/sessioninfo:
    get:
      deprecated: false
      description: Returned information depends on caller's `OAuth2ReadPll` scope.
      operationId: sessionInfo
      summary: Get the session information for an authenticated (signed-in) user.
      tags:
      - User
      x-BTVisibility: PRODUCTION
  /users/settings:
    get:
      deprecated: false
      description: "* Non-admins can call this API for their own user ID. \n* Mouse\
        \ button settings are contained in `reverseScrollWheelZoomDirection` and `viewManipulationMouseKeyMapping`.\
        \ \n* For each action in `viewManipulationMouseKeyMapping`, an array of modifier\
        \ key/mouse combos is provided that performs that action. \n* Possible modifier\
        \ keys include `SHIFT` and `CTRL`. \n* Possible mouse buttons include `MMB`\
        \ (middle mouse button), `RMB` (right mouse button), and `SCROLLWHEEL`. \n\
        * Scrolling forward zooms in, unless `reverseScrollWheelZoomDirection` is\
        \ set to `true`."
      operationId: getUserSettingsCurrentLoggedInUser
      summary: "Get the user settings for the signed-in user (i.e., you) for the current\
        \ session."
      tags:
      - User
      x-BTVisibility: PRODUCTION
  /users/{uid}/settings:
    get:
      deprecated: false
      description: "* Mouse button settings are contained in `reverseScrollWheelZoomDirection`\
        \ and `viewManipulationMouseKeyMapping`. \n* For each action in `viewManipulationMouseKeyMapping`,\
        \ an array of modifier key/mouse combos is provided that performs that action.\
        \ \n* Possible modifier keys include `SHIFT` and `CTRL`. \n* Possible mouse\
        \ buttons include `MMB` (middle mouse button), `RMB` (right mouse button),\
        \ and `SCROLLWHEEL`. \n* Scrolling forward zooms in, unless `reverseScrollWheelZoomDirection`\
        \ is set to `true`."
      operationId: getUserSettings
      summary: Get the user settings for any user in your organization (admins only).
      tags:
      - User
      x-BTVisibility: PRODUCTION
  /variables/d/{did}/w/{wid}/e/{eid}/variables:
    post:
      deprecated: false
      operationId: setVariables
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Assign variables to a Variable Studio
      tags:
      - Variables
      x-BTVisibility: PRODUCTION
  /variables/d/{did}/w/{wid}/e/{eid}/variablestudioreferences:
    post:
      deprecated: false
      operationId: setVariableStudioReferences
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Set the Variable Studio references for an element.
      tags:
      - Variables
      x-BTVisibility: PRODUCTION
  /variables/d/{did}/w/{wid}/e/{eid}/variablestudioscope:
    post:
      deprecated: false
      operationId: setVariableStudioScope
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Set the scope the Variable Studio.
      tags:
      - Variables
      x-BTVisibility: PRODUCTION
  /variables/d/{did}/w/{wid}/variablestudio:
    post:
      deprecated: false
      operationId: createVariableStudio
      security:
      - OAuth2:
        - OAuth2Write
        BasicAuth:
        - OAuth2Write
      summary: Create a new Variable Studio in a document and workspace.
      tags:
      - Variables
      x-BTVisibility: PRODUCTION
  /variables/d/{did}/{wv}/{wvid}/e/{eid}/variables:
    get:
      deprecated: false
      operationId: getVariables
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get the contents of all variable tables in an element.
      tags:
      - Variables
      x-BTVisibility: PRODUCTION
  /variables/d/{did}/{wv}/{wvid}/e/{eid}/variablestudioreferences:
    get:
      deprecated: false
      operationId: getVariableStudioReferences
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get the Variable Studio references for an element.
      tags:
      - Variables
      x-BTVisibility: PRODUCTION
  /variables/d/{did}/{wv}/{wvid}/e/{eid}/variablestudioscope:
    get:
      deprecated: false
      operationId: getVariableStudioScope
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get the scope of a Variable Studio.
      tags:
      - Variables
      x-BTVisibility: PRODUCTION
  /versions:
    get:
      deprecated: false
      operationId: getAllVersions
      summary: Get all versions of the Onshape REST APIs.
      tags:
      - Version
      x-BTVisibility: PRODUCTION
  /webhooks:
    get:
      deprecated: false
      description: "See [API Guide: Webhooks](https://onshape-public.github.io/docs/app-dev/webhook/)\
        \ for implementation details."
      operationId: getWebhooks
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get a list of all webhooks registered by a user or company.
      tags:
      - Webhook
      x-BTVisibility: PRODUCTION
    post:
      callbacks:
        onshape.user.lifecycle.updateappsettings:
          '{$request.body#/url}':
            get:
              operationId: OnshapeUserLifecycleUpdateappsettingsGet
              summary: Occurs when user application settings are modified.
              x-callback-request: true
        onshape.model.lifecycle.changed:
          '{$request.body#/url}':
            get:
              operationId: OnshapeModelLifecycleChangedGet
              summary: Occurs when a change to a model has been made.
              x-callback-request: true
        onshape.model.translation.complete:
          '{$request.body#/url}':
            get:
              operationId: OnshapeModelTranslationCompleteGet
              summary: Occurs when a translation request is completed.
              x-callback-request: true
        onshape.model.lifecycle.metadata:
          '{$request.body#/url}':
            get:
              operationId: OnshapeModelLifecycleMetadataGet
              summary: Occurs when part or element metadata is modified.
              x-callback-request: true
        onshape.model.lifecycle.createversion:
          '{$request.body#/url}':
            get:
              operationId: OnshapeModelLifecycleCreateversionGet
              summary: Occurs when a new version of a document is created.
              x-callback-request: true
        onshape.model.lifecycle.createworkspace:
          '{$request.body#/url}':
            get:
              operationId: OnshapeModelLifecycleCreateworkspaceGet
              summary: Occurs when a new workspace is created.
              x-callback-request: true
        onshape.model.lifecycle.deleteworkspace:
          '{$request.body#/url}':
            get:
              operationId: OnshapeModelLifecycleDeleteworkspaceGet
              summary: Occurs when a workspace is deleted.
              x-callback-request: true
        onshape.model.lifecycle.mergeworkspace:
          '{$request.body#/url}':
            get:
              operationId: OnshapeModelLifecycleMergeworkspaceGet
              summary: Occurs when a version or workspace is merged.
              x-callback-request: true
        onshape.model.lifecycle.restoreworkspace:
          '{$request.body#/url}':
            get:
              operationId: OnshapeModelLifecycleRestoreworkspaceGet
              summary: Occurs when a workspace is restored to a previous version or
                microversion.
              x-callback-request: true
        onshape.model.lifecycle.updateworkspaceunits:
          '{$request.body#/url}':
            get:
              operationId: OnshapeModelLifecycleUpdateworkspaceunitsGet
              summary: Occurs when workspace units or precisions are changed.
              x-callback-request: true
        onshape.model.lifecycle.createelement:
          '{$request.body#/url}':
            get:
              operationId: OnshapeModelLifecycleCreateelementGet
              summary: Occurs when a new element is created.
              x-callback-request: true
        onshape.model.lifecycle.deleteelement:
          '{$request.body#/url}':
            get:
              operationId: OnshapeModelLifecycleDeleteelementGet
              summary: Occurs when an element is deleted.
              x-callback-request: true
        onshape.document.lifecycle.statechange:
          '{$request.body#/url}':
            get:
              operationId: OnshapeDocumentLifecycleStatechangeGet
              summary: Occurs when an document changes state.
              x-callback-request: true
        onshape.model.lifecycle.changed.externalreferences:
          '{$request.body#/url}':
            get:
              operationId: OnshapeModelLifecycleChangedExternalreferencesGet
              summary: Occurs when an external reference changes.
              x-callback-request: true
        onshape.model.lifecycle.changed.namedviews:
          '{$request.body#/url}':
            get:
              operationId: OnshapeModelLifecycleChangedNamedviewsGet
              summary: Occurs when the element's named views change.
              x-callback-request: true
        onshape.document.lifecycle.created:
          '{$request.body#/url}':
            get:
              operationId: OnshapeDocumentLifecycleCreatedGet
              summary: Occurs when a document is created.
              x-callback-request: true
        onshape.revision.created:
          '{$request.body#/url}':
            get:
              operationId: OnshapeRevisionCreatedGet
              summary: Occursˇ when a revision is created.
              x-callback-request: true
        onshape.comment.create:
          '{$request.body#/url}':
            get:
              operationId: OnshapeCommentCreateGet
              summary: Occurs when a comment is created in a document.
              x-callback-request: true
        onshape.comment.update:
          '{$request.body#/url}':
            get:
              operationId: OnshapeCommentUpdateGet
              summary: Occurs when a comment is updated in a document.
              x-callback-request: true
        onshape.comment.delete:
          '{$request.body#/url}':
            get:
              operationId: OnshapeCommentDeleteGet
              summary: Occurs when a comment is deleted in a document.
              x-callback-request: true
        onshape.workflow.transition:
          '{$request.body#/url}':
            get:
              operationId: OnshapeWorkflowTransitionGet
              summary: Occurs when a revision or release package transitions through
                workflow states.
              x-callback-request: true
        webhook.ping:
          '{$request.body#/url}':
            get:
              operationId: WebhookPingGet
              summary: "Occurs either in response to a request by an application to\
                \ call a registered webhook, or as a post-registration validation\
                \ initiated by Onshape."
              x-callback-request: true
        webhook.register:
          '{$request.body#/url}':
            get:
              operationId: WebhookRegisterGet
              summary: Occurs in response to a notification registration API call.
              x-callback-request: true
        webhook.unregister:
          '{$request.body#/url}':
            get:
              operationId: WebhookUnregisterGet
              summary: Occurs in response to a notification deregistation API call.
              x-callback-request: true
      deprecated: false
      description: "Click **Callbacks** below for a list of events your app can subscribe\
        \ to. See [API Guide: Webhooks](https://onshape-public.github.io/docs/app-dev/webhook/)\
        \ for implementation details."
      operationId: createWebhook
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Create a new webhook.
      tags:
      - Webhook
      x-BTVisibility: PRODUCTION
  /webhooks/{webhookid}:
    delete:
      deprecated: false
      description: "See [API Guide: Webhooks](https://onshape-public.github.io/docs/app-dev/webhook/)\
        \ for implementation details."
      operationId: unregisterWebhook
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Unregister a webhook.
      tags:
      - Webhook
      x-BTVisibility: PRODUCTION
    get:
      deprecated: false
      description: "See [API Guide: Webhooks](https://onshape-public.github.io/docs/app-dev/webhook/)\
        \ for implementation details."
      operationId: getWebhook
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get webhook info by webhook ID.
      tags:
      - Webhook
      x-BTVisibility: PRODUCTION
    post:
      deprecated: false
      description: "See [API Guide: Webhooks](https://onshape-public.github.io/docs/app-dev/webhook/)\
        \ for implementation details."
      operationId: updateWebhook
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Update a webhook.
      tags:
      - Webhook
      x-BTVisibility: PRODUCTION
  /webhooks/{webhookid}/ping:
    post:
      deprecated: false
      description: "See [API Guide: Webhooks](https://onshape-public.github.io/docs/app-dev/webhook/)\
        \ for implementation details."
      operationId: pingWebhook
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Ping a webhook.
      tags:
      - Webhook
      x-BTVisibility: PRODUCTION
  /workflow/active:
    get:
      deprecated: false
      description: Optionally takes a document ID to return all workflows for that
        document's owning company.
      operationId: getActiveWorkflows
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get all active workflows for the currently logged in user's company.
      tags:
      - Workflow
      x-BTVisibility: PRODUCTION
  /workflow/c/{companyId}/approvers:
    get:
      deprecated: false
      description: "* Identities can be users and/or teams. \n* For Enterprise accounts,\
        \ also includes roles and any aliases that contain allowed users/teams. \n\
        * Not object- or property-specific. \n* Used for delegation and company settings."
      operationId: getAllowedApprovers
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get all identities allowed to be approvers on a workflow object.
      tags:
      - Workflow
      x-BTVisibility: PRODUCTION
  /workflow/companies/{cid}/objects:
    get:
      deprecated: false
      description: "* For example, you can enumerate RELEASES, TASKS, etc in a company\
        \ by last modified time. \n* Caller must be a company admin. \n* Specify `modifiedAfter`\
        \ and use the `next` URI for complete enumeration."
      operationId: enumerateObjectWorkflows
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Enumerate all of a company's workflowable objects.
      tags:
      - Workflow
      x-BTVisibility: PRODUCTION
  /workflow/obj/{objectId}/auditlog:
    get:
      deprecated: false
      description: Get identities (users and/or teams) allowed to be approvers on
        a workflow object for the company. Not object- or property-specific; used
        for delegation and company settings
      operationId: getAuditLog
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Get all audit log entries for a workflowable object.
      tags:
      - Workflow
      x-BTVisibility: PRODUCTION
  /events:
    post:
      deprecated: false
      operationId: fireEvent
      security:
      - OAuth2:
        - OAuth2Read
        BasicAuth:
        - OAuth2Read
      summary: Fire an asynchronous event.
      tags:
      - Event
components:
  schemas:
    Accessor:
      properties:
        bufferView:
          format: int32
          type: integer
        byteOffset:
          format: int32
          type: integer
        componentType:
          format: int32
          type: integer
        count:
          format: int32
          type: integer
        extensions:
          additionalProperties:
            type: object
          type: object
        extras:
          type: object
        max:
          items:
            type: number
          type: array
        min:
          items:
            type: number
          type: array
        name:
          type: string
        normalized:
          type: boolean
        sparse:
          $ref: '#/components/schemas/AccessorSparse'
        type:
          type: string
      type: object
    AccessorData:
      properties:
        numComponentsPerElement:
          format: int32
          type: integer
        numElements:
          format: int32
          type: integer
        totalNumComponents:
          format: int32
          type: integer
      type: object
    AccessorModel:
      properties:
        accessorData:
          $ref: '#/components/schemas/AccessorData'
        bufferViewModel:
          $ref: '#/components/schemas/BufferViewModel'
        byteOffset:
          format: int32
          type: integer
        byteStride:
          format: int32
          type: integer
        componentSizeInBytes:
          format: int32
          type: integer
        componentType:
          format: int32
          type: integer
        count:
          format: int32
          type: integer
        elementSizeInBytes:
          format: int32
          type: integer
        elementType:
          $ref: '#/components/schemas/ElementType'
        max:
          items:
            type: number
          type: array
        min:
          items:
            type: number
          type: array
        name:
          type: string
      type: object
    AccessorSparse:
      properties:
        count:
          format: int32
          type: integer
        extensions:
          additionalProperties:
            type: object
          type: object
        extras:
          type: object
        indices:
          $ref: '#/components/schemas/AccessorSparseIndices'
        values:
          $ref: '#/components/schemas/AccessorSparseValues'
      type: object
    AccessorSparseIndices:
      properties:
        bufferView:
          format: int32
          type: integer
        byteOffset:
          format: int32
          type: integer
        componentType:
          format: int32
          type: integer
        extensions:
          additionalProperties:
            type: object
          type: object
        extras:
          type: object
      type: object
    AccessorSparseValues:
      properties:
        bufferView:
          format: int32
          type: integer
        byteOffset:
          format: int32
          type: integer
        extensions:
          additionalProperties:
            type: object
          type: object
        extras:
          type: object
      type: object
    Animation:
      properties:
        channels:
          items:
            $ref: '#/components/schemas/AnimationChannel'
          type: array
        extensions:
          additionalProperties:
            type: object
          type: object
        extras:
          type: object
        name:
          type: string
        samplers:
          items:
            $ref: '#/components/schemas/AnimationSampler'
          type: array
      type: object
    AnimationChannel:
      properties:
        extensions:
          additionalProperties:
            type: object
          type: object
        extras:
          type: object
        sampler:
          format: int32
          type: integer
        target:
          $ref: '#/components/schemas/AnimationChannelTarget'
      type: object
    AnimationChannelTarget:
      properties:
        extensions:
          additionalProperties:
            type: object
          type: object
        extras:
          type: object
        node:
          format: int32
          type: integer
        path:
          type: string
      type: object
    AnimationSampler:
      properties:
        extensions:
          additionalProperties:
            type: object
          type: object
        extras:
          type: object
        input:
          format: int32
          type: integer
        interpolation:
          type: string
        output:
          format: int32
          type: integer
      type: object
    ApiResponse:
      example:
        extensions:
          key: "{}"
        get$ref: get$ref
        description: description
        links:
          key:
            server:
              extensions:
                key: "{}"
              variables:
                extensions:
                  key: "{}"
                empty: true
              description: description
              url: url
            extensions:
              key: "{}"
            get$ref: get$ref
            operationRef: operationRef
            description: description
            operationId: operationId
        content:
          empty: true
      properties:
        content:
          $ref: '#/components/schemas/ApiResponse_content'
        description:
          type: string
        extensions:
          additionalProperties:
            type: object
          type: object
        get$ref:
          type: string
      type: object
    Asset:
      properties:
        copyright:
          type: string
        extensions:
          additionalProperties:
            type: object
          type: object
        extras:
          type: object
        generator:
          type: string
        minVersion:
          type: string
        version:
          type: string
      type: object
    BTAPIApplicationExtensionInfo:
      properties:
        actionBody:
          type: string
        actionType:
          format: int32
          type: integer
        actionUrl:
          type: string
        applicationId:
          type: string
        clientId:
          type: string
        description:
          type: string
        extensionContext:
          format: int64
          type: integer
        extensionLocation:
          format: int64
          type: integer
        hasIcon:
          type: boolean
        hasPendingIcon:
          type: boolean
        href:
          description: URI to fetch complete information of the resource.
          format: uri
          type: string
        iconUrl:
          type: string
        id:
          description: Id of the resource.
          type: string
        name:
          description: Name of the resource.
          type: string
        parentAppPrimaryFormat:
          type: string
        showResponse:
          type: boolean
        viewRef:
          description: URI to visualize the resource in a webclient if applicable.
          format: uri
          type: string
        visibilityRule:
          type: string
      type: object
    BTAPIApplicationSummaryInfo:
      properties:
        clientId:
          type: string
        description:
          type: string
        href:
          description: URI to fetch complete information of the resource.
          format: uri
          type: string
        id:
          description: Id of the resource.
          type: string
        name:
          description: Name of the resource.
          type: string
        state:
          format: int32
          type: integer
        viewRef:
          description: URI to visualize the resource in a webclient if applicable.
          format: uri
          type: string
      type: object
    BTAPIWorkflowableType:
      description: All workflowable types that can be enumerated.
      enum:
      - RELEASE
      - TASK
      - ASSIGNMENT
      - OBSOLETION
      type: string
    BTAclEntryInfo:
      properties:
        acceptOwnerTransfer:
          type: boolean
        companyName:
          type: string
        email:
          type: string
        enterpriseMember:
          type: boolean
        entryId:
          type: string
        entryState:
          $ref: '#/components/schemas/BTUserState'
        entryType:
          format: int32
          type: integer
        image:
          type: string
        name:
          type: string
        objectId:
          type: string
        pendingOwnerTransfer:
          type: boolean
        permission:
          format: int64
          type: integer
        permissionSet:
          items:
            type: string
          type: array
        proCompanySubtype:
          format: int32
          type: integer
        teamName:
          type: string
      type: object
    BTAclInfo:
      properties:
        admin:
          type: boolean
        entries:
          items:
            $ref: '#/components/schemas/BTAclEntryInfo'
          type: array
        href:
          description: URI to fetch complete information of the resource.
          format: uri
          type: string
        id:
          description: Id of the resource.
          type: string
        inheritedAcls:
          items:
            $ref: '#/components/schemas/BTInheritedAclInfo'
          type: array
        name:
          description: Name of the resource.
          type: string
        objectId:
          type: string
        objectType:
          format: int64
          type: integer
        owner:
          $ref: '#/components/schemas/BTOwnerInfo'
        public:
          type: boolean
        sharedWithSupport:
          type: boolean
        viewRef:
          description: URI to visualize the resource in a webclient if applicable.
          format: uri
          type: string
        visibility:
          type: string
      type: object
    BTActiveSheetMetalFilter-2944:
      allOf:
      - $ref: '#/components/schemas/BTQueryFilter-183'
      - $ref: '#/components/schemas/BTActiveSheetMetalFilter_2944_allOf'
      properties:
        btType:
          description: Type of JSON object.
          type: string
      type: object
    BTActiveWorkflowInfo:
      properties:
        allowReleaseItemsFromOtherDocuments:
          type: boolean
        canCurrentUserCreateReleases:
          type: boolean
        canCurrentUserEditStandardContent:
          type: boolean
        canCurrentUserManageWorkflows:
          type: boolean
        canCurrentUserSeeArenaItemLink:
          type: boolean
        canCurrentUserSyncBomToArena:
          type: boolean
        canCurrentUserSyncRevisionsToArena:
          type: boolean
        canCurrentUserSyncStandardContentToArena:
          type: boolean
        canCurrentUserSyncToArena:
          type: boolean
        companyId:
          type: string
        documentId:
          type: string
        drawingCanDuplicatePartNumber:
          type: boolean
        enabledActiveMultipleWorkflows:
          type: boolean
        hasInactiveCustomWorkflows:
          type: boolean
        obsoletionWorkflow:
          $ref: '#/components/schemas/BTPublishedWorkflowInfo'
        obsoletionWorkflowId:
          type: string
        osCategoryIdToArenaNumberFormatId:
          additionalProperties:
            type: string
          type: object
        partNumberingSchemeId:
          type: string
        pickableWorkflows:
          items:
            $ref: '#/components/schemas/BTPublishedWorkflowInfo'
          type: array
        releaseWorkflow:
          $ref: '#/components/schemas/BTPublishedWorkflowInfo'
        releaseWorkflowId:
          type: string
        releaseableApplications:
          items:
            type: string
          type: array
        standardContentNumberingSchemeId:
          type: string
        standardContentUsingAutoNumbering:
          type: boolean
        standardContentUsingThirdPartyPartNumbering:
          type: boolean
        usingAutoPartNumbering:
          type: boolean
        usingManagedWorkflow:
          type: boolean
        usingThirdPartyPartNumbering:
          type: boolean
      type: object
    BTAddressInfo:
      properties:
        address:
          type: string
        city:
          type: string
        country:
          type: string
        countryCode:
          type: string
        id:
          type: string
        state:
          type: string
        stateCode:
          type: string
        zip:
          type: string
      type: object
    BTAliasEntryInfo:
      properties:
        createdAt:
          format: date-time
          type: string
        href:
          description: URI to fetch complete information of the resource.
          format: uri
          type: string
        id:
          description: Id of the resource.
          type: string
        identity:
          $ref: '#/components/schemas/BTIdentityInfo'
        name:
          description: Name of the resource.
          type: string
        viewRef:
          description: URI to visualize the resource in a webclient if applicable.
          format: uri
          type: string
      type: object
    BTAliasEntryParams:
      properties:
        email:
          type: string
        teamId:
          type: string
        userId:
          type: string
      type: object
    BTAliasInfo:
      properties:
        companyId:
          type: string
        createdAt:
          format: date-time
          type: string
        description:
          type: string
        entries:
          items:
            $ref: '#/components/schemas/BTAliasEntryInfo'
          type: array
        href:
          description: URI to fetch complete information of the resource.
          format: uri
          type: string
        id:
          description: Id of the resource.
          type: string
        identities:
          items:
            $ref: '#/components/schemas/BTIdentityInfo'
          type: array
        name:
          description: Name of the resource.
          type: string
        viewRef:
          description: URI to visualize the resource in a webclient if applicable.
          format: uri
          type: string
      type: object
    BTAliasParams:
      properties:
        additions:
          items:
            $ref: '#/components/schemas/BTAliasEntryParams'
          type: array
        description:
          type: string
        entries:
          items:
            $ref: '#/components/schemas/BTAliasEntryParams'
          type: array
        name:
          type: string
        removals:
          items:
            $ref: '#/components/schemas/BTAliasEntryParams'
          type: array
      type: object
    BTAllowEdgePointFilter-2371:
      allOf:
      - $ref: '#/components/schemas/BTQueryFilter-183'
      - $ref: '#/components/schemas/BTAllowEdgePointFilter_2371_allOf'
      properties:
        btType:
          description: Type of JSON object.
          type: string
      type: object
    BTAllowFlattenedGeometryFilter-2140:
      allOf:
      - $ref: '#/components/schemas/BTQueryFilter-183'
      - $ref: '#/components/schemas/BTAllowFlattenedGeometryFilter_2140_allOf'
      properties:
        btType:
          description: Type of JSON object.
          type: string
      type: object
    BTAllowMeshGeometryFilter-1026:
      allOf:
      - $ref: '#/components/schemas/BTQueryFilter-183'
      - $ref: '#/components/schemas/BTAllowMeshGeometryFilter_1026_allOf'
      properties:
        btType:
          description: Type of JSON object.
          type: string
      type: object
    BTAllowedMateTypeFilter-1511:
      allOf:
      - $ref: '#/components/schemas/BTMateFilter-162'
      - $ref: '#/components/schemas/BTAllowedMateTypeFilter_1511_allOf'
      properties:
        btType:
          description: Type of JSON object.
          type: string
      type: object
    BTAndFilter-110:
      allOf:
      - $ref: '#/components/schemas/BTQueryFilter-183'
      - $ref: '#/components/schemas/BTAndFilter_110_allOf'
      properties:
        btType:
          description: Type of JSON object.
          type: string
      type: object
    BTAngularDimensionDisplayData-320:
      allOf:
      - $ref: '#/components/schemas/BTDimensionDisplayData-323'
      - $ref: '#/components/schemas/BTAngularDimensionDisplayData_320_allOf'
      discriminator:
        mapping:
          BTArcLengthDimensionDisplayData-1018: '#/components/schemas/BTArcLengthDimensionDisplayData-1018'
        propertyName: btType
      properties:
        btType:
          description: Type of JSON object.
          type: string
      type: object
    BTAnnotationDisplayData-3225:
      discriminator:
        mapping:
          BTDatumDisplayData-3408: '#/components/schemas/BTDatumDisplayData-3408'
        propertyName: btType
      properties:
        annotationPlane:
          items:
            format: float
            type: number
          type: array
        baseNormal:
          items:
            format: float
            type: number
          type: array
        basePoint:
          items:
            format: float
            type: number
          type: array
        btType:
          description: Type of JSON object.
          type: string
        deterministicId:
          type: string
        dxdySegments:
          items:
            format: float
            type: number
          type: array
        numberOfLeaderSegements:
          format: int32
          type: integer
      type: object
    BTAnnotationElementDisplayData-894:
      properties:
        annotationIdToDisplayObject:
          additionalProperties:
            $ref: '#/components/schemas/BTAnnotationDisplayData-3225'
          type: object
        btType:
          description: Type of JSON object.
          type: string
      type: object
    BTApiConfiguration:
      properties:
        current:
          type: boolean
        default:
          type: boolean
        "null":
          type: boolean
        parameterMap:
          additionalProperties:
            type: string
          type: object
        standardContent:
          type: boolean
        standardContentParametersId:
          type: string
      type: object
    BTApiTable-2300:
      properties:
        btType:
          description: Type of JSON object.
          type: string
        columns:
          items:
            $ref: '#/components/schemas/BTApiTableColumn-3141'
          type: array
        entityIds:
          items:
            type: string
          type: array
        id:
          type: string
        rows:
          items:
            $ref: '#/components/schemas/BTApiTableRow-2915'
          type: array
        title:
          type: string
      type: object
    BTApiTableColumn-3141:
      properties:
        btType:
          description: Type of JSON object.
          type: string
        header:
          type: string
        id:
          type: string
        textAlignment:
          $ref: '#/components/schemas/GBTTableTextAlignment'
      type: object
    BTApiTableList-1223:
      properties:
        btType:
          description: Type of JSON object.
          type: string
        tables:
          items:
            $ref: '#/components/schemas/BTApiTable-2300'
          type: array
      type: object
    BTApiTableRow-2915:
      properties:
        btType:
          description: Type of JSON object.
          type: string
        callout:
          type: string
        columnIdToValue:
          additionalProperties:
            type: string
          type: object
        entityIds:
          items:
            type: string
          type: array
      type: object
    BTApiVersion:
      enum:
      - UNDEFINED
      - V1_START
      - V2_SERIALIZATION_UNIFICATION
      - V3_NEW_BOM_FORMAT
      - V4_TRANSACTIONS_NO_NEW
      - V5_BODY_DETAILS_COMPOSITE_REFERENCE
      - V6_JSON_EDIT_RESPONSE_BUGFIX
      - V7_SKETCH_ENDPOINT_INCLUDES_SOLVE_STATUS
      - V8_RESTORE_NOOP_NO_NEW_MICROVERSION
      - V9_INCLUDE_DETERMINISTIC_IDS_TO_QUERY_RESPONSES
      type: string
    BTAppArrayInfoBTAppDrawingViewInfo:
      properties:
        changeId:
          type: string
        errorCode:
          description: "`0: OK (healthy) | 1: INFO | 2: WARNING | 3: ERROR (dangling\
            \ or view generation call failed) | 4: UNKNOWN`"
          format: int32
          type: integer
        errorDescription:
          description: "A human-readable value for the error that occurred, if one\
            \ occurred."
          type: string
        errorValue:
          $ref: '#/components/schemas/BTAppElementErrorCode'
        items:
          items:
            $ref: '#/components/schemas/BTAppDrawingViewInfo'
          type: array
        parentChangeId:
          type: string
      type: object
    BTAppAssociativeDataArrayInfo:
      properties:
        changeId:
          type: string
        errorCode:
          description: "`0: OK (healthy) | 1: INFO | 2: WARNING | 3: ERROR (dangling\
            \ or view generation call failed) | 4: UNKNOWN`"
          format: int32
          type: integer
        errorDescription:
          description: "A human-readable value for the error that occurred, if one\
            \ occurred."
          type: string
        errorValue:
          $ref: '#/components/schemas/BTAppElementErrorCode'
        items:
          items:
            $ref: '#/components/schemas/BTAssociativeDataInfo'
          type: array
        parentChangeId:
          type: string
      type: object
    BTAppDrawingViewInfo:
      properties:
        associativityChangeId:
          type: string
        bomReferenceId:
          type: string
        brokenOutBBoxes:
          additionalProperties:
            $ref: '#/components/schemas/BTBoundingBox-1052'
          type: object
        brokenOutEndConditions:
          additionalProperties:
            $ref: '#/components/schemas/BTBrokenOutEndCondition-1107'
          type: object
        brokenOutPointNumbers:
          items:
            format: int32
            type: integer
          type: array
        changeId:
          type: string
        computeIntersection:
          type: boolean
        cutPoint:
          items:
            format: double
            type: number
          type: array
        depthSectionEndCondition:
          $ref: '#/components/schemas/BTBrokenOutEndCondition-1107'
        displayStateId:
          type: string
        errorCode:
          description: "`0: OK (healthy) | 1: INFO | 2: WARNING | 3: ERROR (dangling\
            \ or view generation call failed) | 4: UNKNOWN`"
          format: int32
          type: integer
        errorDescription:
          description: "A human-readable value for the error that occurred, if one\
            \ occurred."
          type: string
        errorValue:
          $ref: '#/components/schemas/BTAppElementErrorCode'
        explodedViewId:
          type: string
        hasSecondaryViewDefinition:
          type: boolean
        hiddenLines:
          type: string
        ignoreFaultyParts:
          type: boolean
        includeHiddenInstances:
          type: boolean
        includeSurfaces:
          type: boolean
        includeWires:
          type: boolean
        isAlignedSection:
          type: boolean
        isBrokenOutSection:
          type: boolean
        isCopiedView:
          type: boolean
        isCropView:
          type: boolean
        isPartialSection:
          type: boolean
        isSectionOfAlignedSection:
          type: boolean
        isSectionOfSectionOnBase:
          type: boolean
        isSurface:
          type: boolean
        modelReferenceId:
          type: string
        modificationId:
          type: string
        namedPositionId:
          type: string
        occurrenceOrQueryToGeometryProperties:
          additionalProperties:
            $ref: '#/components/schemas/BTAppElementViewGeometryProperties-1100'
          type: object
        offsetSectionPoints:
          items:
            format: double
            type: number
          type: array
        parentChangeId:
          type: string
        parentViewId:
          type: string
        perspective:
          type: boolean
        projectionAngle:
          type: string
        qualityOption:
          format: int32
          type: integer
        renderSketches:
          type: boolean
        sectionId:
          type: string
        showAutoCenterlines:
          type: boolean
        showAutoCentermarks:
          type: boolean
        showCutGeomOnly:
          type: boolean
        showTangentLines:
          type: boolean
        showThreads:
          type: boolean
        showViewingPlane:
          type: boolean
        simplificationOption:
          format: int32
          type: integer
        simplificationThreshold:
          format: double
          type: number
        useParentViewSectionData:
          type: boolean
        viewDirection:
          items:
            format: double
            type: number
          type: array
        viewId:
          type: string
        viewMatrix:
          items:
            format: double
            type: number
          type: array
        viewVersion:
          format: int32
          type: integer
      type: object
    BTAppElementBasicInfo:
      properties:
        changeId:
          type: string
        errorCode:
          description: "`0: OK (healthy) | 1: INFO | 2: WARNING | 3: ERROR (dangling\
            \ or view generation call failed) | 4: UNKNOWN`"
          format: int32
          type: integer
        errorDescription:
          description: "A human-readable value for the error that occurred, if one\
            \ occurred."
          type: string
        errorValue:
          $ref: '#/components/schemas/BTAppElementErrorCode'
        parentChangeId:
          type: string
      type: object
    BTAppElementBulkCreateInfo:
      properties:
        documentMicroversionId:
          description: "The latest document microversion, after the edit was committed."
          type: string
        elementIds:
          description: The ids of the created elements.
          items:
            description: The ids of the created elements.
            type: string
          type: array
        elementMicroversions:
          description: "The microversion ids of the created elements, at creation\
            \ time."
          items:
            description: "The microversion ids of the created elements, at creation\
              \ time."
            type: string
          type: array
        errorCode:
          description: "`0: OK (healthy) | 1: INFO | 2: WARNING | 3: ERROR (dangling\
            \ or view generation call failed) | 4: UNKNOWN`"
          format: int32
          type: integer
        errorDescription:
          description: "A human-readable value for the error that occurred, if one\
            \ occurred."
          type: string
        errorValue:
          $ref: '#/components/schemas/BTAppElementErrorCode'
      required:
      - documentMicroversionId
      type: object
    BTAppElementBulkCreateParams:
      properties:
        description:
          description: "The label that will appear in the document's edit history\
            \ for this operation. If blank, a value will be auto-generated."
          type: string
        formatId:
          description: The data type of the application. This string allows an application
            to distinguish their elements from elements of another application.
          type: string
        location:
          $ref: '#/components/schemas/BTElementLocationParams'
        names:
          description: "The name of the element being created. If blank, a name will\
            \ be auto-generated."
          items:
            description: "The name of the element being created. If blank, a name\
              \ will be auto-generated."
            type: string
          type: array
      required:
      - formatId
      type: object
    BTAppElementChangeParams:
      properties:
        baseContent:
          description: This base64-encoded data is treated as a full representation
            of the sub-element's data and all deltas previously added will no longer
            be returned.
          format: byte
          type: string
        delta:
          description: This base64-encoded data is a delta which the application can
            apply to the last added baseContent data.
          format: byte
          type: string
        subelementId:
          description: The id of the subelement to edit. The value is determined by
            the application.
          type: string
      required:
      - subelementId
      type: object
    BTAppElementCommitTransactionParams:
      properties:
        allowMerge:
          type: boolean
        description:
          description: "The label that will appear in the document's edit history\
            \ for this operation. If blank, a value will be auto-generated."
          type: string
        returnError:
          type: boolean
        transactionIds:
          items:
            type: string
          type: array
      type: object
    BTAppElementContentDeltaInfo:
      properties:
        delta:
          type: string
      type: object
    BTAppElementContentEntryInfo:
      properties:
        baseContent:
          type: string
        deltas:
          items:
            $ref: '#/components/schemas/BTAppElementContentDeltaInfo'
          type: array
        subelementId:
          type: string
      type: object
    BTAppElementContentInfo:
      properties:
        changeId:
          type: string
        data:
          items:
            $ref: '#/components/schemas/BTAppElementContentEntryInfo'
          type: array
        errorCode:
          description: "`0: OK (healthy) | 1: INFO | 2: WARNING | 3: ERROR (dangling\
            \ or view generation call failed) | 4: UNKNOWN`"
          format: int32
          type: integer
        errorDescription:
          description: "A human-readable value for the error that occurred, if one\
            \ occurred."
          type: string
        errorValue:
          $ref: '#/components/schemas/BTAppElementErrorCode'
      type: object
    BTAppElementErrorCode:
      enum:
      - OK
      - TRANSACTION_CONFLICT
      - NOT_FOUND
      - INCONSISTENT_CHANGES
      type: string
    BTAppElementHistoryEntryInfo:
      properties:
        changeId:
          type: string
        createdAt:
          format: date-time
          type: string
        description:
          type: string
      type: object
    BTAppElementHistoryInfo:
      properties:
        changes:
          items:
            $ref: '#/components/schemas/BTAppElementHistoryEntryInfo'
          type: array
        errorCode:
          description: "`0: OK (healthy) | 1: INFO | 2: WARNING | 3: ERROR (dangling\
            \ or view generation call failed) | 4: UNKNOWN`"
          format: int32
          type: integer
        errorDescription:
          description: "A human-readable value for the error that occurred, if one\
            \ occurred."
          type: string
        errorValue:
          $ref: '#/components/schemas/BTAppElementErrorCode'
      type: object
    BTAppElementIdsInfo:
      properties:
        changeId:
          type: string
        errorCode:
          description: "`0: OK (healthy) | 1: INFO | 2: WARNING | 3: ERROR (dangling\
            \ or view generation call failed) | 4: UNKNOWN`"
          format: int32
          type: integer
        errorDescription:
          description: "A human-readable value for the error that occurred, if one\
            \ occurred."
          type: string
        errorValue:
          $ref: '#/components/schemas/BTAppElementErrorCode'
        subelementIds:
          items:
            type: string
          type: array
      type: object
    BTAppElementModifyInfo:
      properties:
        changeId:
          description: "The latest change id for the element, after the edit was committed."
          type: string
        elementId:
          description: The id of the edited element.
          type: string
        elementIds:
          description: "The ids of the edited elements, if multiple elements were\
            \ edited."
          items:
            type: string
          type: array
        errorCode:
          description: "`0: OK (healthy) | 1: INFO | 2: WARNING | 3: ERROR (dangling\
            \ or view generation call failed) | 4: UNKNOWN`"
          format: int32
          type: integer
        errorDescription:
          description: "A human-readable value for the error that occurred, if one\
            \ occurred."
          type: string
        errorValue:
          $ref: '#/components/schemas/BTAppElementErrorCode'
        jsonDifference:
          $ref: '#/components/schemas/BTDiffJsonResponse-2725'
        parentChangeId:
          description: "The latest change id for the element, before the edit was\
            \ made."
          type: string
        propertyEditsMerged:
          description: "When committing a transaction, this field indicates if the\
            \ properties of the application element were changed after the transaction\
            \ was created."
          type: boolean
        transactionId:
          description: The id of the transaction in which the edit was applied.
          type: string
      required:
      - changeId
      type: object
    BTAppElementParams:
      properties:
        description:
          description: "The label that will appear in the document's edit history\
            \ for this operation. If blank, a value will be auto-generated."
          type: string
        formatId:
          description: The data type of the application. This string allows an application
            to distinguish their elements from elements of another application.
          type: string
        jsonTree:
          description: Initialization data for the new element's json tree.
          type: object
        location:
          $ref: '#/components/schemas/BTElementLocationParams'
        name:
          description: "The name of the element being created. If blank, a name will\
            \ be auto-generated."
          type: string
        subelements:
          description: Initialization data for the new element's subelements.
          items:
            $ref: '#/components/schemas/BTAppElementChangeParams'
          type: array
      required:
      - formatId
      type: object
    BTAppElementParamsArrayBTCopyViewAssociativeDataParams:
      properties:
        description:
          type: string
        items:
          items:
            $ref: '#/components/schemas/BTCopyViewAssociativeDataParams'
          type: array
        parentChangeId:
          type: string
        transactionId:
          type: string
      type: object
    BTAppElementReferenceInfo:
      properties:
        changeId:
          description: "The latest change id for the element, after the edit was committed."
          type: string
        errorCode:
          description: "`0: OK (healthy) | 1: INFO | 2: WARNING | 3: ERROR (dangling\
            \ or view generation call failed) | 4: UNKNOWN`"
          format: int32
          type: integer
        errorDescription:
          description: "A human-readable value for the error that occurred, if one\
            \ occurred."
          type: string
        errorValue:
          $ref: '#/components/schemas/BTAppElementErrorCode'
        parentChangeId:
          description: "The latest change id for the element, before the edit was\
            \ made."
          type: string
        referenceId:
          type: string
        transactionId:
          description: The id of the transaction in which the edit was applied.
          type: string
      required:
      - changeId
      type: object
    BTAppElementReferenceParams:
      properties:
        hasDocumentMicroversions:
          type: boolean
        idTag:
          type: string
        idTagMicroversionId:
          type: string
        isLocked:
          type: boolean
        isSketchOnly:
          type: boolean
        parentChangeId:
          type: string
        parentViewId:
          type: string
        partNumber:
          type: string
        pureSketch:
          type: boolean
        referenceType:
          format: int32
          type: integer
        returnError:
          type: boolean
        revision:
          type: string
        sketchIds:
          items:
            type: string
          type: array
        targetConfiguration:
          type: string
        targetDocumentId:
          type: string
        targetElementId:
          type: string
        targetMicroversionId:
          type: string
        targetVersionId:
          type: string
        trackNewVersions:
          type: boolean
        transactionId:
          type: string
        updateSketchInfo:
          type: boolean
      type: object
    BTAppElementReferenceResolveInfo:
      properties:
        changeId:
          type: string
        errorCode:
          description: "`0: OK (healthy) | 1: INFO | 2: WARNING | 3: ERROR (dangling\
            \ or view generation call failed) | 4: UNKNOWN`"
          format: int32
          type: integer
        errorDescription:
          description: "A human-readable value for the error that occurred, if one\
            \ occurred."
          type: string
        errorValue:
          $ref: '#/components/schemas/BTAppElementErrorCode'
        idTag:
          type: string
        idTagIsValid:
          type: boolean
        isConfigurable:
          type: boolean
        isFlattenedPart:
          type: boolean
        isLocked:
          type: boolean
        isSketchOnly:
          type: boolean
        isSurface:
          type: boolean
        latestElementMicroversionId:
          type: string
        partNumber:
          type: string
        referenceId:
          type: string
        referenceType:
          format: int32
          type: integer
        resolvedDocumentMicroversionId:
          type: string
        resolvedElementMicroversionId:
          type: string
        revision:
          type: string
        sketchIds:
          items:
            type: string
          type: array
        sourceElementId:
          type: string
        targetConfiguration:
          type: string
        targetDocumentId:
          type: string
        targetDocumentMicroversionId:
          type: string
        targetElementId:
          type: string
        targetElementMicroversionId:
          type: string
        targetVersionId:
          description: Reference to a part or assembly in a version; `NULL` when reference
            is in a workspace.
          type: string
        trackNewVersions:
          type: boolean
      type: object
    BTAppElementReferencesResolveInfo:
      properties:
        resolvedReferences:
          items:
            $ref: '#/components/schemas/BTAppElementReferenceResolveInfo'
          type: array
        unresolvedReferenceIds:
          items:
            type: string
          type: array
      type: object
    BTAppElementStartTransactionParams:
      properties:
        description:
          description: "The label that will appear in the document's edit history\
            \ for this operation. If blank, a value will be auto-generated."
          type: string
        parentChangeId:
          type: string
        returnError:
          type: boolean
      type: object
    BTAppElementTransactionsInfo:
      properties:
        elementTransactions:
          items:
            $ref: '#/components/schemas/BTElementTransaction'
          type: array
        errorCode:
          description: "`0: OK (healthy) | 1: INFO | 2: WARNING | 3: ERROR (dangling\
            \ or view generation call failed) | 4: UNKNOWN`"
          format: int32
          type: integer
        errorDescription:
          description: "A human-readable value for the error that occurred, if one\
            \ occurred."
          type: string
        errorValue:
          $ref: '#/components/schemas/BTAppElementErrorCode'
      type: object
    BTAppElementUpdateParams:
      properties:
        changes:
          description: Edits to be applied to the element's subelement data.
          items:
            $ref: '#/components/schemas/BTAppElementChangeParams'
          type: array
        description:
          description: "The label that will appear in the document's edit history\
            \ for this operation. If blank, a value will be auto-generated."
          type: string
        jsonPatch:
          description: A json patch that will be applied to the application element's
            json data.
          type: string
        jsonTreeEdit:
          $ref: '#/components/schemas/BTJEdit-3734'
        parentChangeId:
          description: The id of the last change made to this application element.
            This can be retrieved from the response for any app element modification
            endpoint.
          type: string
        propertyUpdates:
          description: Edits to be applied to the element's metadata.
          items:
            $ref: '#/components/schemas/BTMetadataPropertyUpdateParams'
          type: array
        returnError:
          description: "If true, errors in request processing will be returned in\
            \ a 200 response with a meaningful description. Otherwise, errors will\
            \ result in a relevant HTTP error response."
          type: boolean
        returnJsonDifferenceFormat:
          description: "If specified, and jsonTreeEdit is non-empty, the json difference\
            \ will be returned in this format, otherwise no json difference will be\
            \ returned."
          enum:
          - default
          - full_path
          - json_patch
          type: string
        transactionId:
          description: The id of the transaction in which this operation should take
            place. Transaction ids can be generated through the AppElement startTransaction
            API.
          type: string
      type: object
    BTAppElementViewGeometryProperties-1100:
      properties:
        btType:
          description: Type of JSON object.
          type: string
        propertyToValue:
          additionalProperties:
            type: string
          type: object
      type: object
    BTAppModificationRequestInfo:
      properties:
        documentId:
          type: string
        elementId:
          type: string
        failureReason:
          type: string
        href:
          description: URI to fetch complete information of the resource.
          format: uri
          type: string
        id:
          description: Id of the resource.
          type: string
        name:
          description: Name of the resource.
          type: string
        output:
          type: string
        outputStatusCode:
          format: int32
          type: integer
        parentDocumentMicroversionId:
          type: string
        parentElementMicroversionId:
          type: string
        requestState:
          $ref: '#/components/schemas/BTAppModificationRequestState'
        resultDocumentMicroversionId:
          type: string
        resultElementMicroversionId:
          type: string
        viewRef:
          description: URI to visualize the resource in a webclient if applicable.
          format: uri
          type: string
        workspaceId:
          type: string
      type: object
    BTAppModificationRequestState:
      enum:
      - ACTIVE
      - DONE
      - FAILED
      type: string
    BTAppearanceOverride-2517:
      properties:
        appearance:
          $ref: '#/components/schemas/BTGraphicsAppearance-1152'
        appearanceReset:
          type: boolean
        btType:
          description: Type of JSON object.
          type: string
        copyWithoutEntities:
          $ref: '#/components/schemas/BTAppearanceOverride-2517'
        entityDeterministicIds:
          items:
            type: string
          type: array
        isDeletion:
          type: boolean
      type: object
    BTApplicationElementThumbnailParams:
      properties:
        base64EncodedImage:
          type: string
        description:
          type: string
        imageHeight:
          format: int32
          type: integer
        imageWidth:
          format: int32
          type: integer
        isPrimary:
          type: boolean
        uniqueId:
          type: string
      type: object
    BTApplicationElementThumbnailParamsArray:
      properties:
        thumbnails:
          items:
            $ref: '#/components/schemas/BTApplicationElementThumbnailParams'
          type: array
      type: object
    BTApplicationSettingsType:
      enum:
      - USER
      - COMPANY
      - TEAM
      type: string
    BTApplicationTargetInfo:
      properties:
        baseHref:
          format: uri
          type: string
        clientId:
          type: string
        supportsCollaboration:
          type: boolean
        tabIconHref:
          format: uri
          type: string
      type: object
    BTArcLengthDimensionDisplayData-1018:
      allOf:
      - $ref: '#/components/schemas/BTAngularDimensionDisplayData-320'
      - $ref: '#/components/schemas/BTArcLengthDimensionDisplayData_1018_allOf'
      properties:
        btType:
          description: Type of JSON object.
          type: string
      type: object
    BTAssemblyDefinitionInfo:
      properties:
        partStudioFeatures:
          items:
            $ref: '#/components/schemas/BTAssemblyPsFeatureInfo'
          type: array
        parts:
          items:
            $ref: '#/components/schemas/BTAssemblyPartInfo'
          type: array
        rootAssembly:
          $ref: '#/components/schemas/BTRootAssemblyInfo'
        subAssemblies:
          items:
            $ref: '#/components/schemas/BTSubAssemblyInfo'
          type: array
      type: object
    BTAssemblyFeatureDataInfo:
      properties:
        name:
          type: string
      type: object
    BTAssemblyFeatureInfo:
      description: List of Assembly features including those are created by replicates.
      properties:
        featureData:
          $ref: '#/components/schemas/BTAssemblyFeatureDataInfo'
        featureType:
          type: string
        id:
          type: string
        suppressed:
          type: boolean
      type: object
    BTAssemblyFeatureListResponse-1174:
      allOf:
      - $ref: '#/components/schemas/BTFeatureApiBase-1430'
      - $ref: '#/components/schemas/BTAssemblyFeatureListResponse_1174_allOf'
      properties:
        btType:
          description: Type of JSON object.
          type: string
      type: object
    BTAssemblyInsertTransformedInstancesResponse:
      properties:
        insertInstanceResponses:
          items:
            $ref: '#/components/schemas/BTAssemblyInstanceOccurrenceInfo'
          type: array
        insertResponses:
          items:
            $ref: '#/components/schemas/BTAssemblyOccurrenceInfo'
          type: array
      type: object
    BTAssemblyInstance-947:
      allOf:
      - $ref: '#/components/schemas/BTInstance-642'
      - $ref: '#/components/schemas/BTAssemblyInstance_947_allOf'
      properties:
        btType:
          description: Type of JSON object.
          type: string
      type: object
    BTAssemblyInstanceDefinitionParams:
      properties:
        configuration:
          type: string
        documentId:
          type: string
        elementId:
          type: string
        featureId:
          type: string
        includePartTypes:
          items:
            $ref: '#/components/schemas/GBTInsertableType'
          type: array
        isAssembly:
          type: boolean
        isHidden:
          type: boolean
        isSuppressed:
          type: boolean
        isWholePartStudio:
          type: boolean
        microversionId:
          type: string
        partId:
          type: string
        partNumber:
          type: string
        revision:
          type: string
        versionId:
          type: string
      required:
      - documentId
      type: object
    BTAssemblyInstanceInfo:
      description: List of instances including those created by patterns and replicates.
      properties:
        configuration:
          type: string
        documentId:
          type: string
        documentMicroversion:
          type: string
        documentVersion:
          type: string
        elementId:
          type: string
        featureId:
          type: string
        fullConfiguration:
          type: string
        id:
          type: string
        isStandardContent:
          type: boolean
        name:
          type: string
        partId:
          type: string
        partNumber:
          type: string
        revision:
          type: string
        status:
          $ref: '#/components/schemas/BTAssemblyInstanceStatus'
        suppressed:
          type: boolean
        type:
          $ref: '#/components/schemas/BTAssemblyInstanceType'
      type: object
    BTAssemblyInstanceOccurrenceInfo:
      properties:
        occurrences:
          items:
            $ref: '#/components/schemas/BTAssemblyOccurrenceInfo'
          type: array
      type: object
    BTAssemblyInstanceStatus:
      enum:
      - DeletedElement
      type: string
    BTAssemblyInstanceType:
      enum:
      - Assembly
      - Feature
      - Part
      - Unknown
      type: string
    BTAssemblyItemMetadataInfo:
      properties:
        children:
          items:
            $ref: '#/components/schemas/BTAssemblyItemMetadataInfo'
          type: array
        propertyIdToError:
          additionalProperties:
            type: string
          type: object
        propertyIdToEvalInfo:
          additionalProperties:
            type: string
          type: object
        propertyIdToOverrideStatus:
          additionalProperties:
            type: string
          type: object
        propertyIdToSourceType:
          additionalProperties:
            type: string
          type: object
        propertyIdToValue:
          additionalProperties:
            type: string
          type: object
        requestInfo:
          $ref: '#/components/schemas/BTAssemblyItemMetadataRequestInfo'
      type: object
    BTAssemblyItemMetadataRequestInfo:
      properties:
        apiConfig:
          type: string
        documentId:
          type: string
        elementId:
          type: string
        itemId:
          type: string
        linkedDocumentId:
          type: string
        partId:
          type: string
        wvmId:
          type: string
        wvmType:
          type: string
      type: object
    BTAssemblyMateConnectorInfo:
      properties:
        featureId:
          type: string
        mateConnectorCS:
          $ref: '#/components/schemas/BTMateConnectorCSInfo'
      type: object
    BTAssemblyMirror-2996:
      allOf:
      - $ref: '#/components/schemas/BTParametricInstance-2641'
      - $ref: '#/components/schemas/BTAssemblyMirror_2996_allOf'
      properties:
        btType:
          description: Type of JSON object.
          type: string
      type: object
    BTAssemblyModificationParams:
      properties:
        deleteInstances:
          items:
            type: string
          type: array
        editDescription:
          type: string
        suppressInstances:
          items:
            type: string
          type: array
        transformDefinitions:
          items:
            $ref: '#/components/schemas/BTAssemblyTransformDefinitionParams'
          type: array
        unsuppressInstances:
          items:
            type: string
          type: array
      type: object
    BTAssemblyOccurrenceInfo:
      properties:
        fixed:
          type: boolean
        hidden:
          type: boolean
        path:
          items:
            type: string
          type: array
        transform:
          items:
            format: double
            type: number
          type: array
      type: object
    BTAssemblyPartBodyType:
      enum:
      - solid
      - sheet
      - composite
      type: string
    BTAssemblyPartInfo:
      properties:
        bodyType:
          $ref: '#/components/schemas/BTAssemblyPartBodyType'
        configuration:
          type: string
        documentId:
          type: string
        documentMicroversion:
          type: string
        documentVersion:
          type: string
        elementId:
          type: string
        fullConfiguration:
          type: string
        isStandardContent:
          type: boolean
        mateConnectors:
          items:
            $ref: '#/components/schemas/BTAssemblyMateConnectorInfo'
          type: array
        partId:
          type: string
        partNumber:
          type: string
        revision:
          type: string
      type: object
    BTAssemblyPattern-1974:
      allOf:
      - $ref: '#/components/schemas/BTParametricInstance-2641'
      - $ref: '#/components/schemas/BTAssemblyPattern_1974_allOf'
      properties:
        btType:
          description: Type of JSON object.
          type: string
      type: object
    BTAssemblyPatternInfo:
      description: Pattern description.
      properties:
        id:
          description: Id of the pattern.
          type: string
        name:
          description: Name of the pattern.
          type: string
        seedToPatternInstances:
          additionalProperties:
            description: Mapping of seed to pattern instance ids.
            items:
              description: Mapping of seed to pattern instance ids.
              type: string
            type: array
          description: Mapping of seed to pattern instance ids.
          type: object
        suppressed:
          description: If pattern is suppressed.
          type: boolean
        type:
          $ref: '#/components/schemas/GBTPatternType'
      type: object
    BTAssemblyPsFeatureInfo:
      properties:
        configuration:
          type: string
        documentId:
          type: string
        documentMicroversion:
          type: string
        documentVersion:
          type: string
        elementId:
          type: string
        featureId:
          type: string
        featureType:
          type: string
        fullConfiguration:
          type: string
        partNumber:
          type: string
        revision:
          type: string
      type: object
    BTAssemblyReferencesDisplayData-1562:
      properties:
        annotationsForElement:
          $ref: '#/components/schemas/BTAnnotationElementDisplayData-894'
        assemblyReferences:
          items:
            $ref: '#/components/schemas/BTSingleReferenceDisplayData-1943'
          type: array
        btType:
          description: Type of JSON object.
          type: string
        elementId:
          type: string
        fromFullElementId:
          $ref: '#/components/schemas/BTFullElementId-756'
        fullElementId:
          $ref: '#/components/schemas/BTFullElementId-756'
        incremental:
          type: boolean
        instanceCount:
          format: int32
          type: integer
        keepFromMicroversion:
          type: boolean
        microversionId:
          $ref: '#/components/schemas/BTMicroversionId-366'
        microversionIdAndConfigurationInterval:
          $ref: '#/components/schemas/BTMicroversionIdAndConfigurationInterval-2364'
        microversionInterval:
          $ref: '#/components/schemas/BTMicroversionIdInterval-367'
        versionForRasterization:
          $ref: '#/components/schemas/BTElementDisplayData-326'
      type: object
    BTAssemblyReplicate-2774:
      allOf:
      - $ref: '#/components/schemas/BTParametricInstance-2641'
      - $ref: '#/components/schemas/BTAssemblyReplicate_2774_allOf'
      properties:
        btType:
          description: Type of JSON object.
          type: string
      type: object
    BTAssemblySimulation-2246:
      allOf:
      - $ref: '#/components/schemas/BTMAssemblyFeature-887'
      - $ref: '#/components/schemas/BTAssemblySimulation_2246_allOf'
      properties:
        btType:
          description: Type of JSON object.
          type: string
      type: object
    BTAssemblySimulationData-978:
      allOf:
      - $ref: '#/components/schemas/BTMNode-19'
      - $ref: '#/components/schemas/BTAssemblySimulationData_978_allOf'
      properties:
        btType:
          description: Type of JSON object.
          type: string
      type: object
    BTAssemblySimulationStructuralLoadsTable-3867:
      allOf:
      - $ref: '#/components/schemas/BTTable-1825'
      - $ref: '#/components/schemas/BTAssemblySimulationStructuralLoadsTable_3867_allOf'
      properties:
        btType:
          description: Type of JSON object.
          type: string
      type: object
    BTAssemblySimulationTable-3236:
      allOf:
      - $ref: '#/components/schemas/BTTable-1825'
      - $ref: '#/components/schemas/BTAssemblySimulationTable_3236_allOf'
      properties:
        btType:
          description: Type of JSON object.
          type: string
      type: object
    BTAssemblyTransformDefinitionParams:
      properties:
        isRelative:
          type: boolean
        occurrences:
          items:
            $ref: '#/components/schemas/BTOccurrence-74'
          type: array
        transform:
          items:
            format: double
            type: number
          type: array
      type: object
    BTAssemblyTransformedInstancesDefinitionParams:
      properties:
        transformGroups:
          items:
            $ref: '#/components/schemas/TransformGroup'
          type: array
      type: object
    BTAssociativeDataInfo:
      properties:
        associativeDataId:
          type: string
        data:
          items:
            $ref: '#/components/schemas/BTNameValuePair'
          type: array
        documentId:
          type: string
        documentMicroversion:
          type: string
        elementId:
          type: string
        error:
          type: string
        idTag:
          type: string
        microversionId:
          type: string
        occurrenceId:
          type: string
        type:
          $ref: '#/components/schemas/GBTAppElementAssociativeDataType'
        versionId:
          type: string
      type: object
    BTBDrawingOperationParams:
      description: A single drawing entity creation or modification definition
      properties:
        formatVersion:
          description: Version of drawing entity format.
          type: string
        messageName:
          description: "Type of drawing modification operation: `onshapeCreateAnnotations`\
            \ | `onshapeEditAnnotations`"
          type: string
      required:
      - formatVersion
[...]
