{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Onshape REST API",
    "description" : "## Welcome to the Onshape REST API Explorer\n\nTo use this API explorer, sign in to your [Onshape](https://cad.onshape.com) account in another tab, then click the **Try it out** button below (it toggles to a **Cancel** button when selected).\n\nSee the **[API Explorer Guide](https://onshape-public.github.io/docs/api-intro/explorer/)** for help navigating this API Explorer, including **[authentication](https://onshape-public.github.io/docs/api-intro/explorer/#authentication)*[...]",
    "termsOfService" : "https://www.onshape.com/legal/terms-of-use",
    "contact" : {
      "email" : "api-support@onshape.zendesk.com"
    },
    "license" : {
      "name" : "Apache 2.0",
      "url" : "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version" : "1.194.51923-8c2ff2e03a86",
    "x-logo" : {
      "url" : "images/logo-onshape-gray-green.svg",
      "backgroundColor" : "#ffffff",
      "altText" : "Onshape",
      "href" : "images/logo-onshape-gray-green.svg"
    },
    "x-indeterministic-schemas" : [ "BTDiffInfo", "BTParameterSpecArray-2600", "BTSplineDescription-2118", "NodeModel", "BTPFunctionDeclaration-246", "BTPFunctionOrPredicateDeclaration-247", "BTPExpression-9", "SkinModel", "BTMAnnotation-4664" ],
    "x-filter-info" : "?restUserRole=PUBLIC"
  },
  "servers" : [ {
    "url" : "https://cad.onshape.com/api/v10",
    "description" : "Current"
  } ],
  "security" : [ {
    "BasicAuth" : [ ]
  } ],
  "tags" : [ {
    "name" : "APIApplication",
    "description" : "Manage application preferences."
  }, {
    "name" : "Account",
    "description" : "Manage user purchases, subscriptions, and consumables."
  }, {
    "name" : "Alias",
    "description" : "Create and manage enterprise aliases. (Enterprise admins only.)"
  }, {
    "name" : "AppAssociativeData",
    "description" : "Manage the application-specific metadata that associates application data with Onshape data."
  }, {
    "name" : "AppElement",
    "description" : "Access and modify application elements."
  }, {
    "name" : "Assembly",
    "description" : "Create and manage assemblies."
  }, {
    "name" : "Billing",
    "description" : "Get billing plan data for applications."
  }, {
    "name" : "BlobElement",
    "description" : "Create, modify, and translate blob elements."
  }, {
    "name" : "Comment",
    "description" : "Create, read, update, and delete comments."
  }, {
    "name" : "Company",
    "description" : "Access company information."
  }, {
    "name" : "Document",
    "description" : "Create and manage documents."
  }, {
    "name" : "Drawing",
    "description" : "Access, create, and translate drawings."
  }, {
    "name" : "Element",
    "description" : "Access and manage Elements. Every Element in an Onshape document is represented by a tab."
  }, {
    "name" : "ExportRule",
    "description" : "Access valid export rules."
  }, {
    "name" : "FeatureStudio",
    "description" : "Access and manage Feature Studio Elements."
  }, {
    "name" : "Folder",
    "description" : "Access and modify folder sharing permissions."
  }, {
    "name" : "Insertable",
    "description" : "Access the list of things that can be inserted into a document."
  }, {
    "name" : "Metadata",
    "description" : "Access and modify metadata."
  }, {
    "name" : "MetadataCategory",
    "description" : "Access properties associated with metadata categories."
  }, {
    "name" : "NumberingScheme",
    "description" : "Manage the set of valid Part numbers."
  }, {
    "name" : "OpenApi",
    "description" : "Get the OpenAPI specification for the Onshape API."
  }, {
    "name" : "Part",
    "description" : "Export Parts and access Part details."
  }, {
    "name" : "PartNumber",
    "description" : "Create valid part numbers."
  }, {
    "name" : "PartStudio",
    "description" : "Access and modify Part Studios."
  }, {
    "name" : "PropertiesTableTemplate",
    "description" : "Create, access, and delete templates for properties tables."
  }, {
    "name" : "Publication",
    "description" : "Access publication information."
  }, {
    "name" : "ReleasePackage",
    "description" : "Access and update Release Management workflows."
  }, {
    "name" : "Revision",
    "description" : "Access, delete, and enumerate revisions."
  }, {
    "name" : "Sketch",
    "description" : "Access sketch information."
  }, {
    "name" : "Task",
    "description" : "Create, access, and modify Tasks and Action Items."
  }, {
    "name" : "Team",
    "description" : "Access team information."
  }, {
    "name" : "Thumbnail",
    "description" : "Access, modify, and delete thumbnails."
  }, {
    "name" : "Translation",
    "description" : "Import and export Onshape surfaces, parts, Part Studios, Assemblies, and subassemblies to/from other file formats (STL, PARASOLID, SOLIDWORKS, etc)."
  }, {
    "name" : "User",
    "description" : "Access user information."
  }, {
    "name" : "Variables",
    "description" : "Create, modify, and access variables."
  }, {
    "name" : "Version",
    "description" : "Get all versions of the Onshape REST APIs."
  }, {
    "name" : "Webhook",
    "description" : "Create and manage [webhooks](https://onshape-public.github.io/docs/app-dev/webhook/)."
  }, {
    "name" : "Workflow",
    "description" : "Access and modify workflows."
  } ],
  "paths" : {
    "/accounts/plans/{planId}/purchases" : {
      "get" : {
        "tags" : [ "Account" ],
        "summary" : "Get a list of all app purchases made for the specified plan.",
        "operationId" : "getPlanPurchases",
        "deprecated" : false,
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/accounts/purchases" : {
      "get" : {
        "tags" : [ "Account" ],
        "summary" : "Get a list of all app purchases made by the current user.",
        "description" : "This API should be used within the context of an OAuth-enabled application.",
        "operationId" : "getPurchases",
        "deprecated" : false,
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/accounts/purchases/{pid}/consume" : {
      "post" : {
        "tags" : [ "Account" ],
        "summary" : "Mark a purchase as consumed by the current user.",
        "operationId" : "consumePurchase",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Purchase" ],
          "BasicAuth" : [ "OAuth2Purchase" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/accounts/{aid}/purchases/{pid}" : {
      "delete" : {
        "tags" : [ "Account" ],
        "summary" : "Cancel a recurring subscription for the specified account ID and purchase ID.",
        "operationId" : "cancelPurchaseNew",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Purchase" ],
          "BasicAuth" : [ "OAuth2Purchase" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/aliases" : {
      "get" : {
        "tags" : [ "Alias" ],
        "summary" : "Get a list of all aliases that exist for your enterprise.",
        "operationId" : "getAliasesInCompany",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      },
      "post" : {
        "tags" : [ "Alias" ],
        "summary" : "Create an alias in your enterprise.",
        "description" : "`Manage users and teams` global permission is required to call this API.",
        "operationId" : "createAlias",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/aliases/{aid}" : {
      "get" : {
        "tags" : [ "Alias" ],
        "summary" : "Get an alias by ID.",
        "description" : "Get the information for an alias ID.",
        "operationId" : "getAlias",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      },
      "post" : {
        "tags" : [ "Alias" ],
        "summary" : "Add, remove, replace, or rename entries in an alias list.",
        "description" : "`Manage users and teams` global permission is required to call this API. \n* Add new users in the `additions` array. \n* Remove existing users in the `removals` array. Attempts to remove a user that does not exist in the Alias list will have no effect.\n* Replace the entire Alias list with the `entries` array. \n* You can also update the alias' `name` and `description`. \nFor example, given an Alias with members userA and userB: \n* `additions: [userC]` results in [userA[...]",
        "operationId" : "updateAlias",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      },
      "delete" : {
        "tags" : [ "Alias" ],
        "summary" : "Delete an alias from your enterprise.",
        "description" : "`Manage users and teams` global permission is required to call this API.",
        "operationId" : "deleteAlias",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/aliases/{aid}/members" : {
      "get" : {
        "tags" : [ "Alias" ],
        "summary" : "Get all users and teams assigned to an alias.",
        "description" : "This is a search-like endpoint that returns a subset of the member list. Use `getAlias` to return all members every time it's called.",
        "operationId" : "getAliasMembers",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/appelements/d/{did}/w/{wid}" : {
      "post" : {
        "tags" : [ "AppElement" ],
        "summary" : "Create a new application element.",
        "operationId" : "createElement",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/appelements/d/{did}/w/{wid}/bulkcreate" : {
      "post" : {
        "tags" : [ "AppElement" ],
        "summary" : "Create multiple empty application elements at once.",
        "description" : "Call this faster API instead of creating multiple app elements one at a time or in parallel.",
        "operationId" : "bulkCreateElement",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/appelements/d/{did}/w/{wid}/e/{eid}/blob/{bid}" : {
      "get" : {
        "tags" : [ "AppElement" ],
        "summary" : "Download the blob element (i.e., a file) stored in an app element in a document's workspace.",
        "description" : "The downloaded file can be used to retrieve stored subelements.",
        "operationId" : "downloadBlobSubelementWorkspace",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      },
      "post" : {
        "tags" : [ "AppElement" ],
        "summary" : "Create a new blob subelement from an uploaded file.",
        "description" : "Request body parameters are multipart fields, so you must use `\"Content-Type\":\"multipart/form-data\"` in the request header.",
        "operationId" : "uploadBlobSubelement",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      },
      "delete" : {
        "tags" : [ "AppElement" ],
        "summary" : "Delete a blob subelement from an app element.",
        "operationId" : "deleteBlobSubelement",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/appelements/d/{did}/w/{wid}/e/{eid}/copyassociativedata" : {
      "post" : {
        "tags" : [ "AppAssociativeData" ],
        "summary" : "Copy associative data from one view to another.",
        "description" : "Can only be copied between tabs in the same document. You can manage associativity with [translateIds](https://cad.onshape.com/glassworks/explorer/#/PartStudio/translateIds).",
        "operationId" : "copyAssociativeData",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/appelements/d/{did}/w/{wid}/e/{eid}/transactions" : {
      "get" : {
        "tags" : [ "AppElement" ],
        "summary" : "Get a list of all transactions performed on an element.",
        "operationId" : "getElementTransactions",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      },
      "post" : {
        "tags" : [ "AppElement" ],
        "summary" : "Start a transaction",
        "description" : "Creates a microbranch (i.e., a branch for a new microversion).",
        "operationId" : "startTransaction",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/appelements/d/{did}/w/{wid}/e/{eid}/transactions/{tid}" : {
      "delete" : {
        "tags" : [ "AppElement" ],
        "summary" : "Abort a transaction.",
        "description" : "Deletes a microbranch (i.e., the branch with the microversion for the transaction).",
        "operationId" : "abortTransaction",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/appelements/d/{did}/w/{wid}/transactions" : {
      "post" : {
        "tags" : [ "AppElement" ],
        "summary" : "Merge multiple transactions into one microversion.",
        "description" : "If successful, all transactions will be committed to a single microversion. If the call raises an error, nothing will be committed.",
        "operationId" : "commitTransactions",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/appelements/d/{did}/{vm}/{vmid}/e/{eid}/blob/{bid}" : {
      "get" : {
        "tags" : [ "AppElement" ],
        "summary" : "Download a blob subelement from the specified app element.",
        "description" : "Download a blob subelement as a file.",
        "operationId" : "downloadBlobSubelement",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/appelements/d/{did}/{wvm}/{wvmid}/e/{eid}/associativedata" : {
      "get" : {
        "tags" : [ "AppAssociativeData" ],
        "summary" : "Get the associative data for the specified app element.",
        "description" : "You can manage associativity with [translateIds](https://cad.onshape.com/glassworks/explorer/#/PartStudio/translateIds).",
        "operationId" : "getAssociativeData",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      },
      "post" : {
        "tags" : [ "AppAssociativeData" ],
        "summary" : "Set the associative data for the specified app element.",
        "description" : "You can manage associativity with [translateIds](https://cad.onshape.com/glassworks/explorer/#/PartStudio/translateIds).",
        "operationId" : "postAssociativeData",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read", "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Read", "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      },
      "delete" : {
        "tags" : [ "AppAssociativeData" ],
        "summary" : "Delete the associative data from the specified app element.",
        "description" : "You can manage associativity with [translateIds](https://cad.onshape.com/glassworks/explorer/#/PartStudio/translateIds).",
        "operationId" : "deleteAssociativeData",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/appelements/d/{did}/{wvm}/{wvmid}/e/{eid}/blob" : {
      "get" : {
        "tags" : [ "AppElement" ],
        "summary" : "Get a list of all blob subelement IDs for the specified workspace, version, or microversion.",
        "operationId" : "getBlobSubelementIds",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/appelements/d/{did}/{wvm}/{wvmid}/e/{eid}/compare" : {
      "get" : {
        "tags" : [ "AppElement" ],
        "summary" : "Compare app element JSON trees between workspaces/versions/microversions in a document.",
        "description" : "Specify the source workspace/version/microversion in the URL and specify the target workspace/version/microversion in the query parameters.",
        "operationId" : "compareAppElementJson",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/appelements/d/{did}/{wvm}/{wvmid}/e/{eid}/content" : {
      "get" : {
        "tags" : [ "AppElement" ],
        "summary" : "Get a list of all subelement IDs in a specified workspace/version/microversion.",
        "operationId" : "getSubElementContent",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      },
      "post" : {
        "tags" : [ "AppElement" ],
        "summary" : "Update the content for the specified app element.",
        "operationId" : "updateAppElement",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read", "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Read", "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/appelements/d/{did}/{wvm}/{wvmid}/e/{eid}/content/history" : {
      "get" : {
        "tags" : [ "AppElement" ],
        "summary" : "Get the history of the specified all element.",
        "operationId" : "getAppElementHistory",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/appelements/d/{did}/{wvm}/{wvmid}/e/{eid}/content/ids" : {
      "get" : {
        "tags" : [ "AppElement" ],
        "summary" : "Get a list of all subelement IDs in a specified workspace/version/microversion.",
        "operationId" : "getSubelementIds",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/appelements/d/{did}/{wvm}/{wvmid}/e/{eid}/content/json" : {
      "get" : {
        "tags" : [ "AppElement" ],
        "summary" : "Get the full JSON tree for the specified workspace/version/microversion.",
        "operationId" : "getJson",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/appelements/d/{did}/{wvm}/{wvmid}/e/{eid}/content/jsonpaths" : {
      "post" : {
        "tags" : [ "AppElement" ],
        "summary" : "Get the JSON at specified paths for an element.",
        "description" : "Use this endpoint to return the JSON at the specified path instead of returning the entire JSON for the element. This POST endpoint does not write any information.",
        "operationId" : "getJsonPaths",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/appelements/d/{did}/{wvm}/{wvmid}/e/{eid}/content/subelements" : {
      "delete" : {
        "tags" : [ "AppElement" ],
        "summary" : "Delete multiple subelements array by document ID, workspace or version or microversion ID, tab ID, and subelement IDs.",
        "operationId" : "deleteAppElementContentBatch",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/appelements/d/{did}/{wvm}/{wvmid}/e/{eid}/content/subelements/{sid}" : {
      "delete" : {
        "tags" : [ "AppElement" ],
        "summary" : "Deletes the content from the specified app element.",
        "operationId" : "deleteAppElementContent",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/appelements/d/{did}/{wvm}/{wvmid}/e/{eid}/references" : {
      "post" : {
        "tags" : [ "AppElement" ],
        "summary" : "Creates a reference to an app element.",
        "operationId" : "createReference",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/appelements/d/{did}/{wvm}/{wvmid}/e/{eid}/references/{rid}" : {
      "get" : {
        "tags" : [ "AppElement" ],
        "summary" : "Resolves a single reference to an app element.",
        "description" : "For single operations only. Use `resolveReferences` for bulk operations.",
        "operationId" : "resolveReference",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      },
      "post" : {
        "tags" : [ "AppElement" ],
        "summary" : "Update an app element reference.",
        "operationId" : "updateReference",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      },
      "delete" : {
        "tags" : [ "AppElement" ],
        "summary" : "Delete an app element reference.",
        "operationId" : "deleteReference",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/appelements/d/{did}/{wvm}/{wvmid}/e/{eid}/resolvereferences" : {
      "get" : {
        "tags" : [ "AppElement" ],
        "summary" : "Resolves bulk app element references.",
        "description" : "For bulk operations only. Use `resolveReference` for a single operation.",
        "operationId" : "resolveReferences",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/appelements/d/{did}/{wvm}/{wvmid}/resolvereferences" : {
      "get" : {
        "tags" : [ "AppElement" ],
        "summary" : "Resolves bulk app element references.",
        "description" : "Resolve all references for all workspace elements. For bulk operations  only. Use `resolveReferences` for a single element.",
        "operationId" : "resolveAllElementReferences",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/applications/clients/{cid}/settings/companies/{cpid}" : {
      "get" : {
        "tags" : [ "APIApplication" ],
        "summary" : "Get company-level preference settings for an application.",
        "description" : "This API is only usable with an OAuth token and only by the current user or admin.",
        "operationId" : "getCompanyAppSettings",
        "deprecated" : false,
        "x-BTVisibility" : "PRODUCTION"
      },
      "post" : {
        "tags" : [ "APIApplication" ],
        "summary" : "Update company preference settings for an application.",
        "description" : "This API is only usable with an OAuth token and only by the current user or admin. \n* Add or update a setting identified by key with value. \n* Operation and field may optionally be specified when updating Map type settings. \n* Field specifies the key of the setting Map to update. \n* Operation may be one of: \n    * `ADD`: Add or update an existing field of the settings Map. \n    * `UPDATE`: Update an existing field of the settings Map and return an error if the fiel[...]",
        "operationId" : "updateAppCompanySettings",
        "deprecated" : false,
        "x-BTVisibility" : "PRODUCTION"
      },
      "delete" : {
        "tags" : [ "APIApplication" ],
        "summary" : "Delete a company's application preference settings.",
        "description" : "This API is only usable with an OAuth token and only by the current user or admin.",
        "operationId" : "deleteCompanyAppSettings",
        "deprecated" : false,
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/applications/clients/{cid}/settings/users/{uid}" : {
      "get" : {
        "tags" : [ "APIApplication" ],
        "summary" : "Get user-level preference settings for an application.",
        "description" : "This API is only usable with an OAuth token and only by the current user or admin.",
        "operationId" : "getUserAppSettings",
        "deprecated" : false,
        "x-BTVisibility" : "PRODUCTION"
      },
      "post" : {
        "tags" : [ "APIApplication" ],
        "summary" : "Update a user's application preference settings.",
        "description" : "This API is only usable with an OAuth token and only by the current user or admin. \n* Add or update a setting identified by key with value. \n* Operation and field may optionally be specified when updating Map type settings. \n* Field specifies the key of the setting Map to update. \n* Operation may be one of: \n    * `ADD`: Add or update an existing field of the settings Map. \n    * `UPDATE`: Update an existing field of the settings Map and return an error if the fiel[...]",
        "operationId" : "updateAppSettings",
        "deprecated" : false,
        "x-BTVisibility" : "PRODUCTION"
      },
      "delete" : {
        "tags" : [ "APIApplication" ],
        "summary" : "Delete a user's application preference settings.",
        "description" : "This API is only usable with an OAuth token and only by the current user or admin.",
        "operationId" : "deleteAppSettings",
        "deprecated" : false,
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/applications/extensions/user/{uid}/client/{cid}" : {
      "get" : {
        "tags" : [ "APIApplication" ],
        "summary" : "Get a list of the client extensions the specified user has granted/accepted terms for.",
        "operationId" : "getApplicableExtensionsForClient",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2ReadPII" ],
          "BasicAuth" : [ "OAuth2ReadPII" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/assemblies/d/{did}/e/{eid}/namedViews" : {
      "get" : {
        "tags" : [ "Assembly" ],
        "summary" : "Get the view data for all named views for the specified element.",
        "operationId" : "getNamedViews",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/assemblies/d/{did}/w/{wid}" : {
      "post" : {
        "tags" : [ "Assembly" ],
        "summary" : "Create a new assembly tab in the document.",
        "operationId" : "createAssembly",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/assemblies/d/{did}/w/{wid}/e/{eid}/bomelement" : {
      "post" : {
        "tags" : [ "Assembly" ],
        "summary" : "Gets the Bill Of Materials (BOM) for the specified assembly, or creates a BOM if none exist.",
        "operationId" : "getOrCreateBillOfMaterialsElement",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/assemblies/d/{did}/w/{wid}/e/{eid}/features/featureid/{fid}" : {
      "post" : {
        "tags" : [ "Assembly" ],
        "summary" : "Update an existing feature for an Assembly.",
        "operationId" : "updateFeature",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      },
      "delete" : {
        "tags" : [ "Assembly" ],
        "summary" : "Delete a feature from an assembly.",
        "operationId" : "deleteFeature",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/assemblies/d/{did}/w/{wid}/e/{eid}/instance/nodeid/{nid}" : {
      "delete" : {
        "tags" : [ "Assembly" ],
        "summary" : "Delete an instance of an assembly.",
        "operationId" : "deleteInstance",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/assemblies/d/{did}/w/{wid}/e/{eid}/instances" : {
      "post" : {
        "tags" : [ "Assembly" ],
        "summary" : "Insert an instance of a part, sketch, assembly, or Part Studio into an assembly.",
        "description" : "Part Studio instances may include multiple parts.",
        "operationId" : "createInstance",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read", "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Read", "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/assemblies/d/{did}/w/{wid}/e/{eid}/matevalues" : {
      "get" : {
        "tags" : [ "Assembly" ],
        "summary" : "Get a list of mate values in the specified assembly.",
        "description" : "Describes the relative position of the first mate connector with respect to the second along the designated degrees of freedom (DOF) for mates in the specified assembly.",
        "operationId" : "getMateValues",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      },
      "post" : {
        "tags" : [ "Assembly" ],
        "summary" : "Update mate values for the given mates in the specified assembly.",
        "description" : "* The input mates must support motion along the provided input degrees of freedom; otherwise, the input mate value will be ignored. \n* Values associated with multiple allowed degrees of freedom for a mate can be updated simultaneously. \n* Values associated with multiple mate features can be updated simultaneously.",
        "operationId" : "updateMateValues",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/assemblies/d/{did}/w/{wid}/e/{eid}/modify" : {
      "post" : {
        "tags" : [ "Assembly" ],
        "summary" : "Modify an assembly.",
        "description" : "This endpoint can include multiple modifications to an assembly with one change. For example, it can delete/suppress/unsuppress/transform multiple instances. It creates one history entry in the document history list.",
        "operationId" : "modify",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/assemblies/d/{did}/w/{wid}/e/{eid}/occurrencetransforms" : {
      "post" : {
        "tags" : [ "Assembly" ],
        "summary" : "Transform a list of assembly occurrences.",
        "operationId" : "transformOccurrences",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read", "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Read", "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/assemblies/d/{did}/w/{wid}/e/{eid}/transformedinstances" : {
      "post" : {
        "tags" : [ "Assembly" ],
        "summary" : "Create new instances with transformation.",
        "operationId" : "insertTransformedInstances",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read", "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Read", "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/assemblies/d/{did}/{wvm}/{wvmid}/e/{eid}" : {
      "get" : {
        "tags" : [ "Assembly" ],
        "summary" : "Get definition information for the specified assembly.",
        "description" : "All coordinates and translation matrix components are in meters (m).",
        "operationId" : "getAssemblyDefinition",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/assemblies/d/{did}/{wvm}/{wvmid}/e/{eid}/bom" : {
      "get" : {
        "tags" : [ "Assembly" ],
        "summary" : "Get the Bill Of Materials (BOM) content for the specified assembly.",
        "description" : "Returns the BOM in JSON in the Onshape BOM Standard format.",
        "operationId" : "getBillOfMaterials",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/assemblies/d/{did}/{wvm}/{wvmid}/e/{eid}/boundingboxes" : {
      "get" : {
        "tags" : [ "Assembly" ],
        "summary" : "Get bounding box information for the specified assembly.",
        "operationId" : "getAssemblyBoundingBoxes",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/assemblies/d/{did}/{wvm}/{wvmid}/e/{eid}/displaystates" : {
      "get" : {
        "tags" : [ "Assembly" ],
        "summary" : "Get a list of display states for the specified assembly.",
        "operationId" : "getDisplayStates",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/assemblies/d/{did}/{wvm}/{wvmid}/e/{eid}/explodedviews" : {
      "get" : {
        "tags" : [ "Assembly" ],
        "summary" : "Get a list of exploded views for the specified assembly.",
        "operationId" : "getExplodedViews",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/assemblies/d/{did}/{wvm}/{wvmid}/e/{eid}/features" : {
      "get" : {
        "tags" : [ "Assembly" ],
        "summary" : "Get the definitions of the specified features in an assembly.",
        "operationId" : "getFeatures",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      },
      "post" : {
        "tags" : [ "Assembly" ],
        "summary" : "Add a feature to the assembly feature list.",
        "operationId" : "addFeature",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/assemblies/d/{did}/{wvm}/{wvmid}/e/{eid}/featurespecs" : {
      "get" : {
        "tags" : [ "Assembly" ],
        "summary" : "Get the feature spec definitions for an assembly.",
        "operationId" : "getFeatureSpecs",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/assemblies/d/{did}/{wvm}/{wvmid}/e/{eid}/massproperties" : {
      "get" : {
        "tags" : [ "Assembly" ],
        "summary" : "Get the mass properties for the assembly.",
        "description" : "The assembly must contain parts that have density. The returned schema includes the same information as in the Onshape [Mass Properties Tool](https://cad.onshape.com/help/Content/massprops-asmb.htm). \nWhen three values are returned: \n * The first is the calculated value. \n * The second is the minimum possible value, considering tolerance. \n * The third is the maximum possible value, considering tolerance.",
        "operationId" : "getAssemblyMassProperties",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/assemblies/d/{did}/{wvm}/{wvmid}/e/{eid}/namedpositions" : {
      "get" : {
        "tags" : [ "Assembly" ],
        "summary" : "Get a list of all named positions for the assembly.",
        "operationId" : "getNamedPositions",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/assemblies/d/{did}/{wvm}/{wvmid}/e/{eid}/shadedviews" : {
      "get" : {
        "tags" : [ "Assembly" ],
        "summary" : "Get an array of shaded view images for the document.",
        "operationId" : "getAssemblyShadedViews",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/assemblies/d/{did}/{wv}/{wvid}/e/{eid}/translations" : {
      "post" : {
        "tags" : [ "Assembly" ],
        "summary" : "Export the assembly to another format.",
        "description" : "* Use `formatName` in the JSON request body to specify the export file type. Use [Translations/getAllTranslatorFormats](https://cad.onshape.com/glassworks/explorer/#/Translation/getAllTranslatorFormats) to get a list of valid export file formats. Confirm that `couldBeAssembly=true.`\n* Set `storeInDocument` to `true` to export to a data file. Set to `false` to export to a blob element in the same document. \n* See [API Guide: Model Translation](https://onshape-public.git[...]",
        "operationId" : "translateFormat",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/billing/plans/client/{cid}" : {
      "get" : {
        "tags" : [ "Billing" ],
        "summary" : "Get all billing plans and their information for an application by client ID.",
        "description" : "This API should be used within the context of an OAuth-enabled application.",
        "operationId" : "getClientPlans",
        "deprecated" : false,
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/blobelements/d/{did}/w/{wid}" : {
      "post" : {
        "tags" : [ "BlobElement" ],
        "summary" : "Upload a file and create a blob element from it.",
        "description" : "Request body parameters are multipart fields, so you must use `\"Content-Type\":\"multipart/form-data\"` in the request header.",
        "operationId" : "uploadFileCreateElement",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/blobelements/d/{did}/w/{wid}/e/{eid}" : {
      "get" : {
        "tags" : [ "BlobElement" ],
        "summary" : "Download a file from a blob element for the specified workspace/version/microversion.",
        "description" : "See [API Guide: Model Translation](https://onshape-public.github.io/docs/api-adv/translation/) for more details.",
        "operationId" : "downloadFileWorkspace",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      },
      "post" : {
        "tags" : [ "BlobElement" ],
        "summary" : "Update a blob element by uploading a file.",
        "description" : "Request body parameters are multipart fields, so you must use `\"Content-Type\":\"multipart/form-data\"` in the request header.",
        "operationId" : "uploadFileUpdateElement",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/blobelements/d/{did}/w/{wid}/e/{eid}/units" : {
      "post" : {
        "tags" : [ "BlobElement" ],
        "summary" : "Change the measurement units for the blob element.",
        "operationId" : "updateUnits",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/blobelements/d/{did}/{wv}/{wvid}/e/{eid}/translations" : {
      "post" : {
        "tags" : [ "BlobElement" ],
        "summary" : "Export a blob element to another format.",
        "description" : "* Use `formatName` in the JSON request body to specify the export file type. Use [Translations/getAllTranslatorFormats](https://cad.onshape.com/glassworks/explorer/#/Translation/getAllTranslatorFormats) to get a list of valid export file formats. \n* Set `storeInDocument` to `true` to export to a data file. Set to `false` to export to a blob element in the same document. \n* See [API Guide: Model Translation](https://onshape-public.github.io/docs/api-adv/translation/) fo[...]",
        "operationId" : "createBlobTranslation",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/comments" : {
      "get" : {
        "tags" : [ "Comment" ],
        "summary" : "Get a list of comments in a document.",
        "operationId" : "getComments",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      },
      "post" : {
        "tags" : [ "Comment" ],
        "summary" : "Update a document with a new comment.",
        "operationId" : "createComment",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/comments/{cid}" : {
      "get" : {
        "tags" : [ "Comment" ],
        "summary" : "Get details for a comment.",
        "operationId" : "getComment",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      },
      "post" : {
        "tags" : [ "Comment" ],
        "summary" : "Update the content of an existing comment.",
        "operationId" : "updateComment",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      },
      "delete" : {
        "tags" : [ "Comment" ],
        "summary" : "Delete a comment from a document.",
        "operationId" : "deleteComment",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Delete" ],
          "BasicAuth" : [ "OAuth2Delete" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/comments/{cid}/attachment" : {
      "post" : {
        "tags" : [ "Comment" ],
        "summary" : "Add an attachment to a comment.",
        "operationId" : "addAttachment",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      },
      "delete" : {
        "tags" : [ "Comment" ],
        "summary" : "Delete all attachments from a comment.",
        "operationId" : "deleteAttachments",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Delete" ],
          "BasicAuth" : [ "OAuth2Delete" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/comments/{cid}/attachment/{fdid}.{ext}" : {
      "get" : {
        "tags" : [ "Comment" ],
        "summary" : "Get the attachment with the specified file extension that is associated with the specified comment.",
        "description" : "Returns only a single attachment.",
        "operationId" : "getAttachment",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/comments/{cid}/reopen" : {
      "post" : {
        "tags" : [ "Comment" ],
        "summary" : "Reopen a resolved comment.",
        "operationId" : "reopen",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/comments/{cid}/resolve" : {
      "post" : {
        "tags" : [ "Comment" ],
        "summary" : "Resolve a comment.",
        "operationId" : "resolve",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/companies" : {
      "get" : {
        "tags" : [ "Company" ],
        "summary" : "Get all companies to which the specified user belongs.",
        "description" : "If no user is specified, will return all companies associated with the current user.",
        "operationId" : "findCompany",
        "deprecated" : false,
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/companies/{cid}" : {
      "get" : {
        "tags" : [ "Company" ],
        "summary" : "Get company information by company ID.",
        "operationId" : "getCompany",
        "deprecated" : false,
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/companies/{cid}/documentsbyname" : {
      "get" : {
        "tags" : [ "Company" ],
        "summary" : "Get document by exact document name.",
        "description" : "This API can only be called by company admins. Use the `name` field for the exact document name string.",
        "operationId" : "getDocumentsByName",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/companies/{cid}/users" : {
      "post" : {
        "tags" : [ "Company" ],
        "summary" : "Add a user to a company.",
        "description" : "Returns the company user info.",
        "operationId" : "addUserToCompany",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/companies/{cid}/users/{uid}" : {
      "post" : {
        "tags" : [ "Company" ],
        "summary" : "Update the company's information for a user.",
        "description" : "Returns updated company user info. Global permissions can only be updated by the company admin.",
        "operationId" : "updateCompanyUser",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      },
      "delete" : {
        "tags" : [ "Company" ],
        "summary" : "Remove a user from a company, company teams, and all the direct shares.",
        "operationId" : "removeUserFromCompany",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Delete" ],
          "BasicAuth" : [ "OAuth2Delete" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/documents" : {
      "get" : {
        "tags" : [ "Document" ],
        "summary" : "Get a list of documents that meet the criteria you specify.",
        "operationId" : "getDocuments",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      },
      "post" : {
        "tags" : [ "Document" ],
        "summary" : "Create and upload a document.",
        "description" : "The `name` field is required in the `BTDocumentParams` schema when creating a new document.",
        "operationId" : "createDocument",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/documents/d/{did}/externaldata/{fid}" : {
      "get" : {
        "tags" : [ "Document" ],
        "summary" : "Download external data file(s) associated with the document.",
        "description" : "* See [API Guide: Model Translation](https://onshape-public.github.io/docs/api-adv/translation/) for more details.\n* If downloading an exported file, poll the `requestState` in the translation response and wait for a result of `DONE` before attempting to download the file. \n* Use the `resultExternalDataIds` from the translation response as the foreign id (`{fid}`) in this API.",
        "operationId" : "downloadExternalData",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/documents/d/{did}/versions" : {
      "get" : {
        "tags" : [ "Document" ],
        "summary" : "Retrieve versions by document ID.",
        "operationId" : "getDocumentVersions",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      },
      "post" : {
        "tags" : [ "Document" ],
        "summary" : "Create version by document ID.",
        "operationId" : "createVersion",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/documents/d/{did}/versions/{vid}" : {
      "get" : {
        "tags" : [ "Document" ],
        "summary" : "Retrieve version by document ID and version ID.",
        "operationId" : "getVersion",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/documents/d/{did}/w/{wid}/e/{eid}/latestdocumentreferences" : {
      "post" : {
        "tags" : [ "Document" ],
        "summary" : "Update external references to latest by document ID, workspace ID, and tab ID.",
        "operationId" : "updateExternalReferencesToLatestDocuments",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/documents/d/{did}/w/{wid}/moveelement" : {
      "post" : {
        "tags" : [ "Document" ],
        "summary" : "Move tab by document ID and workspace ID.",
        "operationId" : "moveElementsToDocument",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/documents/d/{did}/w/{wid}/revertunchangedtorevisions" : {
      "post" : {
        "tags" : [ "Document" ],
        "operationId" : "revertUnchangedToRevisions",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/documents/d/{did}/w/{wid}/syncAppElements" : {
      "post" : {
        "tags" : [ "Document" ],
        "operationId" : "syncAppElements",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/documents/d/{did}/workspaces" : {
      "get" : {
        "tags" : [ "Document" ],
        "summary" : "Retrieve workspaces by document ID.",
        "operationId" : "getDocumentWorkspaces",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      },
      "post" : {
        "tags" : [ "Document" ],
        "summary" : "Create workspace by document ID.",
        "operationId" : "createWorkspace",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/documents/d/{did}/workspaces/{wid}" : {
      "delete" : {
        "tags" : [ "Document" ],
        "summary" : "Delete workspace by document ID and workspace ID.",
        "operationId" : "deleteWorkspace",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Delete" ],
          "BasicAuth" : [ "OAuth2Delete" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/documents/d/{did}/{wm}/{wmid}/documenthistory" : {
      "get" : {
        "tags" : [ "Document" ],
        "summary" : "Retrieve document history by document ID and workspace or microversion ID.",
        "operationId" : "getDocumentHistory",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/documents/d/{did}/{wvm}/{wvmid}/elements" : {
      "get" : {
        "tags" : [ "Document" ],
        "summary" : "Retrieve tabs by document ID and workspace or version or microversion ID.",
        "operationId" : "getElementsInDocument",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/documents/d/{did}/{wvm}/{wvmid}/unitinfo" : {
      "get" : {
        "tags" : [ "Document" ],
        "summary" : "Get the selected units and precision by document ID and workspace or version or microversion ID.",
        "operationId" : "getUnitInfo",
        "deprecated" : false,
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/documents/d/{did}/{wv}/{wvid}/currentmicroversion" : {
      "get" : {
        "tags" : [ "Document" ],
        "summary" : "Retrieve current microversion by document ID and workspace or version ID.",
        "operationId" : "getCurrentMicroversion",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/documents/d/{did}/{wv}/{wvid}/e/{eid}/export" : {
      "post" : {
        "tags" : [ "Document" ],
        "summary" : "Export document by document ID, workspace or version ID, and tab ID.",
        "operationId" : "export2Json",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/documents/d/{did}/{wv}/{wvid}/insertables" : {
      "get" : {
        "tags" : [ "Document" ],
        "summary" : "Retrieve insertables by document ID and workspace or version ID.",
        "operationId" : "getInsertables",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/documents/search" : {
      "post" : {
        "tags" : [ "Document" ],
        "summary" : "Search document.",
        "description" : "This returns list of documents based on search parameters.",
        "operationId" : "search",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/documents/{did}" : {
      "get" : {
        "tags" : [ "Document" ],
        "summary" : "Retrieve document by document ID.",
        "operationId" : "getDocument",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      },
      "post" : {
        "tags" : [ "Document" ],
        "summary" : "Update document attributes by document ID.",
        "operationId" : "updateDocumentAttributes",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      },
      "delete" : {
        "tags" : [ "Document" ],
        "summary" : "Delete document by document ID.",
        "operationId" : "deleteDocument",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Delete" ],
          "BasicAuth" : [ "OAuth2Delete" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/documents/{did}/acl" : {
      "get" : {
        "tags" : [ "Document" ],
        "summary" : "Retrieve access control list by document ID.",
        "operationId" : "getDocumentAcl",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/documents/{did}/acl/anonymousAccess" : {
      "post" : {
        "tags" : [ "Document" ],
        "summary" : "Allow or deny anonymous access to a document or publication.",
        "description" : "If anonymous access is allowed, you can allow or deny anonymous users the ability to export the document or publication. If `anonymousAccessAllowed=false` and `anonymousAllowsExport=true`, the call will throw an error.",
        "operationId" : "updateAnonymousAccess",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read", "OAuth2Share" ],
          "BasicAuth" : [ "OAuth2Read", "OAuth2Share" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/documents/{did}/acl/public" : {
      "post" : {
        "tags" : [ "Document" ],
        "summary" : "Make a document public or private.",
        "description" : " * Set `public=true` in the request body to make the document public. Set to `false` to make it private. Free users cannot make documents private. \n * The `documentId` provided in the URL must match the one provided in the request body exactly. ",
        "operationId" : "updatePublicAccess",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read", "OAuth2Share" ],
          "BasicAuth" : [ "OAuth2Read", "OAuth2Share" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/documents/{did}/permissionset" : {
      "get" : {
        "tags" : [ "Document" ],
        "summary" : "Retrieve Document permissions by document ID.",
        "operationId" : "getDocumentPermissionSet",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/documents/{did}/share" : {
      "post" : {
        "tags" : [ "Document" ],
        "summary" : "Share document by document ID.",
        "operationId" : "shareDocument",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read", "OAuth2Share" ],
          "BasicAuth" : [ "OAuth2Read", "OAuth2Share" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/documents/{did}/share/{eid}" : {
      "delete" : {
        "tags" : [ "Document" ],
        "summary" : "Remove document View permissions from a user or other entity.",
        "description" : "Specify the ID of the entity to unshare with in the `eid` field, and specify the type of entity being identified in the `entryType` field. For example, to unshare a document with a company, you would use `1` as the `entryType` value and the `companyId` as the `entityId`.",
        "operationId" : "unShareDocument",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read", "OAuth2Share" ],
          "BasicAuth" : [ "OAuth2Read", "OAuth2Share" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/documents/{did}/shareWithSupport" : {
      "post" : {
        "tags" : [ "Document" ],
        "summary" : "Share document by document ID with Onshape support.",
        "operationId" : "shareWithSupport",
        "deprecated" : false,
        "x-BTVisibility" : "PRODUCTION"
      },
      "delete" : {
        "tags" : [ "Document" ],
        "summary" : "Unshare document with support.",
        "operationId" : "unshareFromSupport",
        "deprecated" : false,
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/documents/{did}/w/{wid}/mergePreview" : {
      "get" : {
        "tags" : [ "Document" ],
        "summary" : "Merge preview of changes that will occur based on document ID, workspace ID and source workspace/version ID",
        "operationId" : "mergePreview",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/documents/{did}/w/{wid}/restore/{vm}/{vmid}" : {
      "post" : {
        "tags" : [ "Document" ],
        "summary" : "Restore version or microversion to workspace by document ID, workspace ID, and version or microversion ID.",
        "operationId" : "restoreFromHistory",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/documents/{did}/workspaces/{wid}/copy" : {
      "post" : {
        "tags" : [ "Document" ],
        "summary" : "Copy workspace by document ID and workspace ID.",
        "operationId" : "copyWorkspace",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/documents/{did}/workspaces/{wid}/merge" : {
      "post" : {
        "tags" : [ "Document" ],
        "summary" : "Merge into workspace by document ID and workspace ID.",
        "operationId" : "mergeIntoWorkspace",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/drawings/d/{did}/w/{wid}/create" : {
      "post" : {
        "tags" : [ "Drawing" ],
        "summary" : "Create a new drawing in a document.",
        "description" : "This endpoint takes a JSON Schema as input. See the schema docs below for details, and see [API Guide: Drawings](https://onshape-public.github.io/docs/api-adv/drawings/) for more information.",
        "operationId" : "createDrawingAppElement",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/drawings/d/{did}/w/{wid}/e/{eid}/modify" : {
      "post" : {
        "tags" : [ "Drawing" ],
        "summary" : "Modify a drawing via JSON payload.",
        "description" : "See [API Guide: Drawings](https://onshape-public.github.io/docs/api-adv/drawings/) for more information.",
        "operationId" : "modifyDrawing",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/drawings/d/{did}/w/{wid}/e/{eid}/translationformats" : {
      "get" : {
        "tags" : [ "Drawing" ],
        "summary" : "Get a list of all valid formats the drawing can be translated (exported) to.",
        "description" : "See [API Guide: Translations](https://onshape-public.github.io/docs/api-adv/translation/#export-a-drawing-as-a-json) for more information.",
        "operationId" : "getDrawingTranslatorFormats",
        "deprecated" : false,
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/drawings/d/{did}/{wvm}/{wvmid}/e/{eid}/views" : {
      "get" : {
        "tags" : [ "Drawing" ],
        "summary" : "Get details of all drawing views.",
        "operationId" : "getDrawingViews_1",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/drawings/d/{did}/{wvm}/{wvmid}/e/{eid}/views/{viewid}/jsongeometry" : {
      "get" : {
        "tags" : [ "Drawing" ],
        "summary" : "Get view geometry of a drawing view in JSON format.",
        "operationId" : "getDrawingViewJsonGeometry_1",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/drawings/d/{did}/{wv}/{wvid}/e/{eid}/translations" : {
      "post" : {
        "tags" : [ "Drawing" ],
        "summary" : "Translate (export) a drawing to a different format.",
        "description" : "Export a drawing to a different format within a document. Use `getDrawingTranslatorFormats` for a list of supported translation (i.e., import/export) formats. See [API Guide: Translations](https://onshape-public.github.io/docs/api-adv/translation/#export-a-drawing-as-a-json) for more information.",
        "operationId" : "createDrawingTranslation",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/drawings/modify/status/{mrid}" : {
      "get" : {
        "tags" : [ "Drawing" ],
        "summary" : "Get the status of a drawing modification operation.",
        "operationId" : "getModificationStatus",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/elements/copyelement/{did}/workspace/{wid}" : {
      "post" : {
        "tags" : [ "Element" ],
        "summary" : "Copy an element from a source document.",
        "description" : "Specify the target document and workspace in the URL. Specify the source document, workspace, and element in the request body. \nIf `anchorElementId` is specified, the copied element will be inserted after the anchor element. If not specified, the copied element will be inserted at the end of the tab list. \n",
        "operationId" : "copyElementFromSourceDocument",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/elements/d/{did}/e/{eid}/configurationencodings" : {
      "post" : {
        "tags" : [ "Element" ],
        "summary" : "Encode a configuration option for use in other API calls.",
        "description" : "Returns a configuration string in the following form: \n`configuration=parameterId%3DparameterValue` \nThe configuration string can be used in other Onshape API calls to specify which configuration option to use. See the [Configuration API Guide](https://onshape-public.github.io/docs/api-adv/configs/) for additional details. \n",
        "operationId" : "encodeConfigurationMap",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/elements/d/{did}/w/{wid}/e/{eid}" : {
      "delete" : {
        "tags" : [ "Element" ],
        "summary" : "Delete an element from a document.",
        "description" : "Attempting to delete the last element in a document will result in an error.",
        "operationId" : "deleteElement",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Delete" ],
          "BasicAuth" : [ "OAuth2Delete" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/elements/d/{did}/w/{wid}/e/{eid}/updatereferences" : {
      "post" : {
        "tags" : [ "Element" ],
        "summary" : "Update or replace references in an element.",
        "operationId" : "updateReferences",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read", "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Read", "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/elements/d/{did}/{wvm}/{wvmid}/e/{eid}/configuration" : {
      "get" : {
        "tags" : [ "Element" ],
        "summary" : "Get the configuration definition for a Part Studio or Assembly.",
        "description" : "Use Configurations to create variations of elements. You can configure feature and parameter values, part properties, custom part properties, face and part appearances, and sketch text. Each Part Studio can have only one Configuration, but it can contain multiple Configuration inputs. \nSee the [Configuration API Guide](https://onshape-public.github.io/docs/api-adv/configs/) for additional details. ",
        "operationId" : "getConfiguration",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      },
      "post" : {
        "tags" : [ "Element" ],
        "summary" : "Update the configuration definition for a Part Studio or Assembly.",
        "description" : "See the [Configuration API Guide](https://onshape-public.github.io/docs/api-adv/configs/) for additional details",
        "operationId" : "updateConfiguration",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/elements/d/{did}/{wvm}/{wvmid}/e/{eid}/configurationencodings/{cid}" : {
      "get" : {
        "tags" : [ "Element" ],
        "summary" : "Decode a configuration string.",
        "description" : "Decode a configuration string into its original JSON form to obtain configuration parameter ID and value. See the [Configuration API Guide](https://onshape-public.github.io/docs/api-adv/configs/) for additional details.  ",
        "operationId" : "decodeConfiguration",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/elements/translatorFormats/{did}/{wv}/{wvid}/{eid}" : {
      "get" : {
        "tags" : [ "Element" ],
        "summary" : "Gets the list of formats an element can be translated to or from.",
        "description" : "See the [Translation API Guide](https://onshape-public.github.io/docs/api-adv/translation/) for additional details. ",
        "operationId" : "getElementTranslatorFormatsByVersionOrWorkspace",
        "deprecated" : false,
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/exportrules/options/{cu}/{cuid}" : {
      "get" : {
        "tags" : [ "ExportRule" ],
        "summary" : " Get a list of valid export rule options for the user or company.",
        "description" : "Does NOT get the rules themselves; it gets the information used to create them.",
        "operationId" : "getValidRuleOptions",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/featurestudios/d/{did}/w/{wid}" : {
      "post" : {
        "tags" : [ "FeatureStudio" ],
        "summary" : "Create a new Feature Studio tab in a document.",
        "description" : "Specify the name for the new tab in the request body.",
        "operationId" : "createFeatureStudio",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/featurestudios/d/{did}/{wvm}/{wvmid}/e/{eid}" : {
      "get" : {
        "tags" : [ "FeatureStudio" ],
        "summary" : "Get the text for a Feature Studio element.",
        "operationId" : "getFeatureStudioContents",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      },
      "post" : {
        "tags" : [ "FeatureStudio" ],
        "summary" : "Update the text for a Feature Studio element.",
        "operationId" : "updateFeatureStudioContents",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/featurestudios/d/{did}/{wvm}/{wvmid}/e/{eid}/featurespecs" : {
      "get" : {
        "tags" : [ "FeatureStudio" ],
        "summary" : "Get the feature specs for a Feature Studio element.",
        "operationId" : "getFeatureStudioSpecs",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/folders/{fid}/acl" : {
      "get" : {
        "tags" : [ "Folder" ],
        "summary" : "Get the Access Control List (ACL) for a folder to view permissions.",
        "description" : "Returns the ACL of permission objects. Each object contains: \n* The type of entity  \n    * 0 (User)  \n    * 1 (Company) \n    * 2 (Team) \n    * 3 (Document) \n    * 4 (Application) \n * The ID of the entity for the specified type. \n* The permissions for that entity. \n    *  OWNER (100): All permissions, including those not listed, such as permission to transfer ownership. \n    * DELETE (90) \n    * RESHARE (80) \n    * WRITE (70) \n    * READ (60) \n    * LINK (50[...]",
        "operationId" : "getFolderAcl",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/folders/{fid}/share" : {
      "post" : {
        "tags" : [ "Folder" ],
        "summary" : "Share folder with an entity.",
        "description" : "* Specify the type of entity to share with using `entries.entryType`: \n    * 0 (User)  \n    * 1 (Company) \n    * 2 (Team) \n    * 3 (Document) \n    * 4 (Application) \n* Provide one of the identifiers in the `entries` object in the request body.  \n    * You can share with non-Onshape users with the `email` field when `entryType=0`.  \n * Provide the string for the permission set. Do not include the integer in parentheses: \n    * OWNER (100): Object owner. Implies a[...]",
        "operationId" : "share",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read", "OAuth2Share" ],
          "BasicAuth" : [ "OAuth2Read", "OAuth2Share" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/folders/{fid}/share/{eid}" : {
      "delete" : {
        "tags" : [ "Folder" ],
        "summary" : "Remove permissions from the folder for the specified Access Control List (ACL) entry.",
        "description" : "* Provide the folder ID for the folder to unshare.  \n * Provide the `entityType` for the type of entity to remove. \n    * 0 (User)  \n    * 1 (Company) \n    * 2 (Team) \n    * 3 (Document) \n    * 4 (Application) \n* Provide the entity ID in the `eid` param.",
        "operationId" : "unShare",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read", "OAuth2Share" ],
          "BasicAuth" : [ "OAuth2Read", "OAuth2Share" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/insertables/d/{did}/latest" : {
      "get" : {
        "tags" : [ "Insertable" ],
        "summary" : "Get a list of things in this document that can be inserted elsewhere.",
        "description" : "* Returns only the latest revision of released insertables. \n* Use the document ID (`did`) parameter to specify the source document, not the insertion target. \n* For example, you can insert a custom Feature library into another custom Feature library, insert Parts into an Assembly or a Drawing, etc.",
        "operationId" : "getLatestInDocument",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/metadata/d/{did}/{wvm}/{wvmid}/e" : {
      "get" : {
        "tags" : [ "Metadata" ],
        "summary" : "Get the metadata for all elements in a document.",
        "description" : "See [API Guide: Metadata](https://onshape-public.github.io/docs/api-adv/metadata/) for details. \n* You can specify the optional `depth` query parameter to get multiple levels in an assembly. Default `depth` is `1`. \n* `linkDocumentId` can be specified where applicable. Combined with `inferMetadataOwner` (default value is `false`), this is used to infer metadata owner. \n* `includeComputedProperties` can be used to include or omit computed properties. Default value is `[...]",
        "operationId" : "getWMVEsMetadata",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/metadata/d/{did}/{wvm}/{wvmid}/e/{eid}" : {
      "get" : {
        "tags" : [ "Metadata" ],
        "summary" : "Get the metadata for an element.",
        "description" : "See [API Guide: Metadata](https://onshape-public.github.io/docs/api-adv/metadata/) for details. \n* `linkDocumentId` can be specified where applicable and this combined with the query param `inferMetadataOwner` (default value is `false`) will be used to infer metadata owner. \n* `configuration` optional query parameter defaults to default configuration. \n* You can specify an optional `depth` query parameter to get multiple levels in an assembly. Default `depth` is `1`. [...]",
        "operationId" : "getWMVEMetadata",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      },
      "post" : {
        "tags" : [ "Metadata" ],
        "summary" : "Update the metadata for an element.",
        "description" : "See [API Guide: Metadata](https://onshape-public.github.io/docs/api-adv/metadata/) for details. \n* Microversion (`m`) in `wvm` path parameter option is not supported. \n* Specify the property metadata to update in the Request body.",
        "operationId" : "updateWVEMetadata",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/metadata/d/{did}/{wvm}/{wvmid}/e/{eid}/assembly-debug" : {
      "get" : {
        "tags" : [ "Metadata" ],
        "summary" : "Get the metadata for an assembly, including supporting metadata.",
        "description" : "See [API Guide: Metadata](https://onshape-public.github.io/docs/api-adv/metadata/) for details. \n* `linkDocumentId` can be specified where applicable and this combined with the query param `inferMetadataOwner` (default value is `false`) will be used to infer metadata owner. \n* `configuration` optional query parameter defaults to default configuration. \n* `includeComputedProperties` can be used to include or omit computed properties. Default value is `true`. \n* `inclu[...]",
        "operationId" : "getFullAssemblyMetadata",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/metadata/d/{did}/{wvm}/{wvmid}/e/{eid}/p" : {
      "get" : {
        "tags" : [ "Metadata" ],
        "summary" : "Get the metadata for all parts in a document.",
        "description" : "See [API Guide: Metadata](https://onshape-public.github.io/docs/api-adv/metadata/) for details. \n* The `configuration` optional query parameter uses the default configuration unless otherwise specified. \n* You can specify an optional `depth` query parameter to get multiple levels in an assembly. Default `depth` is `1`. \n* `linkDocumentId` can be specified where applicable. Combined with `inferMetadataOwner` (default value is `false`), this is used to infer metadata ow[...]",
        "operationId" : "getWMVEPsMetadata",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/metadata/d/{did}/{wvm}/{wvmid}/e/{eid}/{iden}/{pid}" : {
      "get" : {
        "tags" : [ "Metadata" ],
        "summary" : "Get the metadata for a part.",
        "description" : "See [API Guide: Metadata](https://onshape-public.github.io/docs/api-adv/metadata/) for details. \n* Specify the part in the `iden` or `pid` path parameter. \n* The `configuration` optional query parameter uses the default configuration unless otherwise specified. \n* `linkDocumentId` can be specified where applicable. Combined with `inferMetadataOwner` (default value is `false`), this is used to infer metadata owner. \n* `includeComputedProperties` can be used to include[...]",
        "operationId" : "getWMVEPMetadata",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      },
      "post" : {
        "tags" : [ "Metadata" ],
        "summary" : "Update the metadata for a part.",
        "description" : "See [API Guide: Metadata](https://onshape-public.github.io/docs/api-adv/metadata/) for details. \n* Specify the part in the `iden` or `pid` path parameter. \n* The `configuration` optional query parameter uses the default configuration unless otherwise specified. \n* `linkDocumentId` can be specified where applicable. Combined with `inferMetadataOwner` (default value is `false`), this is used to infer metadata owner. \n* Specify the property metadata to update in the Req[...]",
        "operationId" : "updateWVEPMetadata",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/metadata/d/{did}/{wv}/{wvid}" : {
      "get" : {
        "tags" : [ "Metadata" ],
        "summary" : "Get the metadata for a workspace or version.",
        "description" : "See [API Guide: Metadata](https://onshape-public.github.io/docs/api-adv/metadata/) for details. \n* `linkDocumentId` can be specified where applicable. Combined with `inferMetadataOwner` (default value is `false`), this is used to infer metadata owner. \n* You can specify an optional `depth` query parameter to get multiple levels in an assembly. Default `depth` is `1`. \n* `includeComputedProperties` can be used to include or omit computed properties. Default value is `t[...]",
        "operationId" : "getWVMetadata",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      },
      "post" : {
        "tags" : [ "Metadata" ],
        "summary" : "Update the metadata for a workspace or version.",
        "description" : "See [API Guide: Metadata](https://onshape-public.github.io/docs/api-adv/metadata/) for details.",
        "operationId" : "updateWVMetadata",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/metadata/standardcontent/d/{did}" : {
      "post" : {
        "tags" : [ "Metadata" ],
        "summary" : "Update the metadata for a standard content part.",
        "description" : "See [API Guide: Metadata](https://onshape-public.github.io/docs/api-adv/metadata/) for details. \n* Specify the document ID to update in the `did` path param. \n* Specify the document in which you have inserted the standard content part in the `linkDocumentId` query param. \n* Specify the property metadata to update in the Request body.",
        "operationId" : "updateVEOPStandardContentPartMetadata",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/metadata/standardcontent/d/{did}/v/{vid}/e/{eid}/p/{pid}" : {
      "get" : {
        "tags" : [ "Metadata" ],
        "summary" : "Get the metadata for a standard content part.",
        "description" : "See [API Guide: Metadata](https://onshape-public.github.io/docs/api-adv/metadata/) for details. \n* Specify the part in the `pid` path parameter. \n* The `configuration` and `linkDocumentId` query parameters are required. \n* `includeComputedProperties` can be used to include or omit computed properties. Default value is `true`. \n* `includeComputedAssemblyProperties` can be used to query computed assembly properties which are generally expensive. Default value is `false[...]",
        "operationId" : "getVEOPStandardContentMetadata",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/metadatacategory/categoryproperties" : {
      "get" : {
        "tags" : [ "MetadataCategory" ],
        "summary" : "Get properties associated with the specified metadata categories.",
        "description" : "An object's category specifies its type: Part, Assembly, Drawing, etc. Available properties depend on the object's category.",
        "operationId" : "getCategoryProperties",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/numberingscheme/nextnumbers" : {
      "post" : {
        "tags" : [ "NumberingScheme" ],
        "summary" : "Send the items to generate numbers for, and return the next valid available part numbers.",
        "operationId" : "nextNumbers",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/openapi" : {
      "get" : {
        "tags" : [ "OpenApi" ],
        "summary" : "Get the OpenAPI specification for the Onshape REST API.",
        "description" : "The Onshape API OpenAPI specification is returned in the JSON format.",
        "operationId" : "getOpenApi",
        "parameters" : [ {
          "name" : "forceReload",
          "in" : "query",
          "description" : "Force reload the OpenApi definition. Only works when asking for the latest version.",
          "schema" : {
            "type" : "boolean"
          }
        }, {
          "name" : "version",
          "in" : "query",
          "description" : "Specify a version of Onshape from which the OpenAPI is generated. If '*' is specified in any of the version fields, that indicates any version if acceptable.",
          "schema" : {
            "type" : "string"
          }
        }, {
          "name" : "versionAlias",
          "in" : "query",
          "description" : "Version aliases based on the currently released version.",
          "schema" : {
            "$ref" : "#/components/schemas/VersionAlias"
          }
        }, {
          "name" : "noFilter",
          "in" : "query",
          "description" : "Do not filter the specification at all.",
          "schema" : {
            "type" : "boolean",
            "default" : false
          }
        }, {
          "name" : "includedTags",
          "in" : "query",
          "description" : "Return only operations with tags included in includedTags.",
          "schema" : {
            "type" : "array",
            "items" : {
              "type" : "string"
            }
          }
        }, {
          "name" : "excludedTags",
          "in" : "query",
          "description" : "If an operation contains an excluded tag, it is not returned from this endpoint.",
          "schema" : {
            "type" : "array",
            "items" : {
              "type" : "string"
            }
          }
        }, {
          "name" : "includeDeprecated",
          "in" : "query",
          "description" : "Include deprecated endpoints.",
          "schema" : {
            "type" : "boolean",
            "default" : false
          }
        }, {
          "name" : "onlyDeprecated",
          "in" : "query",
          "description" : "Only include deprecated endpoints.",
          "schema" : {
            "type" : "boolean",
            "default" : false
          }
        }, {
          "name" : "documentationStatuses",
          "in" : "query",
          "description" : "Only return endpoints that have the specified documentation status. Default is to return all the endpoints the user should have access to.",
          "schema" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/Status"
            }
          }
        }, {
          "name" : "restUserRole",
          "in" : "query",
          "description" : "The REST user role for which this spec is requested.",
          "schema" : {
            "$ref" : "#/components/schemas/BTRestUserRole"
          }
        }, {
          "name" : "operationIds",
          "in" : "query",
          "description" : "Only return operations with specified ids.",
          "schema" : {
            "type" : "array",
            "items" : {
              "type" : "string"
            }
          }
        }, {
          "name" : "excludedOperationIds",
          "in" : "query",
          "description" : "Do not return operations with specified ids.",
          "schema" : {
            "type" : "array",
            "items" : {
              "type" : "string"
            }
          }
        } ],
        "deprecated" : false,
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/openapi/tags" : {
      "get" : {
        "tags" : [ "OpenApi" ],
        "summary" : "Get the list of tags in the Onshape OpenAPI specification.",
        "description" : "Tags are used to group operations. For example, `Document` groups operations on documents.",
        "operationId" : "getTags",
        "deprecated" : false,
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/partnumber/nextnumbers" : {
      "post" : {
        "tags" : [ "PartNumber" ],
        "summary" : "Send the items to generate numbers for, and return the next valid available part numbers.",
        "operationId" : "updateNextNumbers",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/parts/d/{did}/{wvm}/{wvmid}" : {
      "get" : {
        "tags" : [ "Part" ],
        "summary" : "Get all parts in a workspace, version, or microversion.",
        "operationId" : "getPartsWMV",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/parts/d/{did}/{wvm}/{wvmid}/e/{eid}" : {
      "get" : {
        "tags" : [ "Part" ],
        "summary" : "Get all parts in an element.",
        "operationId" : "getPartsWMVE",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/parts/d/{did}/{wvm}/{wvmid}/e/{eid}/partid/{partid}/bodydetails" : {
      "get" : {
        "tags" : [ "Part" ],
        "summary" : "Get a part's body details.",
        "description" : "All coordinates are in meters (m).",
        "operationId" : "getBodyDetails",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/parts/d/{did}/{wvm}/{wvmid}/e/{eid}/partid/{partid}/boundingboxes" : {
      "get" : {
        "tags" : [ "Part" ],
        "summary" : "Get a part's bounding box details.",
        "operationId" : "getBoundingBoxes",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/parts/d/{did}/{wvm}/{wvmid}/e/{eid}/partid/{partid}/gltf" : {
      "get" : {
        "tags" : [ "Part" ],
        "summary" : "Export a part as a glTF file.",
        "description" : "Returns a 307 redirect from which to download the exported file. See [API Guide: Model Translation](https://onshape-public.github.io/docs/api-adv/translation/) for more details.",
        "operationId" : "exportPartGltf",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/parts/d/{did}/{wvm}/{wvmid}/e/{eid}/partid/{partid}/massproperties" : {
      "get" : {
        "tags" : [ "Part" ],
        "summary" : "Get a part's mass properties.",
        "description" : "Parts must have density. The returned schema includes the same information as in the Onshape [Mass Properties Tool](https://cad.onshape.com/help/Content/massprops-ps.htm). \nWhen three values are returned: \n * The first is the calculated value. \n * The second is the minimum possible value, considering tolerance. \n * The third is the maximum possible value, considering tolerance.",
        "operationId" : "getMassProperties",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/parts/d/{did}/{wvm}/{wvmid}/e/{eid}/partid/{partid}/parasolid" : {
      "get" : {
        "tags" : [ "Part" ],
        "summary" : "Export a part as a Parasolid file.",
        "description" : "Returns a 307 redirect from which to download the exported file. See [API Guide: Model Translation](https://onshape-public.github.io/docs/api-adv/translation/) for more details.",
        "operationId" : "exportPS",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/parts/d/{did}/{wvm}/{wvmid}/e/{eid}/partid/{partid}/shadedviews" : {
      "get" : {
        "tags" : [ "Part" ],
        "summary" : "Get a part's shaded views.",
        "operationId" : "getPartShadedViews",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/parts/d/{did}/{wvm}/{wvmid}/e/{eid}/partid/{partid}/sheetmetal/bendtable" : {
      "get" : {
        "tags" : [ "Part" ],
        "summary" : "Get a part's sheet metal bend table.",
        "operationId" : "getBendTable",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/parts/d/{did}/{wvm}/{wvmid}/e/{eid}/partid/{partid}/stl" : {
      "get" : {
        "tags" : [ "Part" ],
        "summary" : "Export a part as an STL file.",
        "description" : "Returns a 307 redirect from which to download the exported file. See [API Guide: Model Translation](https://onshape-public.github.io/docs/api-adv/translation/) for more details.",
        "operationId" : "exportStl",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/parts/d/{did}/{wvm}/{wvmid}/e/{eid}/partid/{partid}/tessellatededges" : {
      "get" : {
        "tags" : [ "Part" ],
        "summary" : "Get a list of a part's tessellation edges.",
        "description" : "Returns the coordinates (in meters) of each edge's endpoints.",
        "operationId" : "getEdges",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/parts/d/{did}/{wvm}/{wvmid}/e/{eid}/partid/{partid}/tessellatedfaces" : {
      "get" : {
        "tags" : [ "Part" ],
        "summary" : "Get a list of a part's tessellation faces.",
        "description" : "Coordinates are in meters (m).",
        "operationId" : "getFaces_1",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/partstudios/d/{did}/e/{eid}/namedViews" : {
      "get" : {
        "tags" : [ "PartStudio" ],
        "summary" : "Get a list of all named views that exist in the Part Studio.",
        "description" : "Returns a map from view name to view data for the given element. See the [Part Studios API Guide](https://onshape-public.github.io/docs/api-adv/partstudios/) for details and tutorials.",
        "operationId" : "getPartStudioNamedViews",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/partstudios/d/{did}/w/{wid}" : {
      "post" : {
        "tags" : [ "PartStudio" ],
        "summary" : "Create a new Part Studio in a document.",
        "description" : "See the [Part Studios API Guide](https://onshape-public.github.io/docs/api-adv/partstudios/) for details and tutorials.",
        "operationId" : "createPartStudio",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/partstudios/d/{did}/w/{wid}/e/{eid}/features/featureid/{fid}" : {
      "post" : {
        "tags" : [ "PartStudio" ],
        "summary" : "Update the definition of a Part Studio feature.",
        "description" : "Replaces an existing feature in the location of the existing feature. See the [Features API Guide](https://onshape-public.github.io/docs/api-adv/featureaccess/) for additional information.",
        "operationId" : "updatePartStudioFeature",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      },
      "delete" : {
        "tags" : [ "PartStudio" ],
        "summary" : "Delete a Part Studio feature.",
        "description" : "See the [Features API Guide](https://onshape-public.github.io/docs/api-adv/featureaccess/) for additional information.",
        "operationId" : "deletePartStudioFeature",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/partstudios/d/{did}/w/{wid}/e/{eid}/features/rollback" : {
      "post" : {
        "tags" : [ "PartStudio" ],
        "summary" : "Move the Feature List rollback bar in the Part Studio.",
        "description" : "Replace `\"string\"` in the request body with an object that specifies the new location for the rollback bar: \n `{ \"rollbackIndex\": integer }` \n\nFor example: `{ \"rollbackIndex\": 2 }` \n\nSet to `-1` to move the rollback bar to the end of the list. \n\nSee the [Part Studios API Guide](https://onshape-public.github.io/docs/api-adv/partstudios/) for details and tutorials.",
        "operationId" : "updateRollback",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/partstudios/d/{did}/w/{wid}/e/{eid}/features/updates" : {
      "post" : {
        "tags" : [ "PartStudio" ],
        "summary" : "Update multiple features in a Part Studio",
        "description" : "This API accepts a list of features (that must already exist in the Part Studio) to update. This call does not fully redefine the features; it updates only the parameters supplied in the top-level feature structure, and optionally can update feature suppression attributes. \nSee the [Features API Guide](https://onshape-public.github.io/docs/api-adv/featureaccess/) for additional information.",
        "operationId" : "updateFeatures",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/bodydetails" : {
      "get" : {
        "tags" : [ "PartStudio" ],
        "summary" : "Get the body details for a Part Studio.",
        "description" : "See the [Part Studios API Guide](https://onshape-public.github.io/docs/api-adv/partstudios/) for details and tutorials.",
        "operationId" : "getPartStudioBodyDetails",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/boundingboxes" : {
      "get" : {
        "tags" : [ "PartStudio" ],
        "summary" : "Get the bounding boxes for a Part Studio.",
        "description" : "This endpoint does not result in a tight bounding box. The values returned are meant for graphics and visualization, and are approximate. \nTo calculate a tight bounding box, see the [FeatureScript API Guide](https://onshape-public.github.io/docs/api-adv/fs/#calculate-a-tight-bounding-box). ",
        "operationId" : "getPartStudioBoundingBoxes",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/compare" : {
      "get" : {
        "tags" : [ "PartStudio" ],
        "summary" : "Get the differences between two Part Studios in a single document.",
        "operationId" : "comparePartStudios",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/features" : {
      "get" : {
        "tags" : [ "PartStudio" ],
        "summary" : "Get a list of features instantiated in the Part Studio.",
        "description" : "See the [Features API Guide](https://onshape-public.github.io/docs/api-adv/featureaccess/) for additional information.",
        "operationId" : "getPartStudioFeatures",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      },
      "post" : {
        "tags" : [ "PartStudio" ],
        "summary" : "Add a feature to the Part Studio's Feature List.",
        "description" : "The feature is added immediately before the rollback bar. Any geometry IDs specified in the feature must be valid at that point in the feature tree. \n \nSee the [Features API Guide](https://onshape-public.github.io/docs/api-adv/featureaccess/) for additional information.",
        "operationId" : "addPartStudioFeature",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/featurescript" : {
      "post" : {
        "tags" : [ "PartStudio" ],
        "summary" : "Evaluate the FeatureScript snippet for a Part Studio.",
        "operationId" : "evalFeatureScript",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/featurescriptrepresentation" : {
      "get" : {
        "tags" : [ "PartStudio" ],
        "summary" : "Get the FeatureScript representation of a Part Studio.",
        "operationId" : "getFeatureScriptRepresentation",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/featurespecs" : {
      "get" : {
        "tags" : [ "PartStudio" ],
        "summary" : "Get the specs for a Part Studio feature.",
        "description" : "Returns a list of feature specs available within the Part Studio. A feature spec provides a data description of the feature's interface to a feature.",
        "operationId" : "getPartStudioFeatureSpecs",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/fstable" : {
      "get" : {
        "tags" : [ "PartStudio" ],
        "summary" : "Compute and return a FeatureScript table for a Part Studio.",
        "operationId" : "getFeatureScriptTable",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/gltf" : {
      "get" : {
        "tags" : [ "PartStudio" ],
        "summary" : "Export the Part Studio as a glTF file.",
        "description" : "Returns the glTF representation. See [API Guide: Model Translation](https://onshape-public.github.io/docs/api-adv/translation/)",
        "operationId" : "exportPartStudioGltf",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/idtranslations" : {
      "post" : {
        "tags" : [ "PartStudio" ],
        "summary" : "Find corresponding deterministic IDs from a source document microversion at the target version.",
        "description" : "* Deterministic IDs are only valid for one microversion. \n* This maps deterministic IDs between microversions in an attempt to find the corresponding entities in each version.",
        "operationId" : "translateIds",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/massproperties" : {
      "get" : {
        "tags" : [ "PartStudio" ],
        "summary" : "Get the mass properties for a Part Studio.",
        "description" : "Parts must have density. The returned schema includes the same information as in the Onshape [Mass Properties Tool](https://cad.onshape.com/help/Content/massprops-ps.htm). \n \nWhen three values are returned: \n * The first is the calculated value. \n * The second is the minimum possible value, considering tolerance. \n * The third is the maximum possible value, considering tolerance. \n \n See the [Part Studios API Guide](https://onshape-public.github.io/docs/api-adv/pa[...]",
        "operationId" : "getPartStudioMassProperties",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/parasolid" : {
      "get" : {
        "tags" : [ "PartStudio" ],
        "summary" : "Export the Part Studio as a Parasolid file.",
        "description" : "Returns a 307 redirect from which to download the exported file. See [API Guide: Model Translation](https://onshape-public.github.io/docs/api-adv/translation/) for more details.",
        "operationId" : "exportParasolid",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/shadedviews" : {
      "get" : {
        "tags" : [ "PartStudio" ],
        "summary" : "Get a list of shaded views for a Part Studio.",
        "operationId" : "getPartStudioShadedViews",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/sketches" : {
      "get" : {
        "tags" : [ "Sketch" ],
        "summary" : "Get information for all sketches in Part Studio.",
        "operationId" : "getSketchInfo",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/sketches/{sid}/boundingboxes" : {
      "get" : {
        "tags" : [ "Sketch" ],
        "summary" : "Get all bounding boxes for a sketch.",
        "operationId" : "getSketchBoundingBoxes",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/sketches/{sid}/tessellatedentities" : {
      "get" : {
        "tags" : [ "Sketch" ],
        "summary" : "Get the tessellations of a sketch in a Part Studio.",
        "description" : "The accuracy of the tessellation to exact geometry is controlled by the `angleTolerance` and `chordTolerance` parameters. The tessellation points are computed closely enough so that neither the angle tolerance nor the chord tolerance are exceeded. For most parts, the angular tolerance is the most restrictive of the two default tolerances.",
        "operationId" : "getTessellatedEntities",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/stl" : {
      "get" : {
        "tags" : [ "PartStudio" ],
        "summary" : "Export the Part Studio as an STL file.",
        "description" : "Returns a 307 redirect from which to download the exported file. See [API Guide: Model Translation](https://onshape-public.github.io/docs/api-adv/translation/)",
        "operationId" : "exportPartStudioStl",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/tessellatededges" : {
      "get" : {
        "tags" : [ "PartStudio" ],
        "summary" : "Get a list of all edges in a Part Studio.",
        "description" : "Returns the edges as tessellated data and includes display data. \nCoordinates are in meters (m).",
        "operationId" : "getPartStudioEdges",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/partstudios/d/{did}/{wvm}/{wvmid}/e/{eid}/tessellatedfaces" : {
      "get" : {
        "tags" : [ "PartStudio" ],
        "summary" : "Get a list of all faces in a Part Studio.",
        "description" : "Coordinates are in meters (m).",
        "operationId" : "getPartStudioFaces",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/partstudios/d/{did}/{wv}/{wvid}/e/{eid}/translations" : {
      "post" : {
        "tags" : [ "PartStudio" ],
        "summary" : "Export a Part Studio to another format.",
        "description" : "* Use `formatName` in the JSON request body to specify the export file type. Use [Translations/getAllTranslatorFormats](https://cad.onshape.com/glassworks/explorer/#/Translation/getAllTranslatorFormats) to get a list of valid export file formats. `\n* Set `storeInDocument` to `true` to export to a data file. Set to `false` to export to a blob element in the same document. \n* See [API Guide: Model Translation](https://onshape-public.github.io/docs/api-adv/translation/) f[...]",
        "operationId" : "createPartStudioTranslation",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/publications" : {
      "post" : {
        "tags" : [ "Publication" ],
        "summary" : "Create a new publication.",
        "operationId" : "createPublication",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/publications/{pid}" : {
      "post" : {
        "tags" : [ "Publication" ],
        "summary" : "Update publication's attributes name, description, and notes.",
        "operationId" : "updatePublicationAttributes",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      },
      "delete" : {
        "tags" : [ "Publication" ],
        "summary" : "Delete a publication.",
        "operationId" : "deletePublication",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Delete" ],
          "BasicAuth" : [ "OAuth2Delete" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/publications/{pid}/item" : {
      "post" : {
        "tags" : [ "Publication" ],
        "summary" : "Add an item in a publication.",
        "operationId" : "addItemToPublication",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/publications/{pid}/item/{iid}" : {
      "delete" : {
        "tags" : [ "Publication" ],
        "summary" : "Remove an item from a publication.",
        "operationId" : "deletePublicationItem",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/publications/{pid}/items" : {
      "get" : {
        "tags" : [ "Publication" ],
        "summary" : "Get all items in a publication.",
        "operationId" : "getPublicationItems",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      },
      "post" : {
        "tags" : [ "Publication" ],
        "summary" : "Add publication items in bulk.",
        "operationId" : "addItemsToPublication",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/releasepackages/companyreleaseworkflow" : {
      "get" : {
        "tags" : [ "ReleasePackage" ],
        "summary" : "Get information about the release/obsoletion workflow for a company-owned document.",
        "operationId" : "getCompanyReleaseWorkflow",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/releasepackages/obsoletion/{wfid}" : {
      "post" : {
        "tags" : [ "ReleasePackage" ],
        "summary" : "Create an obsoletion package to make an existing revision obsolete.",
        "operationId" : "createObsoletionPackage",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/releasepackages/release/{wfid}" : {
      "post" : {
        "tags" : [ "ReleasePackage" ],
        "summary" : "Create a new release package for one or more items.",
        "description" : "All revisionable items must be from the same document. Once a release package is successfully created, use `updateReleasePackage` to update all desired item/package properties, and transition it to the desired state.",
        "operationId" : "createReleasePackage",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/releasepackages/{rpid}" : {
      "get" : {
        "tags" : [ "ReleasePackage" ],
        "summary" : "Get details about the specified release package.",
        "operationId" : "getReleasePackage",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      },
      "post" : {
        "tags" : [ "ReleasePackage" ],
        "summary" : "Update the release/obsoletion package/item properties.",
        "description" : "Use the `wfaction` query param to also perform a workflow transition.",
        "operationId" : "updateReleasePackage",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/revisions/c/{cid}/partnumber/{pnum}" : {
      "get" : {
        "tags" : [ "Revision" ],
        "summary" : "Get a list of revisions by part number.",
        "operationId" : "getRevisionByPartNumber",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/revisions/companies/{cid}" : {
      "get" : {
        "tags" : [ "Revision" ],
        "summary" : "Enumerate all of a company's revisions.",
        "description" : "* Returns a slice of all revisions per API call. \n* To get the next set of results, use the `next` URL from the response body. \n* This API can only be called by company admins.",
        "operationId" : "enumerateRevisions",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/revisions/companies/{cid}/d/{did}/{wv}/{wvid}/e/{eid}" : {
      "get" : {
        "tags" : [ "Revision" ],
        "summary" : "Get a list of all revisions for an element in a company-owned document.",
        "operationId" : "getRevisionHistoryInCompanyByElementId",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/revisions/companies/{cid}/d/{did}/{wv}/{wvid}/e/{eid}/p/{pid}" : {
      "get" : {
        "tags" : [ "Revision" ],
        "summary" : "Get a list of all revisions for a part in a company-owned document by part ID.",
        "operationId" : "getRevisionHistoryInCompanyByPartId",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/revisions/companies/{cid}/partnumber/{pnum}" : {
      "get" : {
        "tags" : [ "Revision" ],
        "summary" : "Get a list of all revisions for a part or element in a company-owned document by part number.",
        "description" : "You can also request `elementType` in addition to `partNumber` since companies may or may not allow drawings to share part numbers with their parts/assemblies. To perform search without `elementType`, use `elementType` = -1 | UNKNOWN. Available element types are: -1: Unknown, 0: Part Studio, 1: Assembly, 2: Drawing, 4: Blob, 5: Application, 8: Variable Studio 10: Unknown",
        "operationId" : "getRevisionHistoryInCompanyByPartNumber",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/revisions/companies/{cid}/partnumber/{pnum}/elementType/{et}" : {
      "delete" : {
        "tags" : [ "Revision" ],
        "summary" : "Delete all revisions for a part number.",
        "description" : "Only company admins can call this API. All documents that contain or use the part number must be deleted first. This operation cannot be undone.",
        "operationId" : "deleteRevisionHistory",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Delete" ],
          "BasicAuth" : [ "OAuth2Delete" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/revisions/d/{did}" : {
      "get" : {
        "tags" : [ "Revision" ],
        "summary" : "Get all revisions for the specified document.",
        "description" : "Retrieve a list of all revisions that exist in a document and are owned by the document's owning company.",
        "operationId" : "getAllInDocument",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/revisions/d/{did}/v/{vid}" : {
      "get" : {
        "tags" : [ "Revision" ],
        "summary" : "Get all revisions for a version.",
        "description" : "Retrieve a list of all revisions that exist in a document version and are owned by the document's owning company.",
        "operationId" : "getAllInDocumentVersion",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/revisions/{cd}/{cdid}/p/{pnum}/latest" : {
      "get" : {
        "tags" : [ "Revision" ],
        "summary" : "Get the latest revision for a part number in a document or company.",
        "description" : "Returns 204 if no revisions are found.",
        "operationId" : "getLatestInDocumentOrCompany",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/tabletemplates" : {
      "post" : {
        "tags" : [ "PropertiesTableTemplate" ],
        "summary" : "Create a new properties table template.",
        "operationId" : "createTableTemplate",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/tabletemplates/companies/{cid}" : {
      "get" : {
        "tags" : [ "PropertiesTableTemplate" ],
        "summary" : "Get all properties table templates available for a company.",
        "operationId" : "getByCompanyId",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/tabletemplates/d/{did}" : {
      "get" : {
        "tags" : [ "PropertiesTableTemplate" ],
        "summary" : "Get all table templates that are available to use on the provided document.",
        "operationId" : "getByDocumentId",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/tabletemplates/{tid}" : {
      "get" : {
        "tags" : [ "PropertiesTableTemplate" ],
        "summary" : "Get a properties table template by template ID.",
        "operationId" : "getTableTemplate",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      },
      "delete" : {
        "tags" : [ "PropertiesTableTemplate" ],
        "summary" : "Delete a properties table template.",
        "operationId" : "deleteTableTemplate",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Delete" ],
          "BasicAuth" : [ "OAuth2Delete" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/tasks" : {
      "get" : {
        "tags" : [ "Task" ],
        "summary" : "Lists tasks assigned to the specified user",
        "description" : "Returns a list of tasks assigneed to the userId specified in the request. Only company admins can view tasks that were not created by them and are not assigned to them.",
        "operationId" : "getActionItems",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      },
      "post" : {
        "tags" : [ "Task" ],
        "summary" : "Create a new task in a draft state.",
        "operationId" : "createTask",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/tasks/{tid}" : {
      "get" : {
        "tags" : [ "Task" ],
        "summary" : "Get a task by id.",
        "operationId" : "getTask",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      },
      "post" : {
        "tags" : [ "Task" ],
        "summary" : "Update the task and its properties.",
        "operationId" : "updateTask",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/tasks/{tid}/{transition}" : {
      "post" : {
        "tags" : [ "Task" ],
        "summary" : "Execute a workflow transition.",
        "operationId" : "transitionTask",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/teams" : {
      "get" : {
        "tags" : [ "Team" ],
        "summary" : "Get a list of all teams the current user belongs to.",
        "operationId" : "find",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/teams/{tid}" : {
      "get" : {
        "tags" : [ "Team" ],
        "summary" : "Get team information by team ID.",
        "operationId" : "getTeam",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/teams/{tid}/members" : {
      "get" : {
        "tags" : [ "Team" ],
        "summary" : "Get a list of a team's members.",
        "description" : "Returns a maximum of 20 per page.",
        "operationId" : "getMembers",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/thumbnails/d/{did}" : {
      "get" : {
        "tags" : [ "Thumbnail" ],
        "summary" : "Get the thumbnail info for a document in the default workspace.",
        "description" : "* By default, returns thumbnail info for the element with the most-recently generated image. If you pinned an element for the document thumbnail, that element will always be used for the document-level thumbnail, if it exists in the workspace.\n* The default workspace may vary by user; the image served depends on the signed-in user.\n* See also: [Tech tip on how to change a document thumbnail in onshape](https://www.onshape.com/en/resource-center/tech-tips/tech-tip-how-t[...]",
        "operationId" : "getThumbnailForDocument",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/thumbnails/d/{did}/v/{vid}" : {
      "get" : {
        "tags" : [ "Thumbnail" ],
        "summary" : "Get the thumbnail info for a version of a document.",
        "description" : "* By default, returns thumbnail info for the element with the most-recently generated image. If you pinned an element for the document thumbnail, that element will always be used for the document-level thumbnail, if it exists in the workspace.\n* See also: [Tech tip on how to change a document thumbnail in onshape](https://www.onshape.com/en/resource-center/tech-tips/tech-tip-how-to-change-a-document-thumbnail-in-onshape)",
        "operationId" : "getThumbnailForDocumentAndVersion",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/thumbnails/d/{did}/w/{wid}" : {
      "get" : {
        "tags" : [ "Thumbnail" ],
        "summary" : "Get the thumbnail info for a workspace.",
        "description" : "* By default, returns thumbnail info for the element with the most-recently generated image. If you pinned an element for the document thumbnail, that element will always be used for the document-level thumbnail, if it exists in the workspace.\n* See also: [Tech tip on how to change a document thumbnail in onshape](https://www.onshape.com/en/resource-center/tech-tips/tech-tip-how-to-change-a-document-thumbnail-in-onshape)",
        "operationId" : "getDocumentThumbnail",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/thumbnails/d/{did}/w/{wid}/e/{eid}/ac/{cid}/s/{sz}" : {
      "get" : {
        "tags" : [ "Thumbnail" ],
        "summary" : "Get the thumbnail image with the given configuration for an element.",
        "description" : "Returns the thumbnail image for an element at a specified version, with the given configuration.",
        "operationId" : "getElementThumbnailWithApiConfiguration",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/thumbnails/d/{did}/w/{wid}/s/{sz}" : {
      "get" : {
        "tags" : [ "Thumbnail" ],
        "summary" : "Get the thumbnail image with the given size for a document.",
        "description" : "* By default, returns thumbnail image for the element with the most-recently generated image. If you pinned an element for the document thumbnail, that element will always be used for the document-level thumbnail, if it exists in the workspace.\n* See also: [Tech tip on how to change a document thumbnail in onshape](https://www.onshape.com/en/resource-center/tech-tips/tech-tip-how-to-change-a-document-thumbnail-in-onshape)",
        "operationId" : "getDocumentThumbnailWithSize",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/thumbnails/d/{did}/{wv}/{wvid}/e/{eid}" : {
      "get" : {
        "tags" : [ "Thumbnail" ],
        "summary" : "Get the thumbnail info structure for an element.",
        "description" : "Returns thumbnail info for the given document, workspace or version, and element.",
        "operationId" : "getElementThumbnail",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      },
      "post" : {
        "tags" : [ "Thumbnail" ],
        "summary" : "Set the thumbnail image for an application element.",
        "description" : "* Allows 3rd-party applications to set thumbnails for their elements. \n* Application elements can have both primary and secondary thumbnails. A primary thumbnail represents the top-level of the element. A secondary thumbnail can represent sub-components of the element (e.g., a drawing sheet).\n* To update one or more thumbnails, you must set the overwrite query param to `true` and supply the entire set of thumbnails. All previous thumbnails will be deleted prior to upda[...]",
        "operationId" : "setApplicationElementThumbnail",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      },
      "delete" : {
        "tags" : [ "Thumbnail" ],
        "summary" : "Delete an element's thumbnail.",
        "description" : "Deletes an application element's thumbnail and images for the given document, workspace or version, and element combination.",
        "operationId" : "deleteApplicationThumbnails",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/thumbnails/d/{did}/{wv}/{wvid}/e/{eid}/s/{sz}" : {
      "get" : {
        "tags" : [ "Thumbnail" ],
        "summary" : "Get the thumbnail image with the given size for an element.",
        "operationId" : "getElementThumbnailWithSize",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/thumbnails/document/{did}" : {
      "get" : {
        "tags" : [ "Thumbnail" ],
        "summary" : "This endpoint will be deprecated soon. Use `getThumbnailForDocument` instead.",
        "description" : "This API exists for historical reasons. It uses `/document/` in the path, rather than the standard `/d/` to specify the document.",
        "operationId" : "getThumbnailForDocumentOld",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/thumbnails/document/{did}/version/{vid}" : {
      "get" : {
        "tags" : [ "Thumbnail" ],
        "summary" : "This endpoint will be deprecated soon. Use `getThumbnailForDocumentAndVersion` instead.",
        "description" : "This API exists for historical reasons. It uses `/document/` in the path, rather than the standard `/d/` to specify the document.",
        "operationId" : "getThumbnailForDocumentAndVersionOld",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/translations/d/{did}" : {
      "get" : {
        "tags" : [ "Translation" ],
        "summary" : "Get information on an in-progress or completed translation by document ID.",
        "operationId" : "getDocumentTranslations",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/translations/d/{did}/w/{wid}" : {
      "post" : {
        "tags" : [ "Translation" ],
        "summary" : "Upload a foreign file into Onshape and translate the data into parts, Part Studios, assemblies, and subassemblies.",
        "description" : "The API call may complete before the translation is finished. If `requestState = ACTIVE`, the translation can be polled until the state is either `DONE` or `FAILED`. Alternatively, a webhook callback can be registered for notification of translation completion (requires `Write` scope if `storeInDocument` is `true`). See [API Guide: Model Translation](https://onshape-public.github.io/docs/api-adv/translation/) for more details.",
        "operationId" : "createTranslation",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/translations/translationformats" : {
      "get" : {
        "tags" : [ "Translation" ],
        "summary" : "Get a list of formats this translation can use.",
        "description" : "Note that we don't necessarily support both import and export for any given format. See [API Guide: Model Translation](https://onshape-public.github.io/docs/api-adv/translation/) for more details.",
        "operationId" : "getAllTranslatorFormats",
        "deprecated" : false,
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/translations/{tid}" : {
      "get" : {
        "tags" : [ "Translation" ],
        "summary" : "Get information on an in-progress or completed translation by translation ID.",
        "description" : "When the translation is complete, `requestState` changes from `ACTIVE` to `DONE` or `FAILED`. See [API Guide: Model Translation](https://onshape-public.github.io/docs/api-adv/translation/) for more details.",
        "operationId" : "getTranslation",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      },
      "delete" : {
        "tags" : [ "Translation" ],
        "summary" : "Delete a translation request.",
        "operationId" : "deleteTranslation",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/users/session" : {
      "post" : {
        "tags" : [ "User" ],
        "summary" : "Authenticate a user's Onshape credentials, and create a session.",
        "description" : "Returned information depends on caller's `OAuth2ReadPll` scope.",
        "operationId" : "session",
        "deprecated" : false,
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/users/sessioninfo" : {
      "get" : {
        "tags" : [ "User" ],
        "summary" : "Get the session information for an authenticated (signed-in) user.",
        "description" : "Returned information depends on caller's `OAuth2ReadPll` scope.",
        "operationId" : "sessionInfo",
        "deprecated" : false,
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/users/settings" : {
      "get" : {
        "tags" : [ "User" ],
        "summary" : "Get the user settings for the signed-in user (i.e., you) for the current session.",
        "description" : "* Non-admins can call this API for their own user ID. \n* Mouse button settings are contained in `reverseScrollWheelZoomDirection` and `viewManipulationMouseKeyMapping`. \n* For each action in `viewManipulationMouseKeyMapping`, an array of modifier key/mouse combos is provided that performs that action. \n* Possible modifier keys include `SHIFT` and `CTRL`. \n* Possible mouse buttons include `MMB` (middle mouse button), `RMB` (right mouse button), and `SCROLLWHEEL`. \n* [...]",
        "operationId" : "getUserSettingsCurrentLoggedInUser",
        "deprecated" : false,
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/users/{uid}/settings" : {
      "get" : {
        "tags" : [ "User" ],
        "summary" : "Get the user settings for any user in your organization (admins only).",
        "description" : "* Mouse button settings are contained in `reverseScrollWheelZoomDirection` and `viewManipulationMouseKeyMapping`. \n* For each action in `viewManipulationMouseKeyMapping`, an array of modifier key/mouse combos is provided that performs that action. \n* Possible modifier keys include `SHIFT` and `CTRL`. \n* Possible mouse buttons include `MMB` (middle mouse button), `RMB` (right mouse button), and `SCROLLWHEEL`. \n* Scrolling forward zooms in, unless `reverseScrollWheelZo[...]",
        "operationId" : "getUserSettings",
        "deprecated" : false,
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/variables/d/{did}/w/{wid}/e/{eid}/variables" : {
      "post" : {
        "tags" : [ "Variables" ],
        "summary" : "Assign variables to a Variable Studio",
        "operationId" : "setVariables",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/variables/d/{did}/w/{wid}/e/{eid}/variablestudioreferences" : {
      "post" : {
        "tags" : [ "Variables" ],
        "summary" : "Set the Variable Studio references for an element.",
        "operationId" : "setVariableStudioReferences",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/variables/d/{did}/w/{wid}/e/{eid}/variablestudioscope" : {
      "post" : {
        "tags" : [ "Variables" ],
        "summary" : "Set the scope the Variable Studio.",
        "operationId" : "setVariableStudioScope",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/variables/d/{did}/w/{wid}/variablestudio" : {
      "post" : {
        "tags" : [ "Variables" ],
        "summary" : "Create a new Variable Studio in a document and workspace.",
        "operationId" : "createVariableStudio",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Write" ],
          "BasicAuth" : [ "OAuth2Write" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/variables/d/{did}/{wv}/{wvid}/e/{eid}/variables" : {
      "get" : {
        "tags" : [ "Variables" ],
        "summary" : "Get the contents of all variable tables in an element.",
        "operationId" : "getVariables",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/variables/d/{did}/{wv}/{wvid}/e/{eid}/variablestudioreferences" : {
      "get" : {
        "tags" : [ "Variables" ],
        "summary" : "Get the Variable Studio references for an element.",
        "operationId" : "getVariableStudioReferences",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/variables/d/{did}/{wv}/{wvid}/e/{eid}/variablestudioscope" : {
      "get" : {
        "tags" : [ "Variables" ],
        "summary" : "Get the scope of a Variable Studio.",
        "operationId" : "getVariableStudioScope",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/versions" : {
      "get" : {
        "tags" : [ "Version" ],
        "summary" : "Get all versions of the Onshape REST APIs.",
        "operationId" : "getAllVersions",
        "deprecated" : false,
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/webhooks" : {
      "get" : {
        "tags" : [ "Webhook" ],
        "summary" : "Get a list of all webhooks registered by a user or company.",
        "description" : "See [API Guide: Webhooks](https://onshape-public.github.io/docs/app-dev/webhook/) for implementation details.",
        "operationId" : "getWebhooks",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      },
      "post" : {
        "tags" : [ "Webhook" ],
        "summary" : "Create a new webhook.",
        "description" : "Click **Callbacks** below for a list of events your app can subscribe to. See [API Guide: Webhooks](https://onshape-public.github.io/docs/app-dev/webhook/) for implementation details.",
        "operationId" : "createWebhook",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/webhooks/{webhookid}" : {
      "get" : {
        "tags" : [ "Webhook" ],
        "summary" : "Get webhook info by webhook ID.",
        "description" : "See [API Guide: Webhooks](https://onshape-public.github.io/docs/app-dev/webhook/) for implementation details.",
        "operationId" : "getWebhook",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      },
      "post" : {
        "tags" : [ "Webhook" ],
        "summary" : "Update a webhook.",
        "description" : "See [API Guide: Webhooks](https://onshape-public.github.io/docs/app-dev/webhook/) for implementation details.",
        "operationId" : "updateWebhook",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      },
      "delete" : {
        "tags" : [ "Webhook" ],
        "summary" : "Unregister a webhook.",
        "description" : "See [API Guide: Webhooks](https://onshape-public.github.io/docs/app-dev/webhook/) for implementation details.",
        "operationId" : "unregisterWebhook",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/webhooks/{webhookid}/ping" : {
      "post" : {
        "tags" : [ "Webhook" ],
        "summary" : "Ping a webhook.",
        "description" : "See [API Guide: Webhooks](https://onshape-public.github.io/docs/app-dev/webhook/) for implementation details.",
        "operationId" : "pingWebhook",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/workflow/active" : {
      "get" : {
        "tags" : [ "Workflow" ],
        "summary" : "Get all active workflows for the currently logged in user's company.",
        "description" : "Optionally takes a document ID to return all workflows for that document's owning company.",
        "operationId" : "getActiveWorkflows",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/workflow/c/{companyId}/approvers" : {
      "get" : {
        "tags" : [ "Workflow" ],
        "summary" : "Get all identities allowed to be approvers on a workflow object.",
        "description" : "* Identities can be users and/or teams. \n* For Enterprise accounts, also includes roles and any aliases that contain allowed users/teams. \n* Not object- or property-specific. \n* Used for delegation and company settings.",
        "operationId" : "getAllowedApprovers",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/workflow/companies/{cid}/objects" : {
      "get" : {
        "tags" : [ "Workflow" ],
        "summary" : "Enumerate all of a company's workflowable objects.",
        "description" : "* For example, you can enumerate RELEASES, TASKS, etc in a company by last modified time. \n* Caller must be a company admin. \n* Specify `modifiedAfter` and use the `next` URI for complete enumeration.",
        "operationId" : "enumerateObjectWorkflows",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    },
    "/workflow/obj/{objectId}/auditlog" : {
      "get" : {
        "tags" : [ "Workflow" ],
        "summary" : "Get all audit log entries for a workflowable object.",
        "description" : "Get identities (users and/or teams) allowed to be approvers on a workflow object for the company. Not object- or property-specific; used for delegation and company settings",
        "operationId" : "getAuditLog",
        "deprecated" : false,
        "security" : [ {
          "OAuth2" : [ "OAuth2Read" ],
          "BasicAuth" : [ "OAuth2Read" ]
        } ],
        "x-BTVisibility" : "PRODUCTION"
      }
    }
  },
  "components" : {
    "schemas" : {
      "Accessor" : {
        "type" : "object",
        "properties" : {
          "bufferView" : {
            "type" : "integer",
            "format" : "int32"
          },
          "byteOffset" : {
            "type" : "integer",
            "format" : "int32"
          },
          "componentType" : {
            "type" : "integer",
            "format" : "int32"
          },
          "count" : {
            "type" : "integer",
            "format" : "int32"
          },
          "extensions" : {
            "type" : "object",
            "additionalProperties" : {
              "type" : "object"
            }
          },
          "extras" : {
            "type" : "object"
          },
          "max" : {
            "type" : "array",
            "items" : {
              "type" : "number"
            }
          },
          "min" : {
            "type" : "array",
            "items" : {
              "type" : "number"
            }
          },
          "name" : {
            "type" : "string"
          },
          "normalized" : {
            "type" : "boolean"
          },
          "sparse" : {
            "$ref" : "#/components/schemas/AccessorSparse"
          },
          "type" : {
            "type" : "string"
          }
        }
      },
      "AccessorData" : {
        "type" : "object",
        "properties" : {
          "numComponentsPerElement" : {
            "type" : "integer",
            "format" : "int32"
          },
          "numElements" : {
            "type" : "integer",
            "format" : "int32"
          },
          "totalNumComponents" : {
            "type" : "integer",
            "format" : "int32"
          }
        }
      },
      "AccessorModel" : {
        "type" : "object",
        "properties" : {
          "accessorData" : {
            "$ref" : "#/components/schemas/AccessorData"
          },
          "bufferViewModel" : {
            "$ref" : "#/components/schemas/BufferViewModel"
          },
          "byteOffset" : {
            "type" : "integer",
            "format" : "int32"
          },
          "byteStride" : {
            "type" : "integer",
            "format" : "int32"
          },
          "componentSizeInBytes" : {
            "type" : "integer",
            "format" : "int32"
          },
          "componentType" : {
            "type" : "integer",
            "format" : "int32"
          },
          "count" : {
            "type" : "integer",
            "format" : "int32"
          },
          "elementSizeInBytes" : {
            "type" : "integer",
            "format" : "int32"
          },
          "elementType" : {
            "$ref" : "#/components/schemas/ElementType"
          },
          "max" : {
            "type" : "array",
            "items" : {
              "type" : "number"
            }
          },
          "min" : {
            "type" : "array",
            "items" : {
              "type" : "number"
            }
          },
          "name" : {
            "type" : "string"
          }
        }
      },
      "AccessorSparse" : {
        "type" : "object",
        "properties" : {
          "count" : {
            "type" : "integer",
            "format" : "int32"
          },
          "extensions" : {
            "type" : "object",
            "additionalProperties" : {
              "type" : "object"
            }
          },
          "extras" : {
            "type" : "object"
          },
          "indices" : {
            "$ref" : "#/components/schemas/AccessorSparseIndices"
          },
          "values" : {
            "$ref" : "#/components/schemas/AccessorSparseValues"
          }
        }
      },
      "AccessorSparseIndices" : {
        "type" : "object",
        "properties" : {
          "bufferView" : {
            "type" : "integer",
            "format" : "int32"
          },
          "byteOffset" : {
            "type" : "integer",
            "format" : "int32"
          },
          "componentType" : {
            "type" : "integer",
            "format" : "int32"
          },
          "extensions" : {
            "type" : "object",
            "additionalProperties" : {
              "type" : "object"
            }
          },
          "extras" : {
            "type" : "object"
          }
        }
      },
      "AccessorSparseValues" : {
        "type" : "object",
        "properties" : {
          "bufferView" : {
            "type" : "integer",
            "format" : "int32"
          },
          "byteOffset" : {
            "type" : "integer",
            "format" : "int32"
          },
          "extensions" : {
            "type" : "object",
            "additionalProperties" : {
              "type" : "object"
            }
          },
          "extras" : {
            "type" : "object"
          }
        }
      },
      "Animation" : {
        "type" : "object",
        "properties" : {
          "channels" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/AnimationChannel"
            }
          },
          "extensions" : {
            "type" : "object",
            "additionalProperties" : {
              "type" : "object"
            }
          },
          "extras" : {
            "type" : "object"
          },
          "name" : {
            "type" : "string"
          },
          "samplers" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/AnimationSampler"
            }
          }
        }
      },
      "AnimationChannel" : {
        "type" : "object",
        "properties" : {
          "extensions" : {
            "type" : "object",
            "additionalProperties" : {
              "type" : "object"
            }
          },
          "extras" : {
            "type" : "object"
          },
          "sampler" : {
            "type" : "integer",
            "format" : "int32"
          },
          "target" : {
            "$ref" : "#/components/schemas/AnimationChannelTarget"
          }
        }
      },
      "AnimationChannelTarget" : {
        "type" : "object",
        "properties" : {
          "extensions" : {
            "type" : "object",
            "additionalProperties" : {
              "type" : "object"
            }
          },
          "extras" : {
            "type" : "object"
          },
          "node" : {
            "type" : "integer",
            "format" : "int32"
          },
          "path" : {
            "type" : "string"
          }
        }
      },
      "AnimationSampler" : {
        "type" : "object",
        "properties" : {
          "extensions" : {
            "type" : "object",
            "additionalProperties" : {
              "type" : "object"
            }
          },
          "extras" : {
            "type" : "object"
          },
          "input" : {
            "type" : "integer",
            "format" : "int32"
          },
          "interpolation" : {
            "type" : "string"
          },
          "output" : {
            "type" : "integer",
            "format" : "int32"
          }
        }
      },
      "ApiResponse" : {
        "type" : "object",
        "properties" : {
          "content" : {
            "type" : "object",
            "properties" : {
              "empty" : {
                "type" : "boolean"
              }
            },
            "additionalProperties" : {
              "$ref" : "#/components/schemas/MediaType"
            }
          },
          "description" : {
            "type" : "string"
          },
          "extensions" : {
            "type" : "object",
            "additionalProperties" : {
              "type" : "object"
            }
          },
          "get$ref" : {
            "type" : "string"
          }
        }
      },
      "Asset" : {
        "type" : "object",
        "properties" : {
          "copyright" : {
            "type" : "string"
          },
          "extensions" : {
            "type" : "object",
            "additionalProperties" : {
              "type" : "object"
            }
          },
          "extras" : {
            "type" : "object"
          },
          "generator" : {
            "type" : "string"
          },
          "minVersion" : {
            "type" : "string"
          },
          "version" : {
            "type" : "string"
          }
        }
      },
      "BTAPIApplicationExtensionInfo" : {
        "type" : "object",
        "properties" : {
          "actionBody" : {
            "type" : "string"
          },
          "actionType" : {
            "type" : "integer",
            "format" : "int32"
          },
          "actionUrl" : {
            "type" : "string"
          },
          "applicationId" : {
            "type" : "string"
          },
          "clientId" : {
            "type" : "string"
          },
          "description" : {
            "type" : "string"
          },
          "extensionContext" : {
            "type" : "integer",
            "format" : "int64"
          },
          "extensionLocation" : {
            "type" : "integer",
            "format" : "int64"
          },
          "hasIcon" : {
            "type" : "boolean"
          },
          "hasPendingIcon" : {
            "type" : "boolean"
          },
          "href" : {
            "type" : "string",
            "description" : "URI to fetch complete information of the resource.",
            "format" : "uri"
          },
          "iconUrl" : {
            "type" : "string"
          },
          "id" : {
            "type" : "string",
            "description" : "Id of the resource."
          },
          "name" : {
            "type" : "string",
            "description" : "Name of the resource."
          },
          "parentAppPrimaryFormat" : {
            "type" : "string"
          },
          "showResponse" : {
            "type" : "boolean"
          },
          "viewRef" : {
            "type" : "string",
            "description" : "URI to visualize the resource in a webclient if applicable.",
            "format" : "uri"
          },
          "visibilityRule" : {
            "type" : "string"
          }
        }
      },
      "BTAPIApplicationSummaryInfo" : {
        "type" : "object",
        "properties" : {
          "clientId" : {
            "type" : "string"
          },
          "description" : {
            "type" : "string"
          },
          "href" : {
            "type" : "string",
            "description" : "URI to fetch complete information of the resource.",
            "format" : "uri"
          },
          "id" : {
            "type" : "string",
            "description" : "Id of the resource."
          },
          "name" : {
            "type" : "string",
            "description" : "Name of the resource."
          },
          "state" : {
            "type" : "integer",
            "format" : "int32"
          },
          "viewRef" : {
            "type" : "string",
            "description" : "URI to visualize the resource in a webclient if applicable.",
            "format" : "uri"
          }
        }
      },
      "BTAPIWorkflowableType" : {
        "type" : "string",
        "description" : "All workflowable types that can be enumerated.",
        "enum" : [ "RELEASE", "TASK", "ASSIGNMENT", "OBSOLETION" ]
      },
      "BTAclEntryInfo" : {
        "type" : "object",
        "properties" : {
          "acceptOwnerTransfer" : {
            "type" : "boolean"
          },
          "companyName" : {
            "type" : "string"
          },
          "email" : {
            "type" : "string"
          },
          "enterpriseMember" : {
            "type" : "boolean"
          },
          "entryId" : {
            "type" : "string"
          },
          "entryState" : {
            "$ref" : "#/components/schemas/BTUserState"
          },
          "entryType" : {
            "type" : "integer",
            "format" : "int32"
          },
          "image" : {
            "type" : "string"
          },
          "name" : {
            "type" : "string"
          },
          "objectId" : {
            "type" : "string"
          },
          "pendingOwnerTransfer" : {
            "type" : "boolean"
          },
          "permission" : {
            "type" : "integer",
            "format" : "int64"
          },
          "permissionSet" : {
            "type" : "array",
            "items" : {
              "type" : "string"
            }
          },
          "proCompanySubtype" : {
            "type" : "integer",
            "format" : "int32"
          },
          "teamName" : {
            "type" : "string"
          }
        }
      },
      "BTAclInfo" : {
        "type" : "object",
        "properties" : {
          "admin" : {
            "type" : "boolean"
          },
          "entries" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/BTAclEntryInfo"
            }
          },
          "href" : {
            "type" : "string",
            "description" : "URI to fetch complete information of the resource.",
            "format" : "uri"
          },
          "id" : {
            "type" : "string",
            "description" : "Id of the resource."
          },
          "inheritedAcls" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/BTInheritedAclInfo"
            }
          },
          "name" : {
            "type" : "string",
            "description" : "Name of the resource."
          },
          "objectId" : {
            "type" : "string"
          },
          "objectType" : {
            "type" : "integer",
            "format" : "int64"
          },
          "owner" : {
            "$ref" : "#/components/schemas/BTOwnerInfo"
          },
          "public" : {
            "type" : "boolean"
          },
          "sharedWithSupport" : {
            "type" : "boolean"
          },
          "viewRef" : {
            "type" : "string",
            "description" : "URI to visualize the resource in a webclient if applicable.",
            "format" : "uri"
          },
          "visibility" : {
            "type" : "string"
          }
        }
      },
      "BTAclParams" : {
        "type" : "object",
        "properties" : {
          "anonymousAccessAllowed" : {
            "type" : "boolean"
          },
          "anonymousAllowsExport" : {
            "type" : "boolean"
          },
          "docStateParams" : {
            "type" : "object",
            "additionalProperties" : {
              "type" : "string"
            }
          },
          "documentId" : {
            "type" : "string"
          },
          "elementId" : {
            "type" : "string"
          },
          "public" : {
            "type" : "boolean"
          },
          "workspaceId" : {
            "type" : "string"
          }
        }
      },
      "BTActiveSheetMetalFilter-2944" : {
        "type" : "object",
        "properties" : {
          "btType" : {
            "type" : "string",
            "description" : "Type of JSON object."
          }
        },
        "allOf" : [ {
          "$ref" : "#/components/schemas/BTQueryFilter-183"
        }, {
          "type" : "object",
          "properties" : {
            "btType" : {
              "type" : "string"
            },
            "isFromActiveSheetMetal" : {
              "type" : "boolean"
            }
          }
        } ]
      },
      "BTActiveWorkflowInfo" : {
        "type" : "object",
        "properties" : {
          "allowReleaseItemsFromOtherDocuments" : {
            "type" : "boolean"
          },
          "canCurrentUserCreateReleases" : {
            "type" : "boolean"
          },
          "canCurrentUserEditStandardContent" : {
            "type" : "boolean"
          },
          "canCurrentUserManageWorkflows" : {
            "type" : "boolean"
          },
          "canCurrentUserSeeArenaItemLink" : {
            "type" : "boolean"
          },
          "canCurrentUserSyncBomToArena" : {
            "type" : "boolean"
          },
          "canCurrentUserSyncRevisionsToArena" : {
            "type" : "boolean"
          },
          "canCurrentUserSyncStandardContentToArena" : {
            "type" : "boolean"
          },
          "canCurrentUserSyncToArena" : {
            "type" : "boolean"
          },
          "companyId" : {
            "type" : "string"
          },
          "documentId" : {
            "type" : "string"
          },
          "drawingCanDuplicatePartNumber" : {
            "type" : "boolean"
          },
          "enabledActiveMultipleWorkflows" : {
            "type" : "boolean"
          },
          "hasInactiveCustomWorkflows" : {
            "type" : "boolean"
          },
          "obsoletionWorkflow" : {
            "$ref" : "#/components/schemas/BTPublishedWorkflowInfo"
          },
          "obsoletionWorkflowId" : {
            "type" : "string"
          },
          "osCategoryIdToArenaNumberFormatId" : {
            "type" : "object",
            "additionalProperties" : {
              "type" : "string"
            }
          },
          "partNumberingSchemeId" : {
            "type" : "string"
          },
          "pickableWorkflows" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/BTPublishedWorkflowInfo"
            }
          },
          "releaseWorkflow" : {
            "$ref" : "#/components/schemas/BTPublishedWorkflowInfo"
          },
          "releaseWorkflowId" : {
            "type" : "string"
          },
          "releaseableApplications" : {
            "type" : "array",
            "items" : {
              "type" : "string"
            }
          },
          "standardContentNumberingSchemeId" : {
            "type" : "string"
          },
          "standardContentUsingAutoNumbering" : {
            "type" : "boolean"
          },
          "standardContentUsingThirdPartyPartNumbering" : {
            "type" : "boolean"
          },
          "usingAutoPartNumbering" : {
            "type" : "boolean"
          },
          "usingManagedWorkflow" : {
            "type" : "boolean"
          },
          "usingThirdPartyPartNumbering" : {
            "type" : "boolean"
          }
        }
      },
      "BTAddressInfo" : {
        "type" : "object",
        "properties" : {
          "address" : {
            "type" : "string"
          },
          "city" : {
            "type" : "string"
          },
          "country" : {
            "type" : "string"
          },
          "countryCode" : {
            "type" : "string"
          },
          "id" : {
            "type" : "string"
          },
          "state" : {
            "type" : "string"
          },
          "stateCode" : {
            "type" : "string"
          },
          "zip" : {
            "type" : "string"
          }
        }
      },
      "BTAliasEntryInfo" : {
        "type" : "object",
        "properties" : {
          "createdAt" : {
            "type" : "string",
            "format" : "date-time"
          },
          "href" : {
            "type" : "string",
            "description" : "URI to fetch complete information of the resource.",
            "format" : "uri"
          },
          "id" : {
            "type" : "string",
            "description" : "Id of the resource."
          },
          "identity" : {
            "$ref" : "#/components/schemas/BTIdentityInfo"
          },
          "name" : {
            "type" : "string",
            "description" : "Name of the resource."
          },
          "viewRef" : {
            "type" : "string",
            "description" : "URI to visualize the resource in a webclient if applicable.",
            "format" : "uri"
          }
        }
      },
      "BTAliasEntryParams" : {
        "type" : "object",
        "properties" : {
          "email" : {
            "type" : "string"
          },
          "teamId" : {
            "type" : "string"
          },
          "userId" : {
            "type" : "string"
          }
        }
      },
      "BTAliasInfo" : {
        "type" : "object",
        "properties" : {
          "companyId" : {
            "type" : "string"
          },
          "createdAt" : {
            "type" : "string",
            "format" : "date-time"
          },
          "description" : {
            "type" : "string"
          },
          "entries" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/BTAliasEntryInfo"
            }
          },
          "href" : {
            "type" : "string",
            "description" : "URI to fetch complete information of the resource.",
            "format" : "uri"
          },
          "id" : {
            "type" : "string",
            "description" : "Id of the resource."
          },
          "identities" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/BTIdentityInfo"
            }
          },
          "name" : {
            "type" : "string",
            "description" : "Name of the resource."
          },
          "viewRef" : {
            "type" : "string",
            "description" : "URI to visualize the resource in a webclient if applicable.",
            "format" : "uri"
          }
        }
      },
      "BTAliasParams" : {
        "type" : "object",
        "properties" : {
          "additions" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/BTAliasEntryParams"
            }
          },
          "description" : {
            "type" : "string"
          },
          "entries" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/BTAliasEntryParams"
            }
          },
          "name" : {
            "type" : "string"
          },
          "removals" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/BTAliasEntryParams"
            }
          }
        }
      },
      "BTAllowEdgePointFilter-2371" : {
        "type" : "object",
        "properties" : {
          "btType" : {
            "type" : "string",
            "description" : "Type of JSON object."
          }
        },
        "allOf" : [ {
          "$ref" : "#/components/schemas/BTQueryFilter-183"
        }, {
          "type" : "object",
          "properties" : {
            "allowsEdgePoint" : {
              "type" : "boolean"
            },
            "btType" : {
              "type" : "string"
            }
          }
        } ]
      },
      "BTAllowFlattenedGeometryFilter-2140" : {
        "type" : "object",
        "properties" : {
          "btType" : {
            "type" : "string",
            "description" : "Type of JSON object."
          }
        },
        "allOf" : [ {
          "$ref" : "#/components/schemas/BTQueryFilter-183"
        }, {
          "type" : "object",
          "properties" : {
            "allowsFlattenedGeometry" : {
              "type" : "boolean"
            },
            "btType" : {
              "type" : "string"
            }
          }
        } ]
      },
      "BTAllowMeshGeometryFilter-1026" : {
        "type" : "object",
        "properties" : {
          "btType" : {
            "type" : "string",
            "description" : "Type of JSON object."
          }
        },
        "allOf" : [ {
          "$ref" : "#/components/schemas/BTQueryFilter-183"
        }, {
          "type" : "object",
          "properties" : {
            "allowsMeshGeometry" : {
              "type" : "boolean"
            },
            "btType" : {
              "type" : "string"
            }
          }
        } ]
      },
      "BTAllowedMateTypeFilter-1511" : {
        "type" : "object",
        "properties" : {
          "btType" : {
            "type" : "string",
            "description" : "Type of JSON object."
          }
        },
        "allOf" : [ {
          "$ref" : "#/components/schemas/BTMateFilter-162"
        }, {
          "type" : "object",
          "properties" : {
            "allowedMateTypes" : {
              "type" : "array",
              "items" : {
                "$ref" : "#/components/schemas/GBTMateType"
              }
            },
            "btType" : {
              "type" : "string"
            }
          }
        } ]
      },
      "BTAndFilter-110" : {
        "type" : "object",
        "properties" : {
          "btType" : {
            "type" : "string",
            "description" : "Type of JSON object."
          }
        },
        "allOf" : [ {
          "$ref" : "#/components/schemas/BTQueryFilter-183"
        }, {
          "type" : "object",
          "properties" : {
            "btType" : {
              "type" : "string"
            },
            "operand1" : {
              "$ref" : "#/components/schemas/BTQueryFilter-183"
            },
            "operand2" : {
              "$ref" : "#/components/schemas/BTQueryFilter-183"
            }
          }
        } ]
      },
      "BTAngularDimensionDisplayData-320" : {
        "type" : "object",
        "properties" : {
          "btType" : {
            "type" : "string",
            "description" : "Type of JSON object."
          }
        },
        "discriminator" : {
          "propertyName" : "btType",
          "mapping" : {
            "BTArcLengthDimensionDisplayData-1018" : "#/components/schemas/BTArcLengthDimensionDisplayData-1018"
          }
        },
        "allOf" : [ {
          "$ref" : "#/components/schemas/BTDimensionDisplayData-323"
        }, {
          "type" : "object",
          "properties" : {
            "btType" : {
              "type" : "string"
            },
            "clockwise" : {
              "type" : "boolean"
            },
            "positionR" : {
              "type" : "number",
              "format" : "double"
            },
            "positionT" : {
              "type" : "number",
              "format" : "double"
            },
            "witnessEndPoint0r" : {
              "type" : "number",
              "format" : "double"
            },
            "witnessEndPoint0t" : {
              "type" : "number",
              "format" : "double"
            },
            "witnessEndPoint1r" : {
              "type" : "number",
              "format" : "double"
            },
            "witnessEndPoint1t" : {
              "type" : "number",
              "format" : "double"
            },
            "witnessMaxPoint0r" : {
              "type" : "number",
              "format" : "double"
            },
            "witnessMaxPoint1r" : {
              "type" : "number",
              "format" : "double"
            },
            "witnessMinPoint0r" : {
              "type" : "number",
              "format" : "double"
            },
            "witnessMinPoint1r" : {
              "type" : "number",
              "format" : "double"
            }
          }
        } ]
      },
      "BTAnnotationDisplayData-3225" : {
        "type" : "object",
        "properties" : {
          "annotationPlane" : {
            "type" : "array",
            "items" : {
              "type" : "number",
              "format" : "float"
            }
          },
          "baseNormal" : {
            "type" : "array",
            "items" : {
              "type" : "number",
              "format" : "float"
            }
          },
          "basePoint" : {
            "type" : "array",
            "items" : {
              "type" : "number",
              "format" : "float"
            }
          },
          "btType" : {
            "type" : "string",
            "description" : "Type of JSON object."
          },
          "deterministicId" : {
            "type" : "string"
          },
          "dxdySegments" : {
            "type" : "array",
            "items" : {
              "type" : "number",
              "format" : "float"
            }
          },
          "numberOfLeaderSegements" : {
            "type" : "integer",
            "format" : "int32"
          }
        },
        "discriminator" : {
          "propertyName" : "btType",
          "mapping" : {
            "BTAnnotationGTolDisplayData-4887" : "#/components/schemas/BTAnnotationGTolDisplayData-4887",
            "BTAnnotationWeldDisplayData-4919" : "#/components/schemas/BTAnnotationWeldDisplayData-4919",
            "BTDatumDisplayData-3408" : "#/components/schemas/BTDatumDisplayData-3408"
          }
        }
      },
      "BTAnnotationElementDisplayData-894" : {
        "type" : "object",
        "properties" : {
          "annotationIdToDisplayObject" : {
            "type" : "object",
            "additionalProperties" : {
              "$ref" : "#/components/schemas/BTAnnotationDisplayData-3225"
            }
          },
          "btType" : {
            "type" : "string",
            "description" : "Type of JSON object."
          }
        }
      },
      "BTAnnotationGTolDisplayData-4887" : {
        "type" : "object",
        "properties" : {
          "btType" : {
            "type" : "string",
            "description" : "Type of JSON object."
          }
        },
        "allOf" : [ {
          "$ref" : "#/components/schemas/BTAnnotationDisplayData-3225"
        }, {
          "type" : "object",
          "properties" : {
            "btType" : {
              "type" : "string"
            },
            "rows" : {
              "type" : "array",
              "items" : {
                "$ref" : "#/components/schemas/BTAnnotationGTolRowDisplayData-4397"
              }
            }
          }
        } ]
      },
      "BTAnnotationGTolRowDisplayData-4397" : {
        "type" : "object",
        "properties" : {
          "btType" : {
            "type" : "string",
            "description" : "Type of JSON object."
          },
          "constraintType" : {
            "$ref" : "#/components/schemas/GBTGTolConstraintType"
          },
          "references" : {
            "type" : "array",
            "items" : {
              "type" : "string"
            }
          },
          "tolerance" : {
            "type" : "number",
            "format" : "double"
          }
        }
      },
      "BTAnnotationWeldDisplayData-4919" : {
        "type" : "object",
        "properties" : {
          "btType" : {
            "type" : "string",
            "description" : "Type of JSON object."
          }
        },
        "allOf" : [ {
          "$ref" : "#/components/schemas/BTAnnotationDisplayData-3225"
        }, {
          "type" : "object",
          "properties" : {
            "btType" : {
              "type" : "string"
            },
            "jointType" : {
              "$ref" : "#/components/schemas/GBTWeldJointType"
            },
            "lowerGroove" : {
              "type" : "number",
              "format" : "double"
            },
            "lowerRootOpening" : {
              "type" : "number",
              "format" : "double"
            },
            "lowerValueFour" : {
              "type" : "number",
              "format" : "double"
            },
            "lowerValueOne" : {
              "type" : "number",
              "format" : "double"
            },
            "lowerValueThree" : {
              "type" : "number",
              "format" : "double"
            },
            "lowerValueTwo" : {
              "type" : "number",
              "format" : "double"
            },
            "lowerWeldType" : {
              "$ref" : "#/components/schemas/GBTWeldType"
            },
            "reference" : {
              "type" : "string"
            },
            "upperGroove" : {
              "type" : "number",
              "format" : "double"
            },
            "upperRootOpening" : {
              "type" : "number",
              "format" : "double"
            },
            "upperValueFour" : {
              "type" : "number",
              "format" : "double"
            },
            "upperValueOne" : {
              "type" : "number",
              "format" : "double"
            },
            "upperValueThree" : {
              "type" : "number",
              "format" : "double"
            },
            "upperValueTwo" : {
              "type" : "number",
              "format" : "double"
            },
            "upperWeldType" : {
              "$ref" : "#/components/schemas/GBTWeldType"
            }
          }
        } ]
      },
      "BTApiConfiguration" : {
        "type" : "object",
        "properties" : {
          "current" : {
            "type" : "boolean"
          },
          "default" : {
            "type" : "boolean"
          },
          "null" : {
            "type" : "boolean"
          },
          "parameterMap" : {
            "type" : "object",
            "additionalProperties" : {
              "type" : "string"
            }
          },
          "standardContent" : {
            "type" : "boolean"
          },
          "standardContentParametersId" : {
            "type" : "string"
          }
        }
      },
      "BTApiTable-2300" : {
        "type" : "object",
        "properties" : {
          "btType" : {
            "type" : "string",
            "description" : "Type of JSON object."
          },
          "columns" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/BTApiTableColumn-3141"
            }
          },
          "entityIds" : {
            "type" : "array",
            "items" : {
              "type" : "string"
            }
          },
          "id" : {
            "type" : "string"
          },
          "rows" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/BTApiTableRow-2915"
            }
          },
          "title" : {
            "type" : "string"
          }
        }
      },
      "BTApiTableColumn-3141" : {
        "type" : "object",
        "properties" : {
          "btType" : {
            "type" : "string",
            "description" : "Type of JSON object."
          },
          "header" : {
            "type" : "string"
          },
          "id" : {
            "type" : "string"
          },
          "textAlignment" : {
            "$ref" : "#/components/schemas/GBTTableTextAlignment"
          }
        }
      },
      "BTApiTableList-1223" : {
        "type" : "object",
        "properties" : {
          "btType" : {
            "type" : "string",
            "description" : "Type of JSON object."
          },
          "tables" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/BTApiTable-2300"
            }
          }
        }
      },
      "BTApiTableRow-2915" : {
        "type" : "object",
        "properties" : {
          "btType" : {
            "type" : "string",
            "description" : "Type of JSON object."
          },
          "callout" : {
            "type" : "string"
          },
          "columnIdToValue" : {
            "type" : "object",
            "additionalProperties" : {
              "type" : "string"
            }
          },
          "entityIds" : {
            "type" : "array",
            "items" : {
              "type" : "string"
            }
          }
        }
      },
      "BTApiVersion" : {
        "type" : "string",
        "enum" : [ "UNDEFINED", "V1_START", "V2_SERIALIZATION_UNIFICATION", "V3_NEW_BOM_FORMAT", "V4_TRANSACTIONS_NO_NEW", "V5_BODY_DETAILS_COMPOSITE_REFERENCE", "V6_JSON_EDIT_RESPONSE_BUGFIX", "V7_SKETCH_ENDPOINT_INCLUDES_SOLVE_STATUS", "V8_RESTORE_NOOP_NO_NEW_MICROVERSION", "V9_INCLUDE_DETERMINISTIC_IDS_TO_QUERY_RESPONSES", "V10_VALIDATE_VISIBILTY_CONDITIONS_FOR_PS_CONFIG_PARAMS" ]
      },
      "BTAppArrayInfoBTAppDrawingViewInfo" : {
        "type" : "object",
        "properties" : {
          "changeId" : {
            "type" : "string"
          },
          "errorCode" : {
            "type" : "integer",
            "description" : "`0: OK (healthy) | 1: INFO | 2: WARNING | 3: ERROR (dangling or view generation call failed) | 4: UNKNOWN`",
            "format" : "int32"
          },
          "errorDescription" : {
            "type" : "string",
            "description" : "A human-readable value for the error that occurred, if one occurred."
          },
          "errorValue" : {
            "$ref" : "#/components/schemas/BTAppElementErrorCode"
          },
          "items" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/BTAppDrawingViewInfo"
            }
          },
          "parentChangeId" : {
            "type" : "string"
          }
        }
      },
      "BTAppAssociativeDataArrayInfo" : {
        "type" : "object",
        "properties" : {
          "changeId" : {
            "type" : "string"
          },
          "errorCode" : {
            "type" : "integer",
            "description" : "`0: OK (healthy) | 1: INFO | 2: WARNING | 3: ERROR (dangling or view generation call failed) | 4: UNKNOWN`",
            "format" : "int32"
          },
          "errorDescription" : {
            "type" : "string",
            "description" : "A human-readable value for the error that occurred, if one occurred."
          },
          "errorValue" : {
            "$ref" : "#/components/schemas/BTAppElementErrorCode"
          },
          "items" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/BTAssociativeDataInfo"
            }
          },
          "parentChangeId" : {
            "type" : "string"
          }
        }
      },
      "BTAppDrawingViewInfo" : {
        "type" : "object",
        "properties" : {
          "associativityChangeId" : {
            "type" : "string"
          },
          "bomReferenceId" : {
            "type" : "string"
          },
          "brokenOutBBoxes" : {
            "type" : "object",
            "additionalProperties" : {
              "$ref" : "#/components/schemas/BTBoundingBox-1052"
            }
          },
          "brokenOutEndConditions" : {
            "type" : "object",
            "additionalProperties" : {
              "$ref" : "#/components/schemas/BTBrokenOutEndCondition-1107"
            }
          },
          "brokenOutPointNumbers" : {
            "type" : "array",
            "items" : {
              "type" : "integer",
              "format" : "int32"
            }
          },
          "changeId" : {
            "type" : "string"
          },
          "computeIntersection" : {
            "type" : "boolean"
          },
          "cutPoint" : {
            "type" : "array",
            "items" : {
              "type" : "number",
              "format" : "double"
            }
          },
          "depthSectionEndCondition" : {
            "$ref" : "#/components/schemas/BTBrokenOutEndCondition-1107"
          },
          "displayStateId" : {
            "type" : "string"
          },
          "errorCode" : {
            "type" : "integer",
            "description" : "`0: OK (healthy) | 1: INFO | 2: WARNING | 3: ERROR (dangling or view generation call failed) | 4: UNKNOWN`",
            "format" : "int32"
          },
          "errorDescription" : {
            "type" : "string",
            "description" : "A human-readable value for the error that occurred, if one occurred."
          },
          "errorValue" : {
            "$ref" : "#/components/schemas/BTAppElementErrorCode"
          },
          "explodedViewId" : {
            "type" : "string"
          },
          "hasSecondaryViewDefinition" : {
            "type" : "boolean"
          },
          "hiddenLines" : {
            "type" : "string"
          },
          "ignoreFaultyParts" : {
            "type" : "boolean"
          },
          "includeHiddenInstances" : {
            "type" : "boolean"
          },
          "includeSurfaces" : {
            "type" : "boolean"
          },
          "includeWires" : {
            "type" : "boolean"
          },
          "isAlignedSection" : {
            "type" : "boolean"
          },
          "isBrokenOutSection" : {
            "type" : "boolean"
          },
          "isCopiedView" : {
            "type" : "boolean"
          },
          "isCropView" : {
            "type" : "boolean"
          },
          "isPartialSection" : {
            "type" : "boolean"
          },
          "isSectionOfAlignedSection" : {
            "type" : "boolean"
          },
          "isSectionOfSectionOnBase" : {
            "type" : "boolean"
          },
          "isSurface" : {
            "type" : "boolean"
          },
          "modelReferenceId" : {
            "type" : "string"
          },
          "modificationId" : {
            "type" : "string"
          },
          "namedPositionId" : {
            "type" : "string"
          },
          "occurrenceOrQueryToGeometryProperties" : {
            "type" : "object",
            "additionalProperties" : {
              "$ref" : "#/components/schemas/BTAppElementViewGeometryProperties-1100"
            }
          },
          "offsetSectionPoints" : {
            "type" : "array",
            "items" : {
              "type" : "number",
              "format" : "double"
            }
          },
          "parentChangeId" : {
            "type" : "string"
          },
          "parentViewId" : {
            "type" : "string"
          },
          "perspective" : {
            "type" : "boolean"
          },
          "projectionAngle" : {
            "type" : "string"
          },
          "qualityOption" : {
            "type" : "integer",
            "format" : "int32"
          },
          "renderSketches" : {
            "type" : "boolean"
          },
          "sectionId" : {
            "type" : "string"
          },
          "showAutoCenterlines" : {
            "type" : "boolean"
          },
          "showAutoCentermarks" : {
            "type" : "boolean"
          },
          "showCutGeomOnly" : {
            "type" : "boolean"
          },
          "showTangentLines" : {
            "type" : "boolean"
          },
          "showThreads" : {
            "type" : "boolean"
          },
          "showViewingPlane" : {
            "type" : "boolean"
          },
          "simplificationOption" : {
            "type" : "integer",
            "format" : "int32"
          },
          "simplificationThreshold" : {
            "type" : "number",
            "format" : "double"
          },
          "useParentViewSectionData" : {
            "type" : "boolean"
          },
          "viewDirection" : {
            "type" : "array",
            "items" : {
              "type" : "number",
              "format" : "double"
            }
          },
          "viewId" : {
            "type" : "string"
          },
          "viewMatrix" : {
            "type" : "array",
            "items" : {
              "type" : "number",
              "format" : "double"
            }
          },
          "viewVersion" : {
            "type" : "integer",
            "format" : "int32"
          }
        }
      },
      "BTAppElementBasicInfo" : {
        "type" : "object",
        "properties" : {
          "changeId" : {
            "type" : "string"
          },
          "errorCode" : {
            "type" : "integer",
[...]
