/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * API version: 1.113
 * Contact: api-support@onshape.zendesk.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package onshape

import (
	"encoding/json"
)

// BTMConfigurationParameterEnum105 struct for BTMConfigurationParameterEnum105
type BTMConfigurationParameterEnum105 struct {
	BTMConfigurationParameter819
	BtType *string `json:"btType,omitempty"`
	DefaultValue *string `json:"defaultValue,omitempty"`
	EnumName *string `json:"enumName,omitempty"`
	Namespace *string `json:"namespace,omitempty"`
	OptionIds *[]string `json:"optionIds,omitempty"`
	Options *[]BTMEnumOption592 `json:"options,omitempty"`
}

// NewBTMConfigurationParameterEnum105 instantiates a new BTMConfigurationParameterEnum105 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBTMConfigurationParameterEnum105() *BTMConfigurationParameterEnum105 {
	this := BTMConfigurationParameterEnum105{}
	return &this
}

// NewBTMConfigurationParameterEnum105WithDefaults instantiates a new BTMConfigurationParameterEnum105 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBTMConfigurationParameterEnum105WithDefaults() *BTMConfigurationParameterEnum105 {
	this := BTMConfigurationParameterEnum105{}
	return &this
}

// GetBtType returns the BtType field value if set, zero value otherwise.
func (o *BTMConfigurationParameterEnum105) GetBtType() string {
	if o == nil || o.BtType == nil {
		var ret string
		return ret
	}
	return *o.BtType
}

// GetBtTypeOk returns a tuple with the BtType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTMConfigurationParameterEnum105) GetBtTypeOk() (*string, bool) {
	if o == nil || o.BtType == nil {
		return nil, false
	}
	return o.BtType, true
}

// HasBtType returns a boolean if a field has been set.
func (o *BTMConfigurationParameterEnum105) HasBtType() bool {
	if o != nil && o.BtType != nil {
		return true
	}

	return false
}

// SetBtType gets a reference to the given string and assigns it to the BtType field.
func (o *BTMConfigurationParameterEnum105) SetBtType(v string) {
	o.BtType = &v
}

// GetDefaultValue returns the DefaultValue field value if set, zero value otherwise.
func (o *BTMConfigurationParameterEnum105) GetDefaultValue() string {
	if o == nil || o.DefaultValue == nil {
		var ret string
		return ret
	}
	return *o.DefaultValue
}

// GetDefaultValueOk returns a tuple with the DefaultValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTMConfigurationParameterEnum105) GetDefaultValueOk() (*string, bool) {
	if o == nil || o.DefaultValue == nil {
		return nil, false
	}
	return o.DefaultValue, true
}

// HasDefaultValue returns a boolean if a field has been set.
func (o *BTMConfigurationParameterEnum105) HasDefaultValue() bool {
	if o != nil && o.DefaultValue != nil {
		return true
	}

	return false
}

// SetDefaultValue gets a reference to the given string and assigns it to the DefaultValue field.
func (o *BTMConfigurationParameterEnum105) SetDefaultValue(v string) {
	o.DefaultValue = &v
}

// GetEnumName returns the EnumName field value if set, zero value otherwise.
func (o *BTMConfigurationParameterEnum105) GetEnumName() string {
	if o == nil || o.EnumName == nil {
		var ret string
		return ret
	}
	return *o.EnumName
}

// GetEnumNameOk returns a tuple with the EnumName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTMConfigurationParameterEnum105) GetEnumNameOk() (*string, bool) {
	if o == nil || o.EnumName == nil {
		return nil, false
	}
	return o.EnumName, true
}

// HasEnumName returns a boolean if a field has been set.
func (o *BTMConfigurationParameterEnum105) HasEnumName() bool {
	if o != nil && o.EnumName != nil {
		return true
	}

	return false
}

// SetEnumName gets a reference to the given string and assigns it to the EnumName field.
func (o *BTMConfigurationParameterEnum105) SetEnumName(v string) {
	o.EnumName = &v
}

// GetNamespace returns the Namespace field value if set, zero value otherwise.
func (o *BTMConfigurationParameterEnum105) GetNamespace() string {
	if o == nil || o.Namespace == nil {
		var ret string
		return ret
	}
	return *o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTMConfigurationParameterEnum105) GetNamespaceOk() (*string, bool) {
	if o == nil || o.Namespace == nil {
		return nil, false
	}
	return o.Namespace, true
}

// HasNamespace returns a boolean if a field has been set.
func (o *BTMConfigurationParameterEnum105) HasNamespace() bool {
	if o != nil && o.Namespace != nil {
		return true
	}

	return false
}

// SetNamespace gets a reference to the given string and assigns it to the Namespace field.
func (o *BTMConfigurationParameterEnum105) SetNamespace(v string) {
	o.Namespace = &v
}

// GetOptionIds returns the OptionIds field value if set, zero value otherwise.
func (o *BTMConfigurationParameterEnum105) GetOptionIds() []string {
	if o == nil || o.OptionIds == nil {
		var ret []string
		return ret
	}
	return *o.OptionIds
}

// GetOptionIdsOk returns a tuple with the OptionIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTMConfigurationParameterEnum105) GetOptionIdsOk() (*[]string, bool) {
	if o == nil || o.OptionIds == nil {
		return nil, false
	}
	return o.OptionIds, true
}

// HasOptionIds returns a boolean if a field has been set.
func (o *BTMConfigurationParameterEnum105) HasOptionIds() bool {
	if o != nil && o.OptionIds != nil {
		return true
	}

	return false
}

// SetOptionIds gets a reference to the given []string and assigns it to the OptionIds field.
func (o *BTMConfigurationParameterEnum105) SetOptionIds(v []string) {
	o.OptionIds = &v
}

// GetOptions returns the Options field value if set, zero value otherwise.
func (o *BTMConfigurationParameterEnum105) GetOptions() []BTMEnumOption592 {
	if o == nil || o.Options == nil {
		var ret []BTMEnumOption592
		return ret
	}
	return *o.Options
}

// GetOptionsOk returns a tuple with the Options field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTMConfigurationParameterEnum105) GetOptionsOk() (*[]BTMEnumOption592, bool) {
	if o == nil || o.Options == nil {
		return nil, false
	}
	return o.Options, true
}

// HasOptions returns a boolean if a field has been set.
func (o *BTMConfigurationParameterEnum105) HasOptions() bool {
	if o != nil && o.Options != nil {
		return true
	}

	return false
}

// SetOptions gets a reference to the given []BTMEnumOption592 and assigns it to the Options field.
func (o *BTMConfigurationParameterEnum105) SetOptions(v []BTMEnumOption592) {
	o.Options = &v
}

func (o BTMConfigurationParameterEnum105) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedBTMConfigurationParameter819, errBTMConfigurationParameter819 := json.Marshal(o.BTMConfigurationParameter819)
	if errBTMConfigurationParameter819 != nil {
		return []byte{}, errBTMConfigurationParameter819
	}
	errBTMConfigurationParameter819 = json.Unmarshal([]byte(serializedBTMConfigurationParameter819), &toSerialize)
	if errBTMConfigurationParameter819 != nil {
		return []byte{}, errBTMConfigurationParameter819
	}
	if o.BtType != nil {
		toSerialize["btType"] = o.BtType
	}
	if o.DefaultValue != nil {
		toSerialize["defaultValue"] = o.DefaultValue
	}
	if o.EnumName != nil {
		toSerialize["enumName"] = o.EnumName
	}
	if o.Namespace != nil {
		toSerialize["namespace"] = o.Namespace
	}
	if o.OptionIds != nil {
		toSerialize["optionIds"] = o.OptionIds
	}
	if o.Options != nil {
		toSerialize["options"] = o.Options
	}
	return json.Marshal(toSerialize)
}

type NullableBTMConfigurationParameterEnum105 struct {
	value *BTMConfigurationParameterEnum105
	isSet bool
}

func (v NullableBTMConfigurationParameterEnum105) Get() *BTMConfigurationParameterEnum105 {
	return v.value
}

func (v *NullableBTMConfigurationParameterEnum105) Set(val *BTMConfigurationParameterEnum105) {
	v.value = val
	v.isSet = true
}

func (v NullableBTMConfigurationParameterEnum105) IsSet() bool {
	return v.isSet
}

func (v *NullableBTMConfigurationParameterEnum105) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBTMConfigurationParameterEnum105(val *BTMConfigurationParameterEnum105) *NullableBTMConfigurationParameterEnum105 {
	return &NullableBTMConfigurationParameterEnum105{value: val, isSet: true}
}

func (v NullableBTMConfigurationParameterEnum105) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBTMConfigurationParameterEnum105) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
