/*
Onshape REST API

## Welcome to the Onshape REST API Explorer  **See the [API Explorer Guide](https://onshape-public.github.io/docs/api-intro/explorer/) for help navigating this page.**  ### Using this page 1. Sign in to your [Onshape](https://cad.onshape.com) account in another tab. 2. Click the `Try it out` button below. It toggles to a `Cancel` button when selected.  ### Authenticating To authenticate your calls, click the `Authorize` button. See [API Explorer Guide: Authentication](https://onshape-public.github.io/docs/api-intro/explorer/#authentication) for details. Calls made when authenticated via API Keys or OAuth count against your annual [API limits](https://onshape-public.github.io/docs/auth/limits/#annual-api-call-limits). * **Tip:** To ensure the current session isn't used when trying other authentication techniques, make sure to [remove the Onshape cookie](https://support.google.com/chrome/answer/95647#zippy=%2Cdelete-cookies-from-a-site) as per the instructions for your browser, or use a private or incognito window.  ### Additional resources  * [Onshape API Guide](https://onshape-public.github.io/docs/): Our full suite of developer guides, to be used as an accompaniment to this API Explorer. * [Onshape Developer Portal](https://cad.onshape.com/appstore/dev-portal): The Onshape portal for managing your API keys, OAuth2 credentials, your Onshape applications, and your Onshape App Store entries. * [Authentication Guide](https://onshape-public.github.io/docs/auth/): Our guide to using API keys, request signatures, and OAuth2 in your Onshape applications.

Contact: api-support@onshape.zendesk.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package onshape

import (
	"encoding/json"
)

// BTAssemblyParametricInstanceInfo Parametric instance description.
type BTAssemblyParametricInstanceInfo struct {
	// Child instances.
	Children []BTAssemblyParametricInstanceChildInfo `json:"children,omitempty"`
	// Id of the Part Studio instance.
	Id *string `json:"id,omitempty"`
	// Name of the parametric instance.
	Name *string `json:"name,omitempty"`
	// If the parametric is suppressed.
	Suppressed *bool `json:"suppressed,omitempty"`
	// Type of parametric instance.
	Type *string `json:"type,omitempty"`
}

// NewBTAssemblyParametricInstanceInfo instantiates a new BTAssemblyParametricInstanceInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBTAssemblyParametricInstanceInfo() *BTAssemblyParametricInstanceInfo {
	this := BTAssemblyParametricInstanceInfo{}
	return &this
}

// NewBTAssemblyParametricInstanceInfoWithDefaults instantiates a new BTAssemblyParametricInstanceInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBTAssemblyParametricInstanceInfoWithDefaults() *BTAssemblyParametricInstanceInfo {
	this := BTAssemblyParametricInstanceInfo{}
	return &this
}

// GetChildren returns the Children field value if set, zero value otherwise.
func (o *BTAssemblyParametricInstanceInfo) GetChildren() []BTAssemblyParametricInstanceChildInfo {
	if o == nil || o.Children == nil {
		var ret []BTAssemblyParametricInstanceChildInfo
		return ret
	}
	return o.Children
}

// GetChildrenOk returns a tuple with the Children field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTAssemblyParametricInstanceInfo) GetChildrenOk() ([]BTAssemblyParametricInstanceChildInfo, bool) {
	if o == nil || o.Children == nil {
		return nil, false
	}
	return o.Children, true
}

// HasChildren returns a boolean if a field has been set.
func (o *BTAssemblyParametricInstanceInfo) HasChildren() bool {
	if o != nil && o.Children != nil {
		return true
	}

	return false
}

// SetChildren gets a reference to the given []BTAssemblyParametricInstanceChildInfo and assigns it to the Children field.
func (o *BTAssemblyParametricInstanceInfo) SetChildren(v []BTAssemblyParametricInstanceChildInfo) {
	o.Children = v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *BTAssemblyParametricInstanceInfo) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTAssemblyParametricInstanceInfo) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *BTAssemblyParametricInstanceInfo) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *BTAssemblyParametricInstanceInfo) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *BTAssemblyParametricInstanceInfo) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTAssemblyParametricInstanceInfo) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *BTAssemblyParametricInstanceInfo) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *BTAssemblyParametricInstanceInfo) SetName(v string) {
	o.Name = &v
}

// GetSuppressed returns the Suppressed field value if set, zero value otherwise.
func (o *BTAssemblyParametricInstanceInfo) GetSuppressed() bool {
	if o == nil || o.Suppressed == nil {
		var ret bool
		return ret
	}
	return *o.Suppressed
}

// GetSuppressedOk returns a tuple with the Suppressed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTAssemblyParametricInstanceInfo) GetSuppressedOk() (*bool, bool) {
	if o == nil || o.Suppressed == nil {
		return nil, false
	}
	return o.Suppressed, true
}

// HasSuppressed returns a boolean if a field has been set.
func (o *BTAssemblyParametricInstanceInfo) HasSuppressed() bool {
	if o != nil && o.Suppressed != nil {
		return true
	}

	return false
}

// SetSuppressed gets a reference to the given bool and assigns it to the Suppressed field.
func (o *BTAssemblyParametricInstanceInfo) SetSuppressed(v bool) {
	o.Suppressed = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *BTAssemblyParametricInstanceInfo) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTAssemblyParametricInstanceInfo) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *BTAssemblyParametricInstanceInfo) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *BTAssemblyParametricInstanceInfo) SetType(v string) {
	o.Type = &v
}

func (o BTAssemblyParametricInstanceInfo) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Children != nil {
		toSerialize["children"] = o.Children
	}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Suppressed != nil {
		toSerialize["suppressed"] = o.Suppressed
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	return json.Marshal(toSerialize)
}

type NullableBTAssemblyParametricInstanceInfo struct {
	value *BTAssemblyParametricInstanceInfo
	isSet bool
}

func (v NullableBTAssemblyParametricInstanceInfo) Get() *BTAssemblyParametricInstanceInfo {
	return v.value
}

func (v *NullableBTAssemblyParametricInstanceInfo) Set(val *BTAssemblyParametricInstanceInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableBTAssemblyParametricInstanceInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableBTAssemblyParametricInstanceInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBTAssemblyParametricInstanceInfo(val *BTAssemblyParametricInstanceInfo) *NullableBTAssemblyParametricInstanceInfo {
	return &NullableBTAssemblyParametricInstanceInfo{value: val, isSet: true}
}

func (v NullableBTAssemblyParametricInstanceInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBTAssemblyParametricInstanceInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
