/*
Onshape REST API

## Welcome to the Onshape REST API Explorer  To use this API explorer, sign in to your [Onshape](https://cad.onshape.com) account in another tab, then click the **Try it out** button below (it toggles to a **Cancel** button when selected).  See the **[API Explorer Guide](https://onshape-public.github.io/docs/api-intro/explorer/)** for help navigating this API Explorer, including **[authentication](https://onshape-public.github.io/docs/api-intro/explorer/#authentication)**.  **Tip:** To ensure the current session isn't used when trying other authentication techniques, make sure to [remove the Onshape cookie](https://support.google.com/chrome/answer/95647#zippy=%2Cdelete-cookies-from-a-site) as per the instructions for your browser. Alternatively, you can use a private or incognito window.  ## See Also  * [Onshape API Guide](https://onshape-public.github.io/docs/): Our full suite of developer guides, to be used as an accompaniment to this API Explorer. * [Onshape Developer Portal](https://dev-portal.onshape.com/): The Onshape portal for managing your API keys, OAuth2 credentials, your Onshape applications, and your Onshape App Store entries. * [Authentication Guide](https://onshape-public.github.io/docs/auth/): Our guide to using API keys, request signatures, and OAuth2 in  your Onshape applications.

API version: 1.175.29637-cebbc8d3a306
Contact: api-support@onshape.zendesk.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package onshape

import (
	"encoding/json"
)

// BTComputedConfigurationInputSpec2525 struct for BTComputedConfigurationInputSpec2525
type BTComputedConfigurationInputSpec2525 struct {
	BtType  *string `json:"btType,omitempty"`
	InputId *string `json:"inputId,omitempty"`
}

// NewBTComputedConfigurationInputSpec2525 instantiates a new BTComputedConfigurationInputSpec2525 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBTComputedConfigurationInputSpec2525() *BTComputedConfigurationInputSpec2525 {
	this := BTComputedConfigurationInputSpec2525{}
	return &this
}

// NewBTComputedConfigurationInputSpec2525WithDefaults instantiates a new BTComputedConfigurationInputSpec2525 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBTComputedConfigurationInputSpec2525WithDefaults() *BTComputedConfigurationInputSpec2525 {
	this := BTComputedConfigurationInputSpec2525{}
	return &this
}

// GetBtType returns the BtType field value if set, zero value otherwise.
func (o *BTComputedConfigurationInputSpec2525) GetBtType() string {
	if o == nil || o.BtType == nil {
		var ret string
		return ret
	}
	return *o.BtType
}

// GetBtTypeOk returns a tuple with the BtType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTComputedConfigurationInputSpec2525) GetBtTypeOk() (*string, bool) {
	if o == nil || o.BtType == nil {
		return nil, false
	}
	return o.BtType, true
}

// HasBtType returns a boolean if a field has been set.
func (o *BTComputedConfigurationInputSpec2525) HasBtType() bool {
	if o != nil && o.BtType != nil {
		return true
	}

	return false
}

// SetBtType gets a reference to the given string and assigns it to the BtType field.
func (o *BTComputedConfigurationInputSpec2525) SetBtType(v string) {
	o.BtType = &v
}

// GetInputId returns the InputId field value if set, zero value otherwise.
func (o *BTComputedConfigurationInputSpec2525) GetInputId() string {
	if o == nil || o.InputId == nil {
		var ret string
		return ret
	}
	return *o.InputId
}

// GetInputIdOk returns a tuple with the InputId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTComputedConfigurationInputSpec2525) GetInputIdOk() (*string, bool) {
	if o == nil || o.InputId == nil {
		return nil, false
	}
	return o.InputId, true
}

// HasInputId returns a boolean if a field has been set.
func (o *BTComputedConfigurationInputSpec2525) HasInputId() bool {
	if o != nil && o.InputId != nil {
		return true
	}

	return false
}

// SetInputId gets a reference to the given string and assigns it to the InputId field.
func (o *BTComputedConfigurationInputSpec2525) SetInputId(v string) {
	o.InputId = &v
}

func (o BTComputedConfigurationInputSpec2525) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.BtType != nil {
		toSerialize["btType"] = o.BtType
	}
	if o.InputId != nil {
		toSerialize["inputId"] = o.InputId
	}
	return json.Marshal(toSerialize)
}

type NullableBTComputedConfigurationInputSpec2525 struct {
	value *BTComputedConfigurationInputSpec2525
	isSet bool
}

func (v NullableBTComputedConfigurationInputSpec2525) Get() *BTComputedConfigurationInputSpec2525 {
	return v.value
}

func (v *NullableBTComputedConfigurationInputSpec2525) Set(val *BTComputedConfigurationInputSpec2525) {
	v.value = val
	v.isSet = true
}

func (v NullableBTComputedConfigurationInputSpec2525) IsSet() bool {
	return v.isSet
}

func (v *NullableBTComputedConfigurationInputSpec2525) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBTComputedConfigurationInputSpec2525(val *BTComputedConfigurationInputSpec2525) *NullableBTComputedConfigurationInputSpec2525 {
	return &NullableBTComputedConfigurationInputSpec2525{value: val, isSet: true}
}

func (v NullableBTComputedConfigurationInputSpec2525) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBTComputedConfigurationInputSpec2525) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
