/*
Onshape REST API

The Onshape REST API consumed by all client. # Authorization The simplest way to authorize and enable the **Try it out** functionality is to sign in to Onshape and use the current session. The **Authorize** button enables other authorization techniques. To ensure the current session isn't used when trying other authentication techniques, make sure to remove the Onshape cookie as per the instructions for your particular browser. Alternatively, a private or incognito window may be used. Here's [how to remove a specific cookie on Chrome](https://support.google.com/chrome/answer/95647#zippy=%2Cdelete-cookies-from-a-site). - **Current Session** authorization is enabled by default if the browser is already signed in to [Onshape](/). - **OAuth2** authorization uses an Onshape OAuth2 app created on the [Onshape Developer Portal](https://dev-portal.onshape.com/oauthApps). The redirect URL field should include `https://cad.onshape.com/glassworks/explorer/oauth2-redirect.html`. - **API Key** authorization using basic authentication is also available. The keys can be generated in the [Onshape Developer Portal](https://dev-portal.onshape.com/keys). In the authentication dialog, enter the access key in the `Username` field, and enter the secret key in the `Password` field. Basic authentication should only be used during the development process since sharing API Keys provides the same level of access as a username and password.

API version: 1.154.6820-1bef41f9cc03
Contact: api-support@onshape.zendesk.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package onshape

import (
	"encoding/json"
)

// BTBExportModelParams struct for BTBExportModelParams
type BTBExportModelParams struct {
	AngleTolerance               *float64 `json:"angleTolerance,omitempty"`
	BatchFlatPatterns            *bool    `json:"batchFlatPatterns,omitempty"`
	ChordTolerance               *float64 `json:"chordTolerance,omitempty"`
	CloudObjectId                *string  `json:"cloudObjectId,omitempty"`
	CloudStorageAccountId        *string  `json:"cloudStorageAccountId,omitempty"`
	Configuration                *string  `json:"configuration,omitempty"`
	DeepSearchForForeignData     *bool    `json:"deepSearchForForeignData,omitempty"`
	DestinationName              *string  `json:"destinationName,omitempty"`
	DocumentId                   string   `json:"documentId"`
	DocumentVersionId            *string  `json:"documentVersionId,omitempty"`
	ElementId                    *string  `json:"elementId,omitempty"`
	ElementIds                   *string  `json:"elementIds,omitempty"`
	EmailLink                    *bool    `json:"emailLink,omitempty"`
	EmailMessage                 *string  `json:"emailMessage,omitempty"`
	EmailSubject                 *string  `json:"emailSubject,omitempty"`
	EmailTo                      *string  `json:"emailTo,omitempty"`
	ExtractToS3                  *bool    `json:"extractToS3,omitempty"`
	FeatureIds                   *string  `json:"featureIds,omitempty"`
	Flatten                      *bool    `json:"flatten,omitempty"`
	Format                       string   `json:"format"`
	FromUserId                   *string  `json:"fromUserId,omitempty"`
	Grouping                     *string  `json:"grouping,omitempty"`
	IncludeBendCenterlines       *bool    `json:"includeBendCenterlines,omitempty"`
	IncludeBendLines             *bool    `json:"includeBendLines,omitempty"`
	IncludeComments              *bool    `json:"includeComments,omitempty"`
	IncludeContentCaptures       *bool    `json:"includeContentCaptures,omitempty"`
	IncludeCustomPropertiesData  *bool    `json:"includeCustomPropertiesData,omitempty"`
	IncludeExportIds             *bool    `json:"includeExportIds,omitempty"`
	IncludeForeignData           *bool    `json:"includeForeignData,omitempty"`
	IncludeItemsData             *bool    `json:"includeItemsData,omitempty"`
	IncludeLinkedDocuments       *bool    `json:"includeLinkedDocuments,omitempty"`
	IncludeReleaseManagementData *bool    `json:"includeReleaseManagementData,omitempty"`
	IncludeSketches              *bool    `json:"includeSketches,omitempty"`
	IncludeStd                   *bool    `json:"includeStd,omitempty"`
	IncludeThumbnails            *bool    `json:"includeThumbnails,omitempty"`
	IsPartingOut                 *bool    `json:"isPartingOut,omitempty"`
	LinkDocumentId               *string  `json:"linkDocumentId,omitempty"`
	LinkDocumentWorkspaceId      *string  `json:"linkDocumentWorkspaceId,omitempty"`
	LinkedDocumentSubSetId       *string  `json:"linkedDocumentSubSetId,omitempty"`
	MaxFacetWidth                *float64 `json:"maxFacetWidth,omitempty"`
	Microversion                 *string  `json:"microversion,omitempty"`
	MinFacetWidth                *float64 `json:"minFacetWidth,omitempty"`
	Mode                         *string  `json:"mode,omitempty"`
	PartIds                      *string  `json:"partIds,omitempty"`
	PartQuery                    *string  `json:"partQuery,omitempty"`
	Password                     *string  `json:"password,omitempty"`
	PasswordRequired             *bool    `json:"passwordRequired,omitempty"`
	Resolution                   *string  `json:"resolution,omitempty"`
	Scale                        *float64 `json:"scale,omitempty"`
	SendCopyToMe                 *bool    `json:"sendCopyToMe,omitempty"`
	SheetMetalFlat               *bool    `json:"sheetMetalFlat,omitempty"`
	SplinesAsPolylines           *bool    `json:"splinesAsPolylines,omitempty"`
	StoreInDocument              *bool    `json:"storeInDocument,omitempty"`
	TriggerAutoDownload          *bool    `json:"triggerAutoDownload,omitempty"`
	Units                        *string  `json:"units,omitempty"`
	UserId                       *string  `json:"userId,omitempty"`
	ValidForDays                 *int32   `json:"validForDays,omitempty"`
	Version                      *string  `json:"version,omitempty"`
	View                         *string  `json:"view,omitempty"`
	WorkspaceId                  *string  `json:"workspaceId,omitempty"`
	ZipSingleFileOutput          *bool    `json:"zipSingleFileOutput,omitempty"`
}

// NewBTBExportModelParams instantiates a new BTBExportModelParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBTBExportModelParams(documentId string, format string) *BTBExportModelParams {
	this := BTBExportModelParams{}
	this.DocumentId = documentId
	this.Format = format
	return &this
}

// NewBTBExportModelParamsWithDefaults instantiates a new BTBExportModelParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBTBExportModelParamsWithDefaults() *BTBExportModelParams {
	this := BTBExportModelParams{}
	return &this
}

// GetAngleTolerance returns the AngleTolerance field value if set, zero value otherwise.
func (o *BTBExportModelParams) GetAngleTolerance() float64 {
	if o == nil || o.AngleTolerance == nil {
		var ret float64
		return ret
	}
	return *o.AngleTolerance
}

// GetAngleToleranceOk returns a tuple with the AngleTolerance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTBExportModelParams) GetAngleToleranceOk() (*float64, bool) {
	if o == nil || o.AngleTolerance == nil {
		return nil, false
	}
	return o.AngleTolerance, true
}

// HasAngleTolerance returns a boolean if a field has been set.
func (o *BTBExportModelParams) HasAngleTolerance() bool {
	if o != nil && o.AngleTolerance != nil {
		return true
	}

	return false
}

// SetAngleTolerance gets a reference to the given float64 and assigns it to the AngleTolerance field.
func (o *BTBExportModelParams) SetAngleTolerance(v float64) {
	o.AngleTolerance = &v
}

// GetBatchFlatPatterns returns the BatchFlatPatterns field value if set, zero value otherwise.
func (o *BTBExportModelParams) GetBatchFlatPatterns() bool {
	if o == nil || o.BatchFlatPatterns == nil {
		var ret bool
		return ret
	}
	return *o.BatchFlatPatterns
}

// GetBatchFlatPatternsOk returns a tuple with the BatchFlatPatterns field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTBExportModelParams) GetBatchFlatPatternsOk() (*bool, bool) {
	if o == nil || o.BatchFlatPatterns == nil {
		return nil, false
	}
	return o.BatchFlatPatterns, true
}

// HasBatchFlatPatterns returns a boolean if a field has been set.
func (o *BTBExportModelParams) HasBatchFlatPatterns() bool {
	if o != nil && o.BatchFlatPatterns != nil {
		return true
	}

	return false
}

// SetBatchFlatPatterns gets a reference to the given bool and assigns it to the BatchFlatPatterns field.
func (o *BTBExportModelParams) SetBatchFlatPatterns(v bool) {
	o.BatchFlatPatterns = &v
}

// GetChordTolerance returns the ChordTolerance field value if set, zero value otherwise.
func (o *BTBExportModelParams) GetChordTolerance() float64 {
	if o == nil || o.ChordTolerance == nil {
		var ret float64
		return ret
	}
	return *o.ChordTolerance
}

// GetChordToleranceOk returns a tuple with the ChordTolerance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTBExportModelParams) GetChordToleranceOk() (*float64, bool) {
	if o == nil || o.ChordTolerance == nil {
		return nil, false
	}
	return o.ChordTolerance, true
}

// HasChordTolerance returns a boolean if a field has been set.
func (o *BTBExportModelParams) HasChordTolerance() bool {
	if o != nil && o.ChordTolerance != nil {
		return true
	}

	return false
}

// SetChordTolerance gets a reference to the given float64 and assigns it to the ChordTolerance field.
func (o *BTBExportModelParams) SetChordTolerance(v float64) {
	o.ChordTolerance = &v
}

// GetCloudObjectId returns the CloudObjectId field value if set, zero value otherwise.
func (o *BTBExportModelParams) GetCloudObjectId() string {
	if o == nil || o.CloudObjectId == nil {
		var ret string
		return ret
	}
	return *o.CloudObjectId
}

// GetCloudObjectIdOk returns a tuple with the CloudObjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTBExportModelParams) GetCloudObjectIdOk() (*string, bool) {
	if o == nil || o.CloudObjectId == nil {
		return nil, false
	}
	return o.CloudObjectId, true
}

// HasCloudObjectId returns a boolean if a field has been set.
func (o *BTBExportModelParams) HasCloudObjectId() bool {
	if o != nil && o.CloudObjectId != nil {
		return true
	}

	return false
}

// SetCloudObjectId gets a reference to the given string and assigns it to the CloudObjectId field.
func (o *BTBExportModelParams) SetCloudObjectId(v string) {
	o.CloudObjectId = &v
}

// GetCloudStorageAccountId returns the CloudStorageAccountId field value if set, zero value otherwise.
func (o *BTBExportModelParams) GetCloudStorageAccountId() string {
	if o == nil || o.CloudStorageAccountId == nil {
		var ret string
		return ret
	}
	return *o.CloudStorageAccountId
}

// GetCloudStorageAccountIdOk returns a tuple with the CloudStorageAccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTBExportModelParams) GetCloudStorageAccountIdOk() (*string, bool) {
	if o == nil || o.CloudStorageAccountId == nil {
		return nil, false
	}
	return o.CloudStorageAccountId, true
}

// HasCloudStorageAccountId returns a boolean if a field has been set.
func (o *BTBExportModelParams) HasCloudStorageAccountId() bool {
	if o != nil && o.CloudStorageAccountId != nil {
		return true
	}

	return false
}

// SetCloudStorageAccountId gets a reference to the given string and assigns it to the CloudStorageAccountId field.
func (o *BTBExportModelParams) SetCloudStorageAccountId(v string) {
	o.CloudStorageAccountId = &v
}

// GetConfiguration returns the Configuration field value if set, zero value otherwise.
func (o *BTBExportModelParams) GetConfiguration() string {
	if o == nil || o.Configuration == nil {
		var ret string
		return ret
	}
	return *o.Configuration
}

// GetConfigurationOk returns a tuple with the Configuration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTBExportModelParams) GetConfigurationOk() (*string, bool) {
	if o == nil || o.Configuration == nil {
		return nil, false
	}
	return o.Configuration, true
}

// HasConfiguration returns a boolean if a field has been set.
func (o *BTBExportModelParams) HasConfiguration() bool {
	if o != nil && o.Configuration != nil {
		return true
	}

	return false
}

// SetConfiguration gets a reference to the given string and assigns it to the Configuration field.
func (o *BTBExportModelParams) SetConfiguration(v string) {
	o.Configuration = &v
}

// GetDeepSearchForForeignData returns the DeepSearchForForeignData field value if set, zero value otherwise.
func (o *BTBExportModelParams) GetDeepSearchForForeignData() bool {
	if o == nil || o.DeepSearchForForeignData == nil {
		var ret bool
		return ret
	}
	return *o.DeepSearchForForeignData
}

// GetDeepSearchForForeignDataOk returns a tuple with the DeepSearchForForeignData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTBExportModelParams) GetDeepSearchForForeignDataOk() (*bool, bool) {
	if o == nil || o.DeepSearchForForeignData == nil {
		return nil, false
	}
	return o.DeepSearchForForeignData, true
}

// HasDeepSearchForForeignData returns a boolean if a field has been set.
func (o *BTBExportModelParams) HasDeepSearchForForeignData() bool {
	if o != nil && o.DeepSearchForForeignData != nil {
		return true
	}

	return false
}

// SetDeepSearchForForeignData gets a reference to the given bool and assigns it to the DeepSearchForForeignData field.
func (o *BTBExportModelParams) SetDeepSearchForForeignData(v bool) {
	o.DeepSearchForForeignData = &v
}

// GetDestinationName returns the DestinationName field value if set, zero value otherwise.
func (o *BTBExportModelParams) GetDestinationName() string {
	if o == nil || o.DestinationName == nil {
		var ret string
		return ret
	}
	return *o.DestinationName
}

// GetDestinationNameOk returns a tuple with the DestinationName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTBExportModelParams) GetDestinationNameOk() (*string, bool) {
	if o == nil || o.DestinationName == nil {
		return nil, false
	}
	return o.DestinationName, true
}

// HasDestinationName returns a boolean if a field has been set.
func (o *BTBExportModelParams) HasDestinationName() bool {
	if o != nil && o.DestinationName != nil {
		return true
	}

	return false
}

// SetDestinationName gets a reference to the given string and assigns it to the DestinationName field.
func (o *BTBExportModelParams) SetDestinationName(v string) {
	o.DestinationName = &v
}

// GetDocumentId returns the DocumentId field value
func (o *BTBExportModelParams) GetDocumentId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DocumentId
}

// GetDocumentIdOk returns a tuple with the DocumentId field value
// and a boolean to check if the value has been set.
func (o *BTBExportModelParams) GetDocumentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DocumentId, true
}

// SetDocumentId sets field value
func (o *BTBExportModelParams) SetDocumentId(v string) {
	o.DocumentId = v
}

// GetDocumentVersionId returns the DocumentVersionId field value if set, zero value otherwise.
func (o *BTBExportModelParams) GetDocumentVersionId() string {
	if o == nil || o.DocumentVersionId == nil {
		var ret string
		return ret
	}
	return *o.DocumentVersionId
}

// GetDocumentVersionIdOk returns a tuple with the DocumentVersionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTBExportModelParams) GetDocumentVersionIdOk() (*string, bool) {
	if o == nil || o.DocumentVersionId == nil {
		return nil, false
	}
	return o.DocumentVersionId, true
}

// HasDocumentVersionId returns a boolean if a field has been set.
func (o *BTBExportModelParams) HasDocumentVersionId() bool {
	if o != nil && o.DocumentVersionId != nil {
		return true
	}

	return false
}

// SetDocumentVersionId gets a reference to the given string and assigns it to the DocumentVersionId field.
func (o *BTBExportModelParams) SetDocumentVersionId(v string) {
	o.DocumentVersionId = &v
}

// GetElementId returns the ElementId field value if set, zero value otherwise.
func (o *BTBExportModelParams) GetElementId() string {
	if o == nil || o.ElementId == nil {
		var ret string
		return ret
	}
	return *o.ElementId
}

// GetElementIdOk returns a tuple with the ElementId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTBExportModelParams) GetElementIdOk() (*string, bool) {
	if o == nil || o.ElementId == nil {
		return nil, false
	}
	return o.ElementId, true
}

// HasElementId returns a boolean if a field has been set.
func (o *BTBExportModelParams) HasElementId() bool {
	if o != nil && o.ElementId != nil {
		return true
	}

	return false
}

// SetElementId gets a reference to the given string and assigns it to the ElementId field.
func (o *BTBExportModelParams) SetElementId(v string) {
	o.ElementId = &v
}

// GetElementIds returns the ElementIds field value if set, zero value otherwise.
func (o *BTBExportModelParams) GetElementIds() string {
	if o == nil || o.ElementIds == nil {
		var ret string
		return ret
	}
	return *o.ElementIds
}

// GetElementIdsOk returns a tuple with the ElementIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTBExportModelParams) GetElementIdsOk() (*string, bool) {
	if o == nil || o.ElementIds == nil {
		return nil, false
	}
	return o.ElementIds, true
}

// HasElementIds returns a boolean if a field has been set.
func (o *BTBExportModelParams) HasElementIds() bool {
	if o != nil && o.ElementIds != nil {
		return true
	}

	return false
}

// SetElementIds gets a reference to the given string and assigns it to the ElementIds field.
func (o *BTBExportModelParams) SetElementIds(v string) {
	o.ElementIds = &v
}

// GetEmailLink returns the EmailLink field value if set, zero value otherwise.
func (o *BTBExportModelParams) GetEmailLink() bool {
	if o == nil || o.EmailLink == nil {
		var ret bool
		return ret
	}
	return *o.EmailLink
}

// GetEmailLinkOk returns a tuple with the EmailLink field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTBExportModelParams) GetEmailLinkOk() (*bool, bool) {
	if o == nil || o.EmailLink == nil {
		return nil, false
	}
	return o.EmailLink, true
}

// HasEmailLink returns a boolean if a field has been set.
func (o *BTBExportModelParams) HasEmailLink() bool {
	if o != nil && o.EmailLink != nil {
		return true
	}

	return false
}

// SetEmailLink gets a reference to the given bool and assigns it to the EmailLink field.
func (o *BTBExportModelParams) SetEmailLink(v bool) {
	o.EmailLink = &v
}

// GetEmailMessage returns the EmailMessage field value if set, zero value otherwise.
func (o *BTBExportModelParams) GetEmailMessage() string {
	if o == nil || o.EmailMessage == nil {
		var ret string
		return ret
	}
	return *o.EmailMessage
}

// GetEmailMessageOk returns a tuple with the EmailMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTBExportModelParams) GetEmailMessageOk() (*string, bool) {
	if o == nil || o.EmailMessage == nil {
		return nil, false
	}
	return o.EmailMessage, true
}

// HasEmailMessage returns a boolean if a field has been set.
func (o *BTBExportModelParams) HasEmailMessage() bool {
	if o != nil && o.EmailMessage != nil {
		return true
	}

	return false
}

// SetEmailMessage gets a reference to the given string and assigns it to the EmailMessage field.
func (o *BTBExportModelParams) SetEmailMessage(v string) {
	o.EmailMessage = &v
}

// GetEmailSubject returns the EmailSubject field value if set, zero value otherwise.
func (o *BTBExportModelParams) GetEmailSubject() string {
	if o == nil || o.EmailSubject == nil {
		var ret string
		return ret
	}
	return *o.EmailSubject
}

// GetEmailSubjectOk returns a tuple with the EmailSubject field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTBExportModelParams) GetEmailSubjectOk() (*string, bool) {
	if o == nil || o.EmailSubject == nil {
		return nil, false
	}
	return o.EmailSubject, true
}

// HasEmailSubject returns a boolean if a field has been set.
func (o *BTBExportModelParams) HasEmailSubject() bool {
	if o != nil && o.EmailSubject != nil {
		return true
	}

	return false
}

// SetEmailSubject gets a reference to the given string and assigns it to the EmailSubject field.
func (o *BTBExportModelParams) SetEmailSubject(v string) {
	o.EmailSubject = &v
}

// GetEmailTo returns the EmailTo field value if set, zero value otherwise.
func (o *BTBExportModelParams) GetEmailTo() string {
	if o == nil || o.EmailTo == nil {
		var ret string
		return ret
	}
	return *o.EmailTo
}

// GetEmailToOk returns a tuple with the EmailTo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTBExportModelParams) GetEmailToOk() (*string, bool) {
	if o == nil || o.EmailTo == nil {
		return nil, false
	}
	return o.EmailTo, true
}

// HasEmailTo returns a boolean if a field has been set.
func (o *BTBExportModelParams) HasEmailTo() bool {
	if o != nil && o.EmailTo != nil {
		return true
	}

	return false
}

// SetEmailTo gets a reference to the given string and assigns it to the EmailTo field.
func (o *BTBExportModelParams) SetEmailTo(v string) {
	o.EmailTo = &v
}

// GetExtractToS3 returns the ExtractToS3 field value if set, zero value otherwise.
func (o *BTBExportModelParams) GetExtractToS3() bool {
	if o == nil || o.ExtractToS3 == nil {
		var ret bool
		return ret
	}
	return *o.ExtractToS3
}

// GetExtractToS3Ok returns a tuple with the ExtractToS3 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTBExportModelParams) GetExtractToS3Ok() (*bool, bool) {
	if o == nil || o.ExtractToS3 == nil {
		return nil, false
	}
	return o.ExtractToS3, true
}

// HasExtractToS3 returns a boolean if a field has been set.
func (o *BTBExportModelParams) HasExtractToS3() bool {
	if o != nil && o.ExtractToS3 != nil {
		return true
	}

	return false
}

// SetExtractToS3 gets a reference to the given bool and assigns it to the ExtractToS3 field.
func (o *BTBExportModelParams) SetExtractToS3(v bool) {
	o.ExtractToS3 = &v
}

// GetFeatureIds returns the FeatureIds field value if set, zero value otherwise.
func (o *BTBExportModelParams) GetFeatureIds() string {
	if o == nil || o.FeatureIds == nil {
		var ret string
		return ret
	}
	return *o.FeatureIds
}

// GetFeatureIdsOk returns a tuple with the FeatureIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTBExportModelParams) GetFeatureIdsOk() (*string, bool) {
	if o == nil || o.FeatureIds == nil {
		return nil, false
	}
	return o.FeatureIds, true
}

// HasFeatureIds returns a boolean if a field has been set.
func (o *BTBExportModelParams) HasFeatureIds() bool {
	if o != nil && o.FeatureIds != nil {
		return true
	}

	return false
}

// SetFeatureIds gets a reference to the given string and assigns it to the FeatureIds field.
func (o *BTBExportModelParams) SetFeatureIds(v string) {
	o.FeatureIds = &v
}

// GetFlatten returns the Flatten field value if set, zero value otherwise.
func (o *BTBExportModelParams) GetFlatten() bool {
	if o == nil || o.Flatten == nil {
		var ret bool
		return ret
	}
	return *o.Flatten
}

// GetFlattenOk returns a tuple with the Flatten field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTBExportModelParams) GetFlattenOk() (*bool, bool) {
	if o == nil || o.Flatten == nil {
		return nil, false
	}
	return o.Flatten, true
}

// HasFlatten returns a boolean if a field has been set.
func (o *BTBExportModelParams) HasFlatten() bool {
	if o != nil && o.Flatten != nil {
		return true
	}

	return false
}

// SetFlatten gets a reference to the given bool and assigns it to the Flatten field.
func (o *BTBExportModelParams) SetFlatten(v bool) {
	o.Flatten = &v
}

// GetFormat returns the Format field value
func (o *BTBExportModelParams) GetFormat() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Format
}

// GetFormatOk returns a tuple with the Format field value
// and a boolean to check if the value has been set.
func (o *BTBExportModelParams) GetFormatOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Format, true
}

// SetFormat sets field value
func (o *BTBExportModelParams) SetFormat(v string) {
	o.Format = v
}

// GetFromUserId returns the FromUserId field value if set, zero value otherwise.
func (o *BTBExportModelParams) GetFromUserId() string {
	if o == nil || o.FromUserId == nil {
		var ret string
		return ret
	}
	return *o.FromUserId
}

// GetFromUserIdOk returns a tuple with the FromUserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTBExportModelParams) GetFromUserIdOk() (*string, bool) {
	if o == nil || o.FromUserId == nil {
		return nil, false
	}
	return o.FromUserId, true
}

// HasFromUserId returns a boolean if a field has been set.
func (o *BTBExportModelParams) HasFromUserId() bool {
	if o != nil && o.FromUserId != nil {
		return true
	}

	return false
}

// SetFromUserId gets a reference to the given string and assigns it to the FromUserId field.
func (o *BTBExportModelParams) SetFromUserId(v string) {
	o.FromUserId = &v
}

// GetGrouping returns the Grouping field value if set, zero value otherwise.
func (o *BTBExportModelParams) GetGrouping() string {
	if o == nil || o.Grouping == nil {
		var ret string
		return ret
	}
	return *o.Grouping
}

// GetGroupingOk returns a tuple with the Grouping field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTBExportModelParams) GetGroupingOk() (*string, bool) {
	if o == nil || o.Grouping == nil {
		return nil, false
	}
	return o.Grouping, true
}

// HasGrouping returns a boolean if a field has been set.
func (o *BTBExportModelParams) HasGrouping() bool {
	if o != nil && o.Grouping != nil {
		return true
	}

	return false
}

// SetGrouping gets a reference to the given string and assigns it to the Grouping field.
func (o *BTBExportModelParams) SetGrouping(v string) {
	o.Grouping = &v
}

// GetIncludeBendCenterlines returns the IncludeBendCenterlines field value if set, zero value otherwise.
func (o *BTBExportModelParams) GetIncludeBendCenterlines() bool {
	if o == nil || o.IncludeBendCenterlines == nil {
		var ret bool
		return ret
	}
	return *o.IncludeBendCenterlines
}

// GetIncludeBendCenterlinesOk returns a tuple with the IncludeBendCenterlines field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTBExportModelParams) GetIncludeBendCenterlinesOk() (*bool, bool) {
	if o == nil || o.IncludeBendCenterlines == nil {
		return nil, false
	}
	return o.IncludeBendCenterlines, true
}

// HasIncludeBendCenterlines returns a boolean if a field has been set.
func (o *BTBExportModelParams) HasIncludeBendCenterlines() bool {
	if o != nil && o.IncludeBendCenterlines != nil {
		return true
	}

	return false
}

// SetIncludeBendCenterlines gets a reference to the given bool and assigns it to the IncludeBendCenterlines field.
func (o *BTBExportModelParams) SetIncludeBendCenterlines(v bool) {
	o.IncludeBendCenterlines = &v
}

// GetIncludeBendLines returns the IncludeBendLines field value if set, zero value otherwise.
func (o *BTBExportModelParams) GetIncludeBendLines() bool {
	if o == nil || o.IncludeBendLines == nil {
		var ret bool
		return ret
	}
	return *o.IncludeBendLines
}

// GetIncludeBendLinesOk returns a tuple with the IncludeBendLines field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTBExportModelParams) GetIncludeBendLinesOk() (*bool, bool) {
	if o == nil || o.IncludeBendLines == nil {
		return nil, false
	}
	return o.IncludeBendLines, true
}

// HasIncludeBendLines returns a boolean if a field has been set.
func (o *BTBExportModelParams) HasIncludeBendLines() bool {
	if o != nil && o.IncludeBendLines != nil {
		return true
	}

	return false
}

// SetIncludeBendLines gets a reference to the given bool and assigns it to the IncludeBendLines field.
func (o *BTBExportModelParams) SetIncludeBendLines(v bool) {
	o.IncludeBendLines = &v
}

// GetIncludeComments returns the IncludeComments field value if set, zero value otherwise.
func (o *BTBExportModelParams) GetIncludeComments() bool {
	if o == nil || o.IncludeComments == nil {
		var ret bool
		return ret
	}
	return *o.IncludeComments
}

// GetIncludeCommentsOk returns a tuple with the IncludeComments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTBExportModelParams) GetIncludeCommentsOk() (*bool, bool) {
	if o == nil || o.IncludeComments == nil {
		return nil, false
	}
	return o.IncludeComments, true
}

// HasIncludeComments returns a boolean if a field has been set.
func (o *BTBExportModelParams) HasIncludeComments() bool {
	if o != nil && o.IncludeComments != nil {
		return true
	}

	return false
}

// SetIncludeComments gets a reference to the given bool and assigns it to the IncludeComments field.
func (o *BTBExportModelParams) SetIncludeComments(v bool) {
	o.IncludeComments = &v
}

// GetIncludeContentCaptures returns the IncludeContentCaptures field value if set, zero value otherwise.
func (o *BTBExportModelParams) GetIncludeContentCaptures() bool {
	if o == nil || o.IncludeContentCaptures == nil {
		var ret bool
		return ret
	}
	return *o.IncludeContentCaptures
}

// GetIncludeContentCapturesOk returns a tuple with the IncludeContentCaptures field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTBExportModelParams) GetIncludeContentCapturesOk() (*bool, bool) {
	if o == nil || o.IncludeContentCaptures == nil {
		return nil, false
	}
	return o.IncludeContentCaptures, true
}

// HasIncludeContentCaptures returns a boolean if a field has been set.
func (o *BTBExportModelParams) HasIncludeContentCaptures() bool {
	if o != nil && o.IncludeContentCaptures != nil {
		return true
	}

	return false
}

// SetIncludeContentCaptures gets a reference to the given bool and assigns it to the IncludeContentCaptures field.
func (o *BTBExportModelParams) SetIncludeContentCaptures(v bool) {
	o.IncludeContentCaptures = &v
}

// GetIncludeCustomPropertiesData returns the IncludeCustomPropertiesData field value if set, zero value otherwise.
func (o *BTBExportModelParams) GetIncludeCustomPropertiesData() bool {
	if o == nil || o.IncludeCustomPropertiesData == nil {
		var ret bool
		return ret
	}
	return *o.IncludeCustomPropertiesData
}

// GetIncludeCustomPropertiesDataOk returns a tuple with the IncludeCustomPropertiesData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTBExportModelParams) GetIncludeCustomPropertiesDataOk() (*bool, bool) {
	if o == nil || o.IncludeCustomPropertiesData == nil {
		return nil, false
	}
	return o.IncludeCustomPropertiesData, true
}

// HasIncludeCustomPropertiesData returns a boolean if a field has been set.
func (o *BTBExportModelParams) HasIncludeCustomPropertiesData() bool {
	if o != nil && o.IncludeCustomPropertiesData != nil {
		return true
	}

	return false
}

// SetIncludeCustomPropertiesData gets a reference to the given bool and assigns it to the IncludeCustomPropertiesData field.
func (o *BTBExportModelParams) SetIncludeCustomPropertiesData(v bool) {
	o.IncludeCustomPropertiesData = &v
}

// GetIncludeExportIds returns the IncludeExportIds field value if set, zero value otherwise.
func (o *BTBExportModelParams) GetIncludeExportIds() bool {
	if o == nil || o.IncludeExportIds == nil {
		var ret bool
		return ret
	}
	return *o.IncludeExportIds
}

// GetIncludeExportIdsOk returns a tuple with the IncludeExportIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTBExportModelParams) GetIncludeExportIdsOk() (*bool, bool) {
	if o == nil || o.IncludeExportIds == nil {
		return nil, false
	}
	return o.IncludeExportIds, true
}

// HasIncludeExportIds returns a boolean if a field has been set.
func (o *BTBExportModelParams) HasIncludeExportIds() bool {
	if o != nil && o.IncludeExportIds != nil {
		return true
	}

	return false
}

// SetIncludeExportIds gets a reference to the given bool and assigns it to the IncludeExportIds field.
func (o *BTBExportModelParams) SetIncludeExportIds(v bool) {
	o.IncludeExportIds = &v
}

// GetIncludeForeignData returns the IncludeForeignData field value if set, zero value otherwise.
func (o *BTBExportModelParams) GetIncludeForeignData() bool {
	if o == nil || o.IncludeForeignData == nil {
		var ret bool
		return ret
	}
	return *o.IncludeForeignData
}

// GetIncludeForeignDataOk returns a tuple with the IncludeForeignData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTBExportModelParams) GetIncludeForeignDataOk() (*bool, bool) {
	if o == nil || o.IncludeForeignData == nil {
		return nil, false
	}
	return o.IncludeForeignData, true
}

// HasIncludeForeignData returns a boolean if a field has been set.
func (o *BTBExportModelParams) HasIncludeForeignData() bool {
	if o != nil && o.IncludeForeignData != nil {
		return true
	}

	return false
}

// SetIncludeForeignData gets a reference to the given bool and assigns it to the IncludeForeignData field.
func (o *BTBExportModelParams) SetIncludeForeignData(v bool) {
	o.IncludeForeignData = &v
}

// GetIncludeItemsData returns the IncludeItemsData field value if set, zero value otherwise.
func (o *BTBExportModelParams) GetIncludeItemsData() bool {
	if o == nil || o.IncludeItemsData == nil {
		var ret bool
		return ret
	}
	return *o.IncludeItemsData
}

// GetIncludeItemsDataOk returns a tuple with the IncludeItemsData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTBExportModelParams) GetIncludeItemsDataOk() (*bool, bool) {
	if o == nil || o.IncludeItemsData == nil {
		return nil, false
	}
	return o.IncludeItemsData, true
}

// HasIncludeItemsData returns a boolean if a field has been set.
func (o *BTBExportModelParams) HasIncludeItemsData() bool {
	if o != nil && o.IncludeItemsData != nil {
		return true
	}

	return false
}

// SetIncludeItemsData gets a reference to the given bool and assigns it to the IncludeItemsData field.
func (o *BTBExportModelParams) SetIncludeItemsData(v bool) {
	o.IncludeItemsData = &v
}

// GetIncludeLinkedDocuments returns the IncludeLinkedDocuments field value if set, zero value otherwise.
func (o *BTBExportModelParams) GetIncludeLinkedDocuments() bool {
	if o == nil || o.IncludeLinkedDocuments == nil {
		var ret bool
		return ret
	}
	return *o.IncludeLinkedDocuments
}

// GetIncludeLinkedDocumentsOk returns a tuple with the IncludeLinkedDocuments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTBExportModelParams) GetIncludeLinkedDocumentsOk() (*bool, bool) {
	if o == nil || o.IncludeLinkedDocuments == nil {
		return nil, false
	}
	return o.IncludeLinkedDocuments, true
}

// HasIncludeLinkedDocuments returns a boolean if a field has been set.
func (o *BTBExportModelParams) HasIncludeLinkedDocuments() bool {
	if o != nil && o.IncludeLinkedDocuments != nil {
		return true
	}

	return false
}

// SetIncludeLinkedDocuments gets a reference to the given bool and assigns it to the IncludeLinkedDocuments field.
func (o *BTBExportModelParams) SetIncludeLinkedDocuments(v bool) {
	o.IncludeLinkedDocuments = &v
}

// GetIncludeReleaseManagementData returns the IncludeReleaseManagementData field value if set, zero value otherwise.
func (o *BTBExportModelParams) GetIncludeReleaseManagementData() bool {
	if o == nil || o.IncludeReleaseManagementData == nil {
		var ret bool
		return ret
	}
	return *o.IncludeReleaseManagementData
}

// GetIncludeReleaseManagementDataOk returns a tuple with the IncludeReleaseManagementData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTBExportModelParams) GetIncludeReleaseManagementDataOk() (*bool, bool) {
	if o == nil || o.IncludeReleaseManagementData == nil {
		return nil, false
	}
	return o.IncludeReleaseManagementData, true
}

// HasIncludeReleaseManagementData returns a boolean if a field has been set.
func (o *BTBExportModelParams) HasIncludeReleaseManagementData() bool {
	if o != nil && o.IncludeReleaseManagementData != nil {
		return true
	}

	return false
}

// SetIncludeReleaseManagementData gets a reference to the given bool and assigns it to the IncludeReleaseManagementData field.
func (o *BTBExportModelParams) SetIncludeReleaseManagementData(v bool) {
	o.IncludeReleaseManagementData = &v
}

// GetIncludeSketches returns the IncludeSketches field value if set, zero value otherwise.
func (o *BTBExportModelParams) GetIncludeSketches() bool {
	if o == nil || o.IncludeSketches == nil {
		var ret bool
		return ret
	}
	return *o.IncludeSketches
}

// GetIncludeSketchesOk returns a tuple with the IncludeSketches field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTBExportModelParams) GetIncludeSketchesOk() (*bool, bool) {
	if o == nil || o.IncludeSketches == nil {
		return nil, false
	}
	return o.IncludeSketches, true
}

// HasIncludeSketches returns a boolean if a field has been set.
func (o *BTBExportModelParams) HasIncludeSketches() bool {
	if o != nil && o.IncludeSketches != nil {
		return true
	}

	return false
}

// SetIncludeSketches gets a reference to the given bool and assigns it to the IncludeSketches field.
func (o *BTBExportModelParams) SetIncludeSketches(v bool) {
	o.IncludeSketches = &v
}

// GetIncludeStd returns the IncludeStd field value if set, zero value otherwise.
func (o *BTBExportModelParams) GetIncludeStd() bool {
	if o == nil || o.IncludeStd == nil {
		var ret bool
		return ret
	}
	return *o.IncludeStd
}

// GetIncludeStdOk returns a tuple with the IncludeStd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTBExportModelParams) GetIncludeStdOk() (*bool, bool) {
	if o == nil || o.IncludeStd == nil {
		return nil, false
	}
	return o.IncludeStd, true
}

// HasIncludeStd returns a boolean if a field has been set.
func (o *BTBExportModelParams) HasIncludeStd() bool {
	if o != nil && o.IncludeStd != nil {
		return true
	}

	return false
}

// SetIncludeStd gets a reference to the given bool and assigns it to the IncludeStd field.
func (o *BTBExportModelParams) SetIncludeStd(v bool) {
	o.IncludeStd = &v
}

// GetIncludeThumbnails returns the IncludeThumbnails field value if set, zero value otherwise.
func (o *BTBExportModelParams) GetIncludeThumbnails() bool {
	if o == nil || o.IncludeThumbnails == nil {
		var ret bool
		return ret
	}
	return *o.IncludeThumbnails
}

// GetIncludeThumbnailsOk returns a tuple with the IncludeThumbnails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTBExportModelParams) GetIncludeThumbnailsOk() (*bool, bool) {
	if o == nil || o.IncludeThumbnails == nil {
		return nil, false
	}
	return o.IncludeThumbnails, true
}

// HasIncludeThumbnails returns a boolean if a field has been set.
func (o *BTBExportModelParams) HasIncludeThumbnails() bool {
	if o != nil && o.IncludeThumbnails != nil {
		return true
	}

	return false
}

// SetIncludeThumbnails gets a reference to the given bool and assigns it to the IncludeThumbnails field.
func (o *BTBExportModelParams) SetIncludeThumbnails(v bool) {
	o.IncludeThumbnails = &v
}

// GetIsPartingOut returns the IsPartingOut field value if set, zero value otherwise.
func (o *BTBExportModelParams) GetIsPartingOut() bool {
	if o == nil || o.IsPartingOut == nil {
		var ret bool
		return ret
	}
	return *o.IsPartingOut
}

// GetIsPartingOutOk returns a tuple with the IsPartingOut field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTBExportModelParams) GetIsPartingOutOk() (*bool, bool) {
	if o == nil || o.IsPartingOut == nil {
		return nil, false
	}
	return o.IsPartingOut, true
}

// HasIsPartingOut returns a boolean if a field has been set.
func (o *BTBExportModelParams) HasIsPartingOut() bool {
	if o != nil && o.IsPartingOut != nil {
		return true
	}

	return false
}

// SetIsPartingOut gets a reference to the given bool and assigns it to the IsPartingOut field.
func (o *BTBExportModelParams) SetIsPartingOut(v bool) {
	o.IsPartingOut = &v
}

// GetLinkDocumentId returns the LinkDocumentId field value if set, zero value otherwise.
func (o *BTBExportModelParams) GetLinkDocumentId() string {
	if o == nil || o.LinkDocumentId == nil {
		var ret string
		return ret
	}
	return *o.LinkDocumentId
}

// GetLinkDocumentIdOk returns a tuple with the LinkDocumentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTBExportModelParams) GetLinkDocumentIdOk() (*string, bool) {
	if o == nil || o.LinkDocumentId == nil {
		return nil, false
	}
	return o.LinkDocumentId, true
}

// HasLinkDocumentId returns a boolean if a field has been set.
func (o *BTBExportModelParams) HasLinkDocumentId() bool {
	if o != nil && o.LinkDocumentId != nil {
		return true
	}

	return false
}

// SetLinkDocumentId gets a reference to the given string and assigns it to the LinkDocumentId field.
func (o *BTBExportModelParams) SetLinkDocumentId(v string) {
	o.LinkDocumentId = &v
}

// GetLinkDocumentWorkspaceId returns the LinkDocumentWorkspaceId field value if set, zero value otherwise.
func (o *BTBExportModelParams) GetLinkDocumentWorkspaceId() string {
	if o == nil || o.LinkDocumentWorkspaceId == nil {
		var ret string
		return ret
	}
	return *o.LinkDocumentWorkspaceId
}

// GetLinkDocumentWorkspaceIdOk returns a tuple with the LinkDocumentWorkspaceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTBExportModelParams) GetLinkDocumentWorkspaceIdOk() (*string, bool) {
	if o == nil || o.LinkDocumentWorkspaceId == nil {
		return nil, false
	}
	return o.LinkDocumentWorkspaceId, true
}

// HasLinkDocumentWorkspaceId returns a boolean if a field has been set.
func (o *BTBExportModelParams) HasLinkDocumentWorkspaceId() bool {
	if o != nil && o.LinkDocumentWorkspaceId != nil {
		return true
	}

	return false
}

// SetLinkDocumentWorkspaceId gets a reference to the given string and assigns it to the LinkDocumentWorkspaceId field.
func (o *BTBExportModelParams) SetLinkDocumentWorkspaceId(v string) {
	o.LinkDocumentWorkspaceId = &v
}

// GetLinkedDocumentSubSetId returns the LinkedDocumentSubSetId field value if set, zero value otherwise.
func (o *BTBExportModelParams) GetLinkedDocumentSubSetId() string {
	if o == nil || o.LinkedDocumentSubSetId == nil {
		var ret string
		return ret
	}
	return *o.LinkedDocumentSubSetId
}

// GetLinkedDocumentSubSetIdOk returns a tuple with the LinkedDocumentSubSetId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTBExportModelParams) GetLinkedDocumentSubSetIdOk() (*string, bool) {
	if o == nil || o.LinkedDocumentSubSetId == nil {
		return nil, false
	}
	return o.LinkedDocumentSubSetId, true
}

// HasLinkedDocumentSubSetId returns a boolean if a field has been set.
func (o *BTBExportModelParams) HasLinkedDocumentSubSetId() bool {
	if o != nil && o.LinkedDocumentSubSetId != nil {
		return true
	}

	return false
}

// SetLinkedDocumentSubSetId gets a reference to the given string and assigns it to the LinkedDocumentSubSetId field.
func (o *BTBExportModelParams) SetLinkedDocumentSubSetId(v string) {
	o.LinkedDocumentSubSetId = &v
}

// GetMaxFacetWidth returns the MaxFacetWidth field value if set, zero value otherwise.
func (o *BTBExportModelParams) GetMaxFacetWidth() float64 {
	if o == nil || o.MaxFacetWidth == nil {
		var ret float64
		return ret
	}
	return *o.MaxFacetWidth
}

// GetMaxFacetWidthOk returns a tuple with the MaxFacetWidth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTBExportModelParams) GetMaxFacetWidthOk() (*float64, bool) {
	if o == nil || o.MaxFacetWidth == nil {
		return nil, false
	}
	return o.MaxFacetWidth, true
}

// HasMaxFacetWidth returns a boolean if a field has been set.
func (o *BTBExportModelParams) HasMaxFacetWidth() bool {
	if o != nil && o.MaxFacetWidth != nil {
		return true
	}

	return false
}

// SetMaxFacetWidth gets a reference to the given float64 and assigns it to the MaxFacetWidth field.
func (o *BTBExportModelParams) SetMaxFacetWidth(v float64) {
	o.MaxFacetWidth = &v
}

// GetMicroversion returns the Microversion field value if set, zero value otherwise.
func (o *BTBExportModelParams) GetMicroversion() string {
	if o == nil || o.Microversion == nil {
		var ret string
		return ret
	}
	return *o.Microversion
}

// GetMicroversionOk returns a tuple with the Microversion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTBExportModelParams) GetMicroversionOk() (*string, bool) {
	if o == nil || o.Microversion == nil {
		return nil, false
	}
	return o.Microversion, true
}

// HasMicroversion returns a boolean if a field has been set.
func (o *BTBExportModelParams) HasMicroversion() bool {
	if o != nil && o.Microversion != nil {
		return true
	}

	return false
}

// SetMicroversion gets a reference to the given string and assigns it to the Microversion field.
func (o *BTBExportModelParams) SetMicroversion(v string) {
	o.Microversion = &v
}

// GetMinFacetWidth returns the MinFacetWidth field value if set, zero value otherwise.
func (o *BTBExportModelParams) GetMinFacetWidth() float64 {
	if o == nil || o.MinFacetWidth == nil {
		var ret float64
		return ret
	}
	return *o.MinFacetWidth
}

// GetMinFacetWidthOk returns a tuple with the MinFacetWidth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTBExportModelParams) GetMinFacetWidthOk() (*float64, bool) {
	if o == nil || o.MinFacetWidth == nil {
		return nil, false
	}
	return o.MinFacetWidth, true
}

// HasMinFacetWidth returns a boolean if a field has been set.
func (o *BTBExportModelParams) HasMinFacetWidth() bool {
	if o != nil && o.MinFacetWidth != nil {
		return true
	}

	return false
}

// SetMinFacetWidth gets a reference to the given float64 and assigns it to the MinFacetWidth field.
func (o *BTBExportModelParams) SetMinFacetWidth(v float64) {
	o.MinFacetWidth = &v
}

// GetMode returns the Mode field value if set, zero value otherwise.
func (o *BTBExportModelParams) GetMode() string {
	if o == nil || o.Mode == nil {
		var ret string
		return ret
	}
	return *o.Mode
}

// GetModeOk returns a tuple with the Mode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTBExportModelParams) GetModeOk() (*string, bool) {
	if o == nil || o.Mode == nil {
		return nil, false
	}
	return o.Mode, true
}

// HasMode returns a boolean if a field has been set.
func (o *BTBExportModelParams) HasMode() bool {
	if o != nil && o.Mode != nil {
		return true
	}

	return false
}

// SetMode gets a reference to the given string and assigns it to the Mode field.
func (o *BTBExportModelParams) SetMode(v string) {
	o.Mode = &v
}

// GetPartIds returns the PartIds field value if set, zero value otherwise.
func (o *BTBExportModelParams) GetPartIds() string {
	if o == nil || o.PartIds == nil {
		var ret string
		return ret
	}
	return *o.PartIds
}

// GetPartIdsOk returns a tuple with the PartIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTBExportModelParams) GetPartIdsOk() (*string, bool) {
	if o == nil || o.PartIds == nil {
		return nil, false
	}
	return o.PartIds, true
}

// HasPartIds returns a boolean if a field has been set.
func (o *BTBExportModelParams) HasPartIds() bool {
	if o != nil && o.PartIds != nil {
		return true
	}

	return false
}

// SetPartIds gets a reference to the given string and assigns it to the PartIds field.
func (o *BTBExportModelParams) SetPartIds(v string) {
	o.PartIds = &v
}

// GetPartQuery returns the PartQuery field value if set, zero value otherwise.
func (o *BTBExportModelParams) GetPartQuery() string {
	if o == nil || o.PartQuery == nil {
		var ret string
		return ret
	}
	return *o.PartQuery
}

// GetPartQueryOk returns a tuple with the PartQuery field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTBExportModelParams) GetPartQueryOk() (*string, bool) {
	if o == nil || o.PartQuery == nil {
		return nil, false
	}
	return o.PartQuery, true
}

// HasPartQuery returns a boolean if a field has been set.
func (o *BTBExportModelParams) HasPartQuery() bool {
	if o != nil && o.PartQuery != nil {
		return true
	}

	return false
}

// SetPartQuery gets a reference to the given string and assigns it to the PartQuery field.
func (o *BTBExportModelParams) SetPartQuery(v string) {
	o.PartQuery = &v
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *BTBExportModelParams) GetPassword() string {
	if o == nil || o.Password == nil {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTBExportModelParams) GetPasswordOk() (*string, bool) {
	if o == nil || o.Password == nil {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *BTBExportModelParams) HasPassword() bool {
	if o != nil && o.Password != nil {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *BTBExportModelParams) SetPassword(v string) {
	o.Password = &v
}

// GetPasswordRequired returns the PasswordRequired field value if set, zero value otherwise.
func (o *BTBExportModelParams) GetPasswordRequired() bool {
	if o == nil || o.PasswordRequired == nil {
		var ret bool
		return ret
	}
	return *o.PasswordRequired
}

// GetPasswordRequiredOk returns a tuple with the PasswordRequired field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTBExportModelParams) GetPasswordRequiredOk() (*bool, bool) {
	if o == nil || o.PasswordRequired == nil {
		return nil, false
	}
	return o.PasswordRequired, true
}

// HasPasswordRequired returns a boolean if a field has been set.
func (o *BTBExportModelParams) HasPasswordRequired() bool {
	if o != nil && o.PasswordRequired != nil {
		return true
	}

	return false
}

// SetPasswordRequired gets a reference to the given bool and assigns it to the PasswordRequired field.
func (o *BTBExportModelParams) SetPasswordRequired(v bool) {
	o.PasswordRequired = &v
}

// GetResolution returns the Resolution field value if set, zero value otherwise.
func (o *BTBExportModelParams) GetResolution() string {
	if o == nil || o.Resolution == nil {
		var ret string
		return ret
	}
	return *o.Resolution
}

// GetResolutionOk returns a tuple with the Resolution field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTBExportModelParams) GetResolutionOk() (*string, bool) {
	if o == nil || o.Resolution == nil {
		return nil, false
	}
	return o.Resolution, true
}

// HasResolution returns a boolean if a field has been set.
func (o *BTBExportModelParams) HasResolution() bool {
	if o != nil && o.Resolution != nil {
		return true
	}

	return false
}

// SetResolution gets a reference to the given string and assigns it to the Resolution field.
func (o *BTBExportModelParams) SetResolution(v string) {
	o.Resolution = &v
}

// GetScale returns the Scale field value if set, zero value otherwise.
func (o *BTBExportModelParams) GetScale() float64 {
	if o == nil || o.Scale == nil {
		var ret float64
		return ret
	}
	return *o.Scale
}

// GetScaleOk returns a tuple with the Scale field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTBExportModelParams) GetScaleOk() (*float64, bool) {
	if o == nil || o.Scale == nil {
		return nil, false
	}
	return o.Scale, true
}

// HasScale returns a boolean if a field has been set.
func (o *BTBExportModelParams) HasScale() bool {
	if o != nil && o.Scale != nil {
		return true
	}

	return false
}

// SetScale gets a reference to the given float64 and assigns it to the Scale field.
func (o *BTBExportModelParams) SetScale(v float64) {
	o.Scale = &v
}

// GetSendCopyToMe returns the SendCopyToMe field value if set, zero value otherwise.
func (o *BTBExportModelParams) GetSendCopyToMe() bool {
	if o == nil || o.SendCopyToMe == nil {
		var ret bool
		return ret
	}
	return *o.SendCopyToMe
}

// GetSendCopyToMeOk returns a tuple with the SendCopyToMe field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTBExportModelParams) GetSendCopyToMeOk() (*bool, bool) {
	if o == nil || o.SendCopyToMe == nil {
		return nil, false
	}
	return o.SendCopyToMe, true
}

// HasSendCopyToMe returns a boolean if a field has been set.
func (o *BTBExportModelParams) HasSendCopyToMe() bool {
	if o != nil && o.SendCopyToMe != nil {
		return true
	}

	return false
}

// SetSendCopyToMe gets a reference to the given bool and assigns it to the SendCopyToMe field.
func (o *BTBExportModelParams) SetSendCopyToMe(v bool) {
	o.SendCopyToMe = &v
}

// GetSheetMetalFlat returns the SheetMetalFlat field value if set, zero value otherwise.
func (o *BTBExportModelParams) GetSheetMetalFlat() bool {
	if o == nil || o.SheetMetalFlat == nil {
		var ret bool
		return ret
	}
	return *o.SheetMetalFlat
}

// GetSheetMetalFlatOk returns a tuple with the SheetMetalFlat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTBExportModelParams) GetSheetMetalFlatOk() (*bool, bool) {
	if o == nil || o.SheetMetalFlat == nil {
		return nil, false
	}
	return o.SheetMetalFlat, true
}

// HasSheetMetalFlat returns a boolean if a field has been set.
func (o *BTBExportModelParams) HasSheetMetalFlat() bool {
	if o != nil && o.SheetMetalFlat != nil {
		return true
	}

	return false
}

// SetSheetMetalFlat gets a reference to the given bool and assigns it to the SheetMetalFlat field.
func (o *BTBExportModelParams) SetSheetMetalFlat(v bool) {
	o.SheetMetalFlat = &v
}

// GetSplinesAsPolylines returns the SplinesAsPolylines field value if set, zero value otherwise.
func (o *BTBExportModelParams) GetSplinesAsPolylines() bool {
	if o == nil || o.SplinesAsPolylines == nil {
		var ret bool
		return ret
	}
	return *o.SplinesAsPolylines
}

// GetSplinesAsPolylinesOk returns a tuple with the SplinesAsPolylines field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTBExportModelParams) GetSplinesAsPolylinesOk() (*bool, bool) {
	if o == nil || o.SplinesAsPolylines == nil {
		return nil, false
	}
	return o.SplinesAsPolylines, true
}

// HasSplinesAsPolylines returns a boolean if a field has been set.
func (o *BTBExportModelParams) HasSplinesAsPolylines() bool {
	if o != nil && o.SplinesAsPolylines != nil {
		return true
	}

	return false
}

// SetSplinesAsPolylines gets a reference to the given bool and assigns it to the SplinesAsPolylines field.
func (o *BTBExportModelParams) SetSplinesAsPolylines(v bool) {
	o.SplinesAsPolylines = &v
}

// GetStoreInDocument returns the StoreInDocument field value if set, zero value otherwise.
func (o *BTBExportModelParams) GetStoreInDocument() bool {
	if o == nil || o.StoreInDocument == nil {
		var ret bool
		return ret
	}
	return *o.StoreInDocument
}

// GetStoreInDocumentOk returns a tuple with the StoreInDocument field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTBExportModelParams) GetStoreInDocumentOk() (*bool, bool) {
	if o == nil || o.StoreInDocument == nil {
		return nil, false
	}
	return o.StoreInDocument, true
}

// HasStoreInDocument returns a boolean if a field has been set.
func (o *BTBExportModelParams) HasStoreInDocument() bool {
	if o != nil && o.StoreInDocument != nil {
		return true
	}

	return false
}

// SetStoreInDocument gets a reference to the given bool and assigns it to the StoreInDocument field.
func (o *BTBExportModelParams) SetStoreInDocument(v bool) {
	o.StoreInDocument = &v
}

// GetTriggerAutoDownload returns the TriggerAutoDownload field value if set, zero value otherwise.
func (o *BTBExportModelParams) GetTriggerAutoDownload() bool {
	if o == nil || o.TriggerAutoDownload == nil {
		var ret bool
		return ret
	}
	return *o.TriggerAutoDownload
}

// GetTriggerAutoDownloadOk returns a tuple with the TriggerAutoDownload field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTBExportModelParams) GetTriggerAutoDownloadOk() (*bool, bool) {
	if o == nil || o.TriggerAutoDownload == nil {
		return nil, false
	}
	return o.TriggerAutoDownload, true
}

// HasTriggerAutoDownload returns a boolean if a field has been set.
func (o *BTBExportModelParams) HasTriggerAutoDownload() bool {
	if o != nil && o.TriggerAutoDownload != nil {
		return true
	}

	return false
}

// SetTriggerAutoDownload gets a reference to the given bool and assigns it to the TriggerAutoDownload field.
func (o *BTBExportModelParams) SetTriggerAutoDownload(v bool) {
	o.TriggerAutoDownload = &v
}

// GetUnits returns the Units field value if set, zero value otherwise.
func (o *BTBExportModelParams) GetUnits() string {
	if o == nil || o.Units == nil {
		var ret string
		return ret
	}
	return *o.Units
}

// GetUnitsOk returns a tuple with the Units field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTBExportModelParams) GetUnitsOk() (*string, bool) {
	if o == nil || o.Units == nil {
		return nil, false
	}
	return o.Units, true
}

// HasUnits returns a boolean if a field has been set.
func (o *BTBExportModelParams) HasUnits() bool {
	if o != nil && o.Units != nil {
		return true
	}

	return false
}

// SetUnits gets a reference to the given string and assigns it to the Units field.
func (o *BTBExportModelParams) SetUnits(v string) {
	o.Units = &v
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *BTBExportModelParams) GetUserId() string {
	if o == nil || o.UserId == nil {
		var ret string
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTBExportModelParams) GetUserIdOk() (*string, bool) {
	if o == nil || o.UserId == nil {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *BTBExportModelParams) HasUserId() bool {
	if o != nil && o.UserId != nil {
		return true
	}

	return false
}

// SetUserId gets a reference to the given string and assigns it to the UserId field.
func (o *BTBExportModelParams) SetUserId(v string) {
	o.UserId = &v
}

// GetValidForDays returns the ValidForDays field value if set, zero value otherwise.
func (o *BTBExportModelParams) GetValidForDays() int32 {
	if o == nil || o.ValidForDays == nil {
		var ret int32
		return ret
	}
	return *o.ValidForDays
}

// GetValidForDaysOk returns a tuple with the ValidForDays field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTBExportModelParams) GetValidForDaysOk() (*int32, bool) {
	if o == nil || o.ValidForDays == nil {
		return nil, false
	}
	return o.ValidForDays, true
}

// HasValidForDays returns a boolean if a field has been set.
func (o *BTBExportModelParams) HasValidForDays() bool {
	if o != nil && o.ValidForDays != nil {
		return true
	}

	return false
}

// SetValidForDays gets a reference to the given int32 and assigns it to the ValidForDays field.
func (o *BTBExportModelParams) SetValidForDays(v int32) {
	o.ValidForDays = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *BTBExportModelParams) GetVersion() string {
	if o == nil || o.Version == nil {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTBExportModelParams) GetVersionOk() (*string, bool) {
	if o == nil || o.Version == nil {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *BTBExportModelParams) HasVersion() bool {
	if o != nil && o.Version != nil {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *BTBExportModelParams) SetVersion(v string) {
	o.Version = &v
}

// GetView returns the View field value if set, zero value otherwise.
func (o *BTBExportModelParams) GetView() string {
	if o == nil || o.View == nil {
		var ret string
		return ret
	}
	return *o.View
}

// GetViewOk returns a tuple with the View field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTBExportModelParams) GetViewOk() (*string, bool) {
	if o == nil || o.View == nil {
		return nil, false
	}
	return o.View, true
}

// HasView returns a boolean if a field has been set.
func (o *BTBExportModelParams) HasView() bool {
	if o != nil && o.View != nil {
		return true
	}

	return false
}

// SetView gets a reference to the given string and assigns it to the View field.
func (o *BTBExportModelParams) SetView(v string) {
	o.View = &v
}

// GetWorkspaceId returns the WorkspaceId field value if set, zero value otherwise.
func (o *BTBExportModelParams) GetWorkspaceId() string {
	if o == nil || o.WorkspaceId == nil {
		var ret string
		return ret
	}
	return *o.WorkspaceId
}

// GetWorkspaceIdOk returns a tuple with the WorkspaceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTBExportModelParams) GetWorkspaceIdOk() (*string, bool) {
	if o == nil || o.WorkspaceId == nil {
		return nil, false
	}
	return o.WorkspaceId, true
}

// HasWorkspaceId returns a boolean if a field has been set.
func (o *BTBExportModelParams) HasWorkspaceId() bool {
	if o != nil && o.WorkspaceId != nil {
		return true
	}

	return false
}

// SetWorkspaceId gets a reference to the given string and assigns it to the WorkspaceId field.
func (o *BTBExportModelParams) SetWorkspaceId(v string) {
	o.WorkspaceId = &v
}

// GetZipSingleFileOutput returns the ZipSingleFileOutput field value if set, zero value otherwise.
func (o *BTBExportModelParams) GetZipSingleFileOutput() bool {
	if o == nil || o.ZipSingleFileOutput == nil {
		var ret bool
		return ret
	}
	return *o.ZipSingleFileOutput
}

// GetZipSingleFileOutputOk returns a tuple with the ZipSingleFileOutput field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTBExportModelParams) GetZipSingleFileOutputOk() (*bool, bool) {
	if o == nil || o.ZipSingleFileOutput == nil {
		return nil, false
	}
	return o.ZipSingleFileOutput, true
}

// HasZipSingleFileOutput returns a boolean if a field has been set.
func (o *BTBExportModelParams) HasZipSingleFileOutput() bool {
	if o != nil && o.ZipSingleFileOutput != nil {
		return true
	}

	return false
}

// SetZipSingleFileOutput gets a reference to the given bool and assigns it to the ZipSingleFileOutput field.
func (o *BTBExportModelParams) SetZipSingleFileOutput(v bool) {
	o.ZipSingleFileOutput = &v
}

func (o BTBExportModelParams) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.AngleTolerance != nil {
		toSerialize["angleTolerance"] = o.AngleTolerance
	}
	if o.BatchFlatPatterns != nil {
		toSerialize["batchFlatPatterns"] = o.BatchFlatPatterns
	}
	if o.ChordTolerance != nil {
		toSerialize["chordTolerance"] = o.ChordTolerance
	}
	if o.CloudObjectId != nil {
		toSerialize["cloudObjectId"] = o.CloudObjectId
	}
	if o.CloudStorageAccountId != nil {
		toSerialize["cloudStorageAccountId"] = o.CloudStorageAccountId
	}
	if o.Configuration != nil {
		toSerialize["configuration"] = o.Configuration
	}
	if o.DeepSearchForForeignData != nil {
		toSerialize["deepSearchForForeignData"] = o.DeepSearchForForeignData
	}
	if o.DestinationName != nil {
		toSerialize["destinationName"] = o.DestinationName
	}
	if true {
		toSerialize["documentId"] = o.DocumentId
	}
	if o.DocumentVersionId != nil {
		toSerialize["documentVersionId"] = o.DocumentVersionId
	}
	if o.ElementId != nil {
		toSerialize["elementId"] = o.ElementId
	}
	if o.ElementIds != nil {
		toSerialize["elementIds"] = o.ElementIds
	}
	if o.EmailLink != nil {
		toSerialize["emailLink"] = o.EmailLink
	}
	if o.EmailMessage != nil {
		toSerialize["emailMessage"] = o.EmailMessage
	}
	if o.EmailSubject != nil {
		toSerialize["emailSubject"] = o.EmailSubject
	}
	if o.EmailTo != nil {
		toSerialize["emailTo"] = o.EmailTo
	}
	if o.ExtractToS3 != nil {
		toSerialize["extractToS3"] = o.ExtractToS3
	}
	if o.FeatureIds != nil {
		toSerialize["featureIds"] = o.FeatureIds
	}
	if o.Flatten != nil {
		toSerialize["flatten"] = o.Flatten
	}
	if true {
		toSerialize["format"] = o.Format
	}
	if o.FromUserId != nil {
		toSerialize["fromUserId"] = o.FromUserId
	}
	if o.Grouping != nil {
		toSerialize["grouping"] = o.Grouping
	}
	if o.IncludeBendCenterlines != nil {
		toSerialize["includeBendCenterlines"] = o.IncludeBendCenterlines
	}
	if o.IncludeBendLines != nil {
		toSerialize["includeBendLines"] = o.IncludeBendLines
	}
	if o.IncludeComments != nil {
		toSerialize["includeComments"] = o.IncludeComments
	}
	if o.IncludeContentCaptures != nil {
		toSerialize["includeContentCaptures"] = o.IncludeContentCaptures
	}
	if o.IncludeCustomPropertiesData != nil {
		toSerialize["includeCustomPropertiesData"] = o.IncludeCustomPropertiesData
	}
	if o.IncludeExportIds != nil {
		toSerialize["includeExportIds"] = o.IncludeExportIds
	}
	if o.IncludeForeignData != nil {
		toSerialize["includeForeignData"] = o.IncludeForeignData
	}
	if o.IncludeItemsData != nil {
		toSerialize["includeItemsData"] = o.IncludeItemsData
	}
	if o.IncludeLinkedDocuments != nil {
		toSerialize["includeLinkedDocuments"] = o.IncludeLinkedDocuments
	}
	if o.IncludeReleaseManagementData != nil {
		toSerialize["includeReleaseManagementData"] = o.IncludeReleaseManagementData
	}
	if o.IncludeSketches != nil {
		toSerialize["includeSketches"] = o.IncludeSketches
	}
	if o.IncludeStd != nil {
		toSerialize["includeStd"] = o.IncludeStd
	}
	if o.IncludeThumbnails != nil {
		toSerialize["includeThumbnails"] = o.IncludeThumbnails
	}
	if o.IsPartingOut != nil {
		toSerialize["isPartingOut"] = o.IsPartingOut
	}
	if o.LinkDocumentId != nil {
		toSerialize["linkDocumentId"] = o.LinkDocumentId
	}
	if o.LinkDocumentWorkspaceId != nil {
		toSerialize["linkDocumentWorkspaceId"] = o.LinkDocumentWorkspaceId
	}
	if o.LinkedDocumentSubSetId != nil {
		toSerialize["linkedDocumentSubSetId"] = o.LinkedDocumentSubSetId
	}
	if o.MaxFacetWidth != nil {
		toSerialize["maxFacetWidth"] = o.MaxFacetWidth
	}
	if o.Microversion != nil {
		toSerialize["microversion"] = o.Microversion
	}
	if o.MinFacetWidth != nil {
		toSerialize["minFacetWidth"] = o.MinFacetWidth
	}
	if o.Mode != nil {
		toSerialize["mode"] = o.Mode
	}
	if o.PartIds != nil {
		toSerialize["partIds"] = o.PartIds
	}
	if o.PartQuery != nil {
		toSerialize["partQuery"] = o.PartQuery
	}
	if o.Password != nil {
		toSerialize["password"] = o.Password
	}
	if o.PasswordRequired != nil {
		toSerialize["passwordRequired"] = o.PasswordRequired
	}
	if o.Resolution != nil {
		toSerialize["resolution"] = o.Resolution
	}
	if o.Scale != nil {
		toSerialize["scale"] = o.Scale
	}
	if o.SendCopyToMe != nil {
		toSerialize["sendCopyToMe"] = o.SendCopyToMe
	}
	if o.SheetMetalFlat != nil {
		toSerialize["sheetMetalFlat"] = o.SheetMetalFlat
	}
	if o.SplinesAsPolylines != nil {
		toSerialize["splinesAsPolylines"] = o.SplinesAsPolylines
	}
	if o.StoreInDocument != nil {
		toSerialize["storeInDocument"] = o.StoreInDocument
	}
	if o.TriggerAutoDownload != nil {
		toSerialize["triggerAutoDownload"] = o.TriggerAutoDownload
	}
	if o.Units != nil {
		toSerialize["units"] = o.Units
	}
	if o.UserId != nil {
		toSerialize["userId"] = o.UserId
	}
	if o.ValidForDays != nil {
		toSerialize["validForDays"] = o.ValidForDays
	}
	if o.Version != nil {
		toSerialize["version"] = o.Version
	}
	if o.View != nil {
		toSerialize["view"] = o.View
	}
	if o.WorkspaceId != nil {
		toSerialize["workspaceId"] = o.WorkspaceId
	}
	if o.ZipSingleFileOutput != nil {
		toSerialize["zipSingleFileOutput"] = o.ZipSingleFileOutput
	}
	return json.Marshal(toSerialize)
}

type NullableBTBExportModelParams struct {
	value *BTBExportModelParams
	isSet bool
}

func (v NullableBTBExportModelParams) Get() *BTBExportModelParams {
	return v.value
}

func (v *NullableBTBExportModelParams) Set(val *BTBExportModelParams) {
	v.value = val
	v.isSet = true
}

func (v NullableBTBExportModelParams) IsSet() bool {
	return v.isSet
}

func (v *NullableBTBExportModelParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBTBExportModelParams(val *BTBExportModelParams) *NullableBTBExportModelParams {
	return &NullableBTBExportModelParams{value: val, isSet: true}
}

func (v NullableBTBExportModelParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBTBExportModelParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
