/*
Onshape REST API

## Welcome to the Onshape REST API Explorer  **See the [API Explorer Guide](https://onshape-public.github.io/docs/api-intro/explorer/) for help navigating this page.**  ### Using this page 1. Sign in to your [Onshape](https://cad.onshape.com) account in another tab. 2. Click the `Try it out` button below. It toggles to a `Cancel` button when selected.  ### Authenticating To authenticate your calls, click the `Authorize` button. See [API Explorer Guide: Authentication](https://onshape-public.github.io/docs/api-intro/explorer/#authentication) for details. Calls made when authenticated via API Keys or OAuth count against your annual [API limits](https://onshape-public.github.io/docs/auth/limits/#annual-api-call-limits). * **Tip:** To ensure the current session isn't used when trying other authentication techniques, make sure to [remove the Onshape cookie](https://support.google.com/chrome/answer/95647#zippy=%2Cdelete-cookies-from-a-site) as per the instructions for your browser, or use a private or incognito window.  ### Additional resources  * [Onshape API Guide](https://onshape-public.github.io/docs/): Our full suite of developer guides, to be used as an accompaniment to this API Explorer. * [Onshape Developer Portal](https://cad.onshape.com/appstore/dev-portal): The Onshape portal for managing your API keys, OAuth2 credentials, your Onshape applications, and your Onshape App Store entries. * [Authentication Guide](https://onshape-public.github.io/docs/auth/): Our guide to using API keys, request signatures, and OAuth2 in your Onshape applications.

Contact: api-support@onshape.zendesk.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package onshape

import (
	"encoding/json"
)

// BTSMApplicationTypeFilter4430 struct for BTSMApplicationTypeFilter4430
type BTSMApplicationTypeFilter4430 struct {
	BTQueryFilter183
	BtType            *string               `json:"btType,omitempty"`
	SmApplicationType *GBTSMApplicationType `json:"smApplicationType,omitempty"`
}

// NewBTSMApplicationTypeFilter4430 instantiates a new BTSMApplicationTypeFilter4430 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBTSMApplicationTypeFilter4430() *BTSMApplicationTypeFilter4430 {
	this := BTSMApplicationTypeFilter4430{}
	return &this
}

// NewBTSMApplicationTypeFilter4430WithDefaults instantiates a new BTSMApplicationTypeFilter4430 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBTSMApplicationTypeFilter4430WithDefaults() *BTSMApplicationTypeFilter4430 {
	this := BTSMApplicationTypeFilter4430{}
	return &this
}

// GetBtType returns the BtType field value if set, zero value otherwise.
func (o *BTSMApplicationTypeFilter4430) GetBtType() string {
	if o == nil || o.BtType == nil {
		var ret string
		return ret
	}
	return *o.BtType
}

// GetBtTypeOk returns a tuple with the BtType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTSMApplicationTypeFilter4430) GetBtTypeOk() (*string, bool) {
	if o == nil || o.BtType == nil {
		return nil, false
	}
	return o.BtType, true
}

// HasBtType returns a boolean if a field has been set.
func (o *BTSMApplicationTypeFilter4430) HasBtType() bool {
	if o != nil && o.BtType != nil {
		return true
	}

	return false
}

// SetBtType gets a reference to the given string and assigns it to the BtType field.
func (o *BTSMApplicationTypeFilter4430) SetBtType(v string) {
	o.BtType = &v
}

// GetSmApplicationType returns the SmApplicationType field value if set, zero value otherwise.
func (o *BTSMApplicationTypeFilter4430) GetSmApplicationType() GBTSMApplicationType {
	if o == nil || o.SmApplicationType == nil {
		var ret GBTSMApplicationType
		return ret
	}
	return *o.SmApplicationType
}

// GetSmApplicationTypeOk returns a tuple with the SmApplicationType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTSMApplicationTypeFilter4430) GetSmApplicationTypeOk() (*GBTSMApplicationType, bool) {
	if o == nil || o.SmApplicationType == nil {
		return nil, false
	}
	return o.SmApplicationType, true
}

// HasSmApplicationType returns a boolean if a field has been set.
func (o *BTSMApplicationTypeFilter4430) HasSmApplicationType() bool {
	if o != nil && o.SmApplicationType != nil {
		return true
	}

	return false
}

// SetSmApplicationType gets a reference to the given GBTSMApplicationType and assigns it to the SmApplicationType field.
func (o *BTSMApplicationTypeFilter4430) SetSmApplicationType(v GBTSMApplicationType) {
	o.SmApplicationType = &v
}

func (o BTSMApplicationTypeFilter4430) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	serializedBTQueryFilter183, errBTQueryFilter183 := json.Marshal(o.BTQueryFilter183)
	if errBTQueryFilter183 != nil {
		return []byte{}, errBTQueryFilter183
	}
	errBTQueryFilter183 = json.Unmarshal([]byte(serializedBTQueryFilter183), &toSerialize)
	if errBTQueryFilter183 != nil {
		return []byte{}, errBTQueryFilter183
	}
	if o.BtType != nil {
		toSerialize["btType"] = o.BtType
	}
	if o.SmApplicationType != nil {
		toSerialize["smApplicationType"] = o.SmApplicationType
	}
	return json.Marshal(toSerialize)
}

type NullableBTSMApplicationTypeFilter4430 struct {
	value *BTSMApplicationTypeFilter4430
	isSet bool
}

func (v NullableBTSMApplicationTypeFilter4430) Get() *BTSMApplicationTypeFilter4430 {
	return v.value
}

func (v *NullableBTSMApplicationTypeFilter4430) Set(val *BTSMApplicationTypeFilter4430) {
	v.value = val
	v.isSet = true
}

func (v NullableBTSMApplicationTypeFilter4430) IsSet() bool {
	return v.isSet
}

func (v *NullableBTSMApplicationTypeFilter4430) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBTSMApplicationTypeFilter4430(val *BTSMApplicationTypeFilter4430) *NullableBTSMApplicationTypeFilter4430 {
	return &NullableBTSMApplicationTypeFilter4430{value: val, isSet: true}
}

func (v NullableBTSMApplicationTypeFilter4430) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBTSMApplicationTypeFilter4430) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
