/*
 * Onshape REST API
 *
 * The Onshape REST API consumed by all clients.
 *
 * API version: 1.113
 * Contact: api-support@onshape.zendesk.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package onshape

import (
	"encoding/json"
)

// BTImageFilter853AllOf struct for BTImageFilter853AllOf
type BTImageFilter853AllOf struct {
	BtType *string `json:"btType,omitempty"`
	IsImage *bool `json:"isImage,omitempty"`
}

// NewBTImageFilter853AllOf instantiates a new BTImageFilter853AllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBTImageFilter853AllOf() *BTImageFilter853AllOf {
	this := BTImageFilter853AllOf{}
	return &this
}

// NewBTImageFilter853AllOfWithDefaults instantiates a new BTImageFilter853AllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBTImageFilter853AllOfWithDefaults() *BTImageFilter853AllOf {
	this := BTImageFilter853AllOf{}
	return &this
}

// GetBtType returns the BtType field value if set, zero value otherwise.
func (o *BTImageFilter853AllOf) GetBtType() string {
	if o == nil || o.BtType == nil {
		var ret string
		return ret
	}
	return *o.BtType
}

// GetBtTypeOk returns a tuple with the BtType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTImageFilter853AllOf) GetBtTypeOk() (*string, bool) {
	if o == nil || o.BtType == nil {
		return nil, false
	}
	return o.BtType, true
}

// HasBtType returns a boolean if a field has been set.
func (o *BTImageFilter853AllOf) HasBtType() bool {
	if o != nil && o.BtType != nil {
		return true
	}

	return false
}

// SetBtType gets a reference to the given string and assigns it to the BtType field.
func (o *BTImageFilter853AllOf) SetBtType(v string) {
	o.BtType = &v
}

// GetIsImage returns the IsImage field value if set, zero value otherwise.
func (o *BTImageFilter853AllOf) GetIsImage() bool {
	if o == nil || o.IsImage == nil {
		var ret bool
		return ret
	}
	return *o.IsImage
}

// GetIsImageOk returns a tuple with the IsImage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTImageFilter853AllOf) GetIsImageOk() (*bool, bool) {
	if o == nil || o.IsImage == nil {
		return nil, false
	}
	return o.IsImage, true
}

// HasIsImage returns a boolean if a field has been set.
func (o *BTImageFilter853AllOf) HasIsImage() bool {
	if o != nil && o.IsImage != nil {
		return true
	}

	return false
}

// SetIsImage gets a reference to the given bool and assigns it to the IsImage field.
func (o *BTImageFilter853AllOf) SetIsImage(v bool) {
	o.IsImage = &v
}

func (o BTImageFilter853AllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.BtType != nil {
		toSerialize["btType"] = o.BtType
	}
	if o.IsImage != nil {
		toSerialize["isImage"] = o.IsImage
	}
	return json.Marshal(toSerialize)
}

type NullableBTImageFilter853AllOf struct {
	value *BTImageFilter853AllOf
	isSet bool
}

func (v NullableBTImageFilter853AllOf) Get() *BTImageFilter853AllOf {
	return v.value
}

func (v *NullableBTImageFilter853AllOf) Set(val *BTImageFilter853AllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableBTImageFilter853AllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableBTImageFilter853AllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBTImageFilter853AllOf(val *BTImageFilter853AllOf) *NullableBTImageFilter853AllOf {
	return &NullableBTImageFilter853AllOf{value: val, isSet: true}
}

func (v NullableBTImageFilter853AllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBTImageFilter853AllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
