/*
Onshape REST API

## Welcome to the Onshape REST API Explorer  **See the [API Explorer Guide](https://onshape-public.github.io/docs/api-intro/explorer/) for help navigating this page.**  ### Using this page 1. Sign in to your [Onshape](https://cad.onshape.com) account in another tab. 2. Click the `Try it out` button below. It toggles to a `Cancel` button when selected.  ### Authenticating To authenticate your calls, click the `Authorize` button. See [API Explorer Guide: Authentication](https://onshape-public.github.io/docs/api-intro/explorer/#authentication) for details. Calls made when authenticated via API Keys or OAuth count against your annual [API limits](https://onshape-public.github.io/docs/auth/limits/#annual-api-call-limits). * **Tip:** To ensure the current session isn't used when trying other authentication techniques, make sure to [remove the Onshape cookie](https://support.google.com/chrome/answer/95647#zippy=%2Cdelete-cookies-from-a-site) as per the instructions for your browser, or use a private or incognito window.  ### Additional resources  * [Onshape API Guide](https://onshape-public.github.io/docs/): Our full suite of developer guides, to be used as an accompaniment to this API Explorer. * [Onshape Developer Portal](https://cad.onshape.com/appstore/dev-portal): The Onshape portal for managing your API keys, OAuth2 credentials, your Onshape applications, and your Onshape App Store entries. * [Authentication Guide](https://onshape-public.github.io/docs/auth/): Our guide to using API keys, request signatures, and OAuth2 in your Onshape applications.

Contact: api-support@onshape.zendesk.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package onshape

import (
	"encoding/json"
)

// BTAppArrayInfoBTAppDrawingViewInfo struct for BTAppArrayInfoBTAppDrawingViewInfo
type BTAppArrayInfoBTAppDrawingViewInfo struct {
	ChangeId *string `json:"changeId,omitempty"`
	// `0: OK (healthy) | 1: INFO | 2: WARNING | 3: ERROR (dangling or view generation call failed) | 4: UNKNOWN`
	ErrorCode *int32 `json:"errorCode,omitempty"`
	// A human-readable value for the error that occurred, if one occurred.
	ErrorDescription *string                `json:"errorDescription,omitempty"`
	ErrorValue       *BTAppElementErrorCode `json:"errorValue,omitempty"`
	Items            []BTAppDrawingViewInfo `json:"items,omitempty"`
	ParentChangeId   *string                `json:"parentChangeId,omitempty"`
}

// NewBTAppArrayInfoBTAppDrawingViewInfo instantiates a new BTAppArrayInfoBTAppDrawingViewInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBTAppArrayInfoBTAppDrawingViewInfo() *BTAppArrayInfoBTAppDrawingViewInfo {
	this := BTAppArrayInfoBTAppDrawingViewInfo{}
	return &this
}

// NewBTAppArrayInfoBTAppDrawingViewInfoWithDefaults instantiates a new BTAppArrayInfoBTAppDrawingViewInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBTAppArrayInfoBTAppDrawingViewInfoWithDefaults() *BTAppArrayInfoBTAppDrawingViewInfo {
	this := BTAppArrayInfoBTAppDrawingViewInfo{}
	return &this
}

// GetChangeId returns the ChangeId field value if set, zero value otherwise.
func (o *BTAppArrayInfoBTAppDrawingViewInfo) GetChangeId() string {
	if o == nil || o.ChangeId == nil {
		var ret string
		return ret
	}
	return *o.ChangeId
}

// GetChangeIdOk returns a tuple with the ChangeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTAppArrayInfoBTAppDrawingViewInfo) GetChangeIdOk() (*string, bool) {
	if o == nil || o.ChangeId == nil {
		return nil, false
	}
	return o.ChangeId, true
}

// HasChangeId returns a boolean if a field has been set.
func (o *BTAppArrayInfoBTAppDrawingViewInfo) HasChangeId() bool {
	if o != nil && o.ChangeId != nil {
		return true
	}

	return false
}

// SetChangeId gets a reference to the given string and assigns it to the ChangeId field.
func (o *BTAppArrayInfoBTAppDrawingViewInfo) SetChangeId(v string) {
	o.ChangeId = &v
}

// GetErrorCode returns the ErrorCode field value if set, zero value otherwise.
func (o *BTAppArrayInfoBTAppDrawingViewInfo) GetErrorCode() int32 {
	if o == nil || o.ErrorCode == nil {
		var ret int32
		return ret
	}
	return *o.ErrorCode
}

// GetErrorCodeOk returns a tuple with the ErrorCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTAppArrayInfoBTAppDrawingViewInfo) GetErrorCodeOk() (*int32, bool) {
	if o == nil || o.ErrorCode == nil {
		return nil, false
	}
	return o.ErrorCode, true
}

// HasErrorCode returns a boolean if a field has been set.
func (o *BTAppArrayInfoBTAppDrawingViewInfo) HasErrorCode() bool {
	if o != nil && o.ErrorCode != nil {
		return true
	}

	return false
}

// SetErrorCode gets a reference to the given int32 and assigns it to the ErrorCode field.
func (o *BTAppArrayInfoBTAppDrawingViewInfo) SetErrorCode(v int32) {
	o.ErrorCode = &v
}

// GetErrorDescription returns the ErrorDescription field value if set, zero value otherwise.
func (o *BTAppArrayInfoBTAppDrawingViewInfo) GetErrorDescription() string {
	if o == nil || o.ErrorDescription == nil {
		var ret string
		return ret
	}
	return *o.ErrorDescription
}

// GetErrorDescriptionOk returns a tuple with the ErrorDescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTAppArrayInfoBTAppDrawingViewInfo) GetErrorDescriptionOk() (*string, bool) {
	if o == nil || o.ErrorDescription == nil {
		return nil, false
	}
	return o.ErrorDescription, true
}

// HasErrorDescription returns a boolean if a field has been set.
func (o *BTAppArrayInfoBTAppDrawingViewInfo) HasErrorDescription() bool {
	if o != nil && o.ErrorDescription != nil {
		return true
	}

	return false
}

// SetErrorDescription gets a reference to the given string and assigns it to the ErrorDescription field.
func (o *BTAppArrayInfoBTAppDrawingViewInfo) SetErrorDescription(v string) {
	o.ErrorDescription = &v
}

// GetErrorValue returns the ErrorValue field value if set, zero value otherwise.
func (o *BTAppArrayInfoBTAppDrawingViewInfo) GetErrorValue() BTAppElementErrorCode {
	if o == nil || o.ErrorValue == nil {
		var ret BTAppElementErrorCode
		return ret
	}
	return *o.ErrorValue
}

// GetErrorValueOk returns a tuple with the ErrorValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTAppArrayInfoBTAppDrawingViewInfo) GetErrorValueOk() (*BTAppElementErrorCode, bool) {
	if o == nil || o.ErrorValue == nil {
		return nil, false
	}
	return o.ErrorValue, true
}

// HasErrorValue returns a boolean if a field has been set.
func (o *BTAppArrayInfoBTAppDrawingViewInfo) HasErrorValue() bool {
	if o != nil && o.ErrorValue != nil {
		return true
	}

	return false
}

// SetErrorValue gets a reference to the given BTAppElementErrorCode and assigns it to the ErrorValue field.
func (o *BTAppArrayInfoBTAppDrawingViewInfo) SetErrorValue(v BTAppElementErrorCode) {
	o.ErrorValue = &v
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *BTAppArrayInfoBTAppDrawingViewInfo) GetItems() []BTAppDrawingViewInfo {
	if o == nil || o.Items == nil {
		var ret []BTAppDrawingViewInfo
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTAppArrayInfoBTAppDrawingViewInfo) GetItemsOk() ([]BTAppDrawingViewInfo, bool) {
	if o == nil || o.Items == nil {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *BTAppArrayInfoBTAppDrawingViewInfo) HasItems() bool {
	if o != nil && o.Items != nil {
		return true
	}

	return false
}

// SetItems gets a reference to the given []BTAppDrawingViewInfo and assigns it to the Items field.
func (o *BTAppArrayInfoBTAppDrawingViewInfo) SetItems(v []BTAppDrawingViewInfo) {
	o.Items = v
}

// GetParentChangeId returns the ParentChangeId field value if set, zero value otherwise.
func (o *BTAppArrayInfoBTAppDrawingViewInfo) GetParentChangeId() string {
	if o == nil || o.ParentChangeId == nil {
		var ret string
		return ret
	}
	return *o.ParentChangeId
}

// GetParentChangeIdOk returns a tuple with the ParentChangeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BTAppArrayInfoBTAppDrawingViewInfo) GetParentChangeIdOk() (*string, bool) {
	if o == nil || o.ParentChangeId == nil {
		return nil, false
	}
	return o.ParentChangeId, true
}

// HasParentChangeId returns a boolean if a field has been set.
func (o *BTAppArrayInfoBTAppDrawingViewInfo) HasParentChangeId() bool {
	if o != nil && o.ParentChangeId != nil {
		return true
	}

	return false
}

// SetParentChangeId gets a reference to the given string and assigns it to the ParentChangeId field.
func (o *BTAppArrayInfoBTAppDrawingViewInfo) SetParentChangeId(v string) {
	o.ParentChangeId = &v
}

func (o BTAppArrayInfoBTAppDrawingViewInfo) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ChangeId != nil {
		toSerialize["changeId"] = o.ChangeId
	}
	if o.ErrorCode != nil {
		toSerialize["errorCode"] = o.ErrorCode
	}
	if o.ErrorDescription != nil {
		toSerialize["errorDescription"] = o.ErrorDescription
	}
	if o.ErrorValue != nil {
		toSerialize["errorValue"] = o.ErrorValue
	}
	if o.Items != nil {
		toSerialize["items"] = o.Items
	}
	if o.ParentChangeId != nil {
		toSerialize["parentChangeId"] = o.ParentChangeId
	}
	return json.Marshal(toSerialize)
}

type NullableBTAppArrayInfoBTAppDrawingViewInfo struct {
	value *BTAppArrayInfoBTAppDrawingViewInfo
	isSet bool
}

func (v NullableBTAppArrayInfoBTAppDrawingViewInfo) Get() *BTAppArrayInfoBTAppDrawingViewInfo {
	return v.value
}

func (v *NullableBTAppArrayInfoBTAppDrawingViewInfo) Set(val *BTAppArrayInfoBTAppDrawingViewInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableBTAppArrayInfoBTAppDrawingViewInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableBTAppArrayInfoBTAppDrawingViewInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBTAppArrayInfoBTAppDrawingViewInfo(val *BTAppArrayInfoBTAppDrawingViewInfo) *NullableBTAppArrayInfoBTAppDrawingViewInfo {
	return &NullableBTAppArrayInfoBTAppDrawingViewInfo{value: val, isSet: true}
}

func (v NullableBTAppArrayInfoBTAppDrawingViewInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBTAppArrayInfoBTAppDrawingViewInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
